NOTE: Notebook to inspect the experimental dataset and Beagle-generated files in order to design a merge approach

In [1]:
import BECancerResistome
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt

## Load Beagle Files

In [2]:
#MC
mc_beagle = pd.read_csv("data/1_Beagle_design_files/MC/MC_guides.txt", sep="\t")

#GR
gr_beagle = pd.read_csv("data/1_Beagle_design_files/GR/GR-guides-standardized.txt", sep="\t")

#EG
eg_beagle = pd.read_csv("data/1_Beagle_design_files/EG/EG-guides.txt", sep="\t")

#RH 
#BCL2L1_MCL1
rh_bcl2l1_mcl1_beagle = pd.read_csv("data/1_Beagle_design_files/RH/BCL2L1_MCL1-guides.txt", sep="\t")
#BRCA1_BRCA2
rh_brca1_brca2_beagle = pd.read_csv("data/1_Beagle_design_files/RH/BRCA1_BRCA2-guides.txt", sep="\t")
#PARP1
rh_parp1_beagle = pd.read_csv("data/1_Beagle_design_files/RH/PARP1-guides.txt", sep="\t")

## Load Experimental Data - zscores

In [3]:
zscores = pd.read_csv("data/complete_merge_Zscores_pDNA.csv", sep=",")

#drop the first column (indices)
#zscores = zscores.drop(zscores.columns[0], axis=1)

In [4]:
pd.set_option('display.max_rows', None)

In [5]:
zscores.head()

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,...,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
0,AAAAAACAAAGAGGTTAAGT,NaN,NaN,-0.951173,-0.705150,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAAAAACATACCTCAACCCT,Unknown,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAAAAACATACCTCAACCCT,Unknown,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,-0.224693,-0.401662,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAAAAACTCAACAGCAGTGA,NRAS,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Inspect Beagle Files

### Check for column inconsistencies

In [6]:
print("MC Beagle Columns:" , mc_beagle.columns.to_list())
print("GR Beagle Columns:" , gr_beagle.columns.to_list())
print("EG Beagle Columns:" , eg_beagle.columns.to_list())
print("RH BCL2L1_MCL1 Beagle Columns:" , rh_bcl2l1_mcl1_beagle.columns.to_list())
print("RH BRCA1_BRCA2 Beagle Columns:" , rh_brca1_brca2_beagle.columns.to_list())
print("RH PARP1 Beagle Columns:" , rh_parp1_beagle.columns.to_list())

MC Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']
GR Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']
EG Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']
RH BCL2L1_MCL1 Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']
RH BRCA1_BRCA2 Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']
RH PARP1 Beagle Columns: ['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']

In [7]:
column_dict = {
    "MC": mc_beagle.columns,
    "GR": gr_beagle.columns,
    "EG": eg_beagle.columns,
    "RH_BCL2L1_MCL1": rh_bcl2l1_mcl1_beagle.columns,
    "RH_BRCA1_BRCA2": rh_brca1_brca2_beagle.columns,
    "RH_PARPI": rh_parp1_beagle.columns
}

# MC as reference dataset 
reference = column_dict["MC"]

# Check differences
for name, cols in column_dict.items():
    if not reference.equals(cols):
        print(f"\n{name} has different columns from MC")
        print(" Extra columns:", set(cols) - set(reference))
        print(" Missing columns:", set(reference) - set(cols))
    else:
        print(f"\n{name} columns match MC")

MC columns match MC

GR columns match MC

EG columns match MC

RH_BCL2L1_MCL1 columns match MC

RH_BRCA1_BRCA2 columns match MC

RH_PARPI columns match MC

In [8]:
pd.set_option('display.max_columns', None)  # Show all columns
eg_beagle.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
0,ENST00000275493.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,ENST00000275493.7,CDS,CGCATCGCTGCTCCCCGAAG,GGGTCGCATCGCTGCTCCCCGAAGAGCTCG,AG,55019263,antisense,55019279T>C,A_4,2T>C,Met1Thr,Missense,NaN,NaN
1,ENST00000275493.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,ENST00000275493.7,CDS,CGCATCGCTGCTCCCCGAAG,GGGTCGCATCGCTGCTCCCCGAAGAGCTCG,AG,55019263,antisense,"55019275G>A, 55019277G>A","C_8, C_6","-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN
2,ENST00000275493.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,ENST00000275493.7,CDS,GTCGCATCGCTGCTCCCCGA,GAGGGTCGCATCGCTGCTCCCCGAAGAGCT,AG,55019265,antisense,55019279T>C,A_6,2T>C,Met1Thr,Missense,NaN,NaN
3,ENST00000275493.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,ENST00000275493.7,CDS,GTCGCATCGCTGCTCCCCGA,GAGGGTCGCATCGCTGCTCCCCGAAGAGCT,AG,55019265,antisense,"55019277G>A, 55019280G>A","C_8, C_5","-1G>A, 3G>A","(NC), Met1Ile","UTR, Missense",NaN,NaN
4,ENST00000275493.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,ENST00000275493.7,CDS,AGGGTCGCATCGCTGCTCCC,CCGGAGGGTCGCATCGCTGCTCCCCGAAGA,CG,55019268,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [280]:
mc_beagle['Target Gene Symbol'].value_counts()

Target Gene Symbol
EGFR      4500
PARP1     3602
PIK3CA    2434
BRAF      2324
AKT1      2222
MAP2K2    1928
PARP2     1792
MYC       1520
MAP2K1    1434
BCL2      1010
KRAS       432
Name: count, dtype: int64

In [281]:
gr_beagle['Target Gene Symbol'].value_counts()

Target Gene Symbol
MDM2     13004
CHEK1    10802
WEE1      5634
PPM1D     4892
PLK1      2858
KRAS      2820
PMVK       746
NRAS       542
Name: count, dtype: int64

In [282]:
rh_beagle['Target Gene Symbol'].value_counts()

Target Gene Symbol
BRCA2     559
PARP1     543
BRCA1     495
MCL1      201
BCL2L1    120
Name: count, dtype: int64

In [283]:
eg_beagle['Target Gene Symbol'].value_counts()

Target Gene Symbol
MTOR      8326
NF1       6810
ERBB2     4942
ERBB3     4576
IGF1R     4556
PIK3CD    4178
ITGA3     4160
EGFR      4074
RICTOR    3808
FGFR2     2526
PIK3CB    2376
SHC1      2352
PIK3CA    2288
BRAF      2002
AKT1      1924
RAF1      1912
PKM       1904
GAB1      1738
MAP2K2    1692
PGD       1598
MYC       1486
MAPK3     1468
MAP2K1    1278
MAPK1     1026
PTEN       896
HRAS       706
GRB2       666
PHLDA2     652
NRAS       492
KRAS       396
Name: count, dtype: int64

### Merge Beagle Files

#### Merge the 3 RH files

In [9]:
rh_beagle = pd.concat([rh_bcl2l1_mcl1_beagle, rh_brca1_brca2_beagle, rh_parp1_beagle], ignore_index=True)

In [267]:
#rh_beagle.to_csv("data/1_Beagle_design_files/RH/RH-guides.txt", sep="\t", index=False)

In [10]:
rh_beagle.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
0,ENST00000307677,SpyoCas9,C-T,4..8,9606,GRCh38,NC_000020.11,ENSG00000171552,BCL2L1,-,ENST00000307677.5,CDS,TGCTGGGCTCACTCTTCAGT,GTTCTGCTGGGCTCACTCTTCAGTCGGAAA,CGG,31665958,sense,31665970G>A,C_8,681C>T,Gly227Gly,Silent,NaN,NaN
1,ENST00000307677,SpyoCas9,C-T,4..8,9606,GRCh38,NC_000020.11,ENSG00000171552,BCL2L1,-,ENST00000307677.5,CDS,TGAGCCCAGCAGAACCACGC,AGAGTGAGCCCAGCAGAACCACGCCGGCCA,CGG,31665967,antisense,"31665973C>T, 31665972C>T;31665971C>T","C_7, C_6;C_5","678G>A, 679G>A;680G>A","Leu226Leu, Gly227Asn","Silent, Missense",NaN,NaN
2,ENST00000307677,SpyoCas9,C-T,4..8,9606,GRCh38,NC_000020.11,ENSG00000171552,BCL2L1,-,ENST00000307677.5,CDS,GTGGCCGGCGTGGTTCTGCT,GACTGTGGCCGGCGTGGTTCTGCTGGGCTC,GGG,31665974,sense,31665989G>A;31665988G>A,C_5;C_6,662C>T;663C>T,Ala221Val,Missense,NaN,NaN
3,ENST00000307677,SpyoCas9,C-T,4..8,9606,GRCh38,NC_000020.11,ENSG00000171552,BCL2L1,-,ENST00000307677.5,CDS,TGTGGCCGGCGTGGTTCTGC,TGACTGTGGCCGGCGTGGTTCTGCTGGGCT,TGG,31665975,sense,31665989G>A;31665988G>A,C_6;C_7,662C>T;663C>T,Ala221Val,Missense,NaN,NaN
4,ENST00000307677,SpyoCas9,C-T,4..8,9606,GRCh38,NC_000020.11,ENSG00000171552,BCL2L1,-,ENST00000307677.5,CDS,GGGCATGACTGTGGCCGGCG,TGACGGGCATGACTGTGGCCGGCGTGGTTC,TGG,31665984,sense,31666000G>A,C_4,651C>T,Gly217Gly,Silent,NaN,NaN

#### Standardize GR columns to match the others

NOTE: If loading the standardized GR Beagle dataset, do not run this section

In [11]:
gr_beagle.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
0,ENST00000450114.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000011.10,ENSG00000166483,WEE1,+,ENST00000450114.7,CDS,CATCGCGGCCCTGGGGACGG,AGCTCATCGCGGCCCTGGGGACGGGGCCGA,GG,9573917,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ENST00000450114.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000011.10,ENSG00000166483,WEE1,+,ENST00000450114.7,CDS,CATCGCGGCCCTGGGGACGG,AGCTCATCGCGGCCCTGGGGACGGGGCCGA,GG,9573917,antisense,"9573931G>A, 9573933G>A","C_6, C_4","-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN
2,ENST00000450114.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000011.10,ENSG00000166483,WEE1,+,ENST00000450114.7,CDS,TCATCGCGGCCCTGGGGACG,AAGCTCATCGCGGCCCTGGGGACGGGGCCG,GG,9573918,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENST00000450114.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000011.10,ENSG00000166483,WEE1,+,ENST00000450114.7,CDS,TCATCGCGGCCCTGGGGACG,AAGCTCATCGCGGCCCTGGGGACGGGGCCG,GG,9573918,antisense,"9573931G>A, 9573933G>A","C_7, C_5","-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN
4,ENST00000450114.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000011.10,ENSG00000166483,WEE1,+,ENST00000450114.7,CDS,CTCATCGCGGCCCTGGGGAC,GAAGCTCATCGCGGCCCTGGGGACGGGGCC,GG,9573919,antisense,9573935T>C,A_4,2T>C,Met1Thr,Missense,NaN,NaN

In [258]:
# Separate 'Target Assembly' and 'Target Taxon' columns
gr_beagle[['Target Assembly', 'Target Taxon']] = gr_beagle['Target Assembly'].str.extract(r'(\w+)\s*\((\d+)\)')

#Rename columns names
gr_beagle.rename(columns={
    'sgRNA Target Sequence': 'sgRNA Sequence',
    'sgRNA Target Sequence Start Pos. (global)': 'sgRNA Sequence Start Pos. (global)' 
    }, inplace=True)

# Correct colmn positions
gr_beagle = gr_beagle[['Input', 'CRISPR Enzyme', 'Edit Type', 'Edit Window', 'Target Taxon', 'Target Assembly', 'Target Genome Sequence', 'Target Gene ID', 'Target Gene Symbol', 'Target Gene Strand', 'Target Transcript ID', 'Target Domain', 'sgRNA Sequence', 'sgRNA Context Sequence', 'PAM Sequence', 'sgRNA Sequence Start Pos. (global)', 'sgRNA Orientation', 'Nucleotide Edits (global)', 'Guide Edits', 'Nucleotide Edits', 'Amino Acid Edits', 'Mutation Category', 'Constraint Violations', 'Note']]

In [269]:
gr_beagle.to_csv("data/1_Beagle_design_files/GR/GR-guides-standardized.txt", sep="\t", index=False)

#### Add a column to track the source study

In [12]:
mc_beagle["Source Study"] = "MC"
gr_beagle["Source Study"] = "GR"
eg_beagle["Source Study"] = "EG"
rh_beagle["Source Study"] = "RH"

#### Merge the 4 datasets

In [13]:
complete_beagle = pd.concat([mc_beagle, gr_beagle, eg_beagle, rh_beagle], ignore_index=True)

In [276]:
print("Total guides:", len(complete_beagle))

Total guides: 143222

In [14]:
complete_beagle.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note,Source Study
0,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,ENST00000644969.2,CDS,GCCACCATCATGGCAGCATC,AGTAGCCACCATCATGGCAGCATCTGCTCT,TG,140726475,sense,"140726491T>C, 140726488T>C","A_4, A_7","*3A>G, *6A>G","(NC), (NC)","UTR, UTR",NaN,NaN,MC
1,ENST00000644969,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,ENST00000644969.2,CDS,GCCACCATCATGGCAGCATC,AGTAGCCACCATCATGGCAGCATCTGCTCT,TG,140726475,sense,"140726490G>A, 140726489G>A","C_5, C_6","*4C>T, *5C>T","(NC), (NC)","UTR, UTR",NaN,NaN,MC
2,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,ENST00000644969.2,CDS,CTGCCATGATGGTGGCTACT,GATGCTGCCATGATGGTGGCTACTTGAAGG,TG,140726479,antisense,140726484A>G,A_6,*10T>C,(NC),UTR,NaN,NaN,MC
3,ENST00000644969,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,ENST00000644969.2,CDS,CTGCCATGATGGTGGCTACT,GATGCTGCCATGATGGTGGCTACTTGAAGG,TG,140726479,antisense,"140726483C>T, 140726482C>T","C_5, C_4","*11G>A, *12G>A","(NC), (NC)","UTR, UTR",NaN,NaN,MC
4,ENST00000644969,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,ENST00000644969.2,CDS,CAAGTAGCCACCATCATGGC,CCTTCAAGTAGCCACCATCATGGCAGCATC,AG,140726481,sense,140726495T>C,A_6,2423A>G,Ter808Trp,Missense,NaN,NaN,MC

### Inspect the complete Beagle file

In [ ]:
complete_beagle['Target Gene Symbol'].value_counts()

##### Check if the combination guide+editor is unique

In [16]:
unique_guide_editor_beagle = complete_beagle[['sgRNA Sequence', 'Edit Type']].drop_duplicates()

In [17]:
#Duplicates without the first occurence - just extra ones
duplicates_guide_editor_exclude_first_beagle = complete_beagle[complete_beagle.duplicated(subset=["sgRNA Sequence", "Edit Type"], keep=False)]

In [18]:
print(f"Total combinations: {len(complete_beagle)}")
print(f"Unique guide+editor combinations: {len(complete_beagle) - len(duplicates_guide_editor_exclude_first_beagle)}")
print(f"Total duplicated guide+editor: {len(duplicates_guide_editor_exclude_first_beagle)}")

Total combinations: 143222
Unique guide+editor combinations: 74424
Total duplicated guide+editor: 68798

In [19]:
duplicates_guide_editor_exclude_first_beagle['Target Gene Symbol'].value_counts()

Target Gene Symbol
MDM2      12882
CHEK1     10440
EGFR       8148
PPM1D      4852
WEE1       4588
PIK3CA     4576
BRAF       3980
AKT1       3848
KRAS       3530
MAP2K2     3384
MYC        2972
MAP2K1     2556
PARP1      1086
NRAS        984
PLK1        962
ERBB3        10
Name: count, dtype: int64

In [20]:
df = duplicates_guide_editor_exclude_first_beagle[duplicates_guide_editor_exclude_first_beagle['Target Gene Symbol']=="MDM2"]

In [22]:
df=df.sort_values(by=['sgRNA Sequence', 'Edit Type'])
df.head()

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note,Source Study
29976,ENST00000258149.11,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000258149.11,CDS,AAAAATGGTTGCATTGTCCA,ACCTAAAAATGGTTGCATTGTCCATGGCAA,TG,68839709,sense,68839712A>G;68839713A>G,A_4_5,1357A>G;1358A>G,Asn453Gly,Missense,NaN,NaN,GR
31190,ENST00000539479.6,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000539479.6,CDS,AAAAATGGTTGCATTGTCCA,ACCTAAAAATGGTTGCATTGTCCATGGCAA,TG,68839709,sense,68839712A>G;68839713A>G,A_4_5,1339A>G;1340A>G,Asn447Gly,Missense,NaN,NaN,GR
32500,ENST00000393416.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393416.7,CDS,AAAAATGGTTGCATTGTCCA,ACCTAAAAATGGTTGCATTGTCCATGGCAA,TG,68839709,sense,68839712A>G;68839713A>G,A_4_5,1432A>G;1433A>G,Asn478Gly,Missense,NaN,NaN,GR
33642,ENST00000544561.6,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000544561.6,CDS,AAAAATGGTTGCATTGTCCA,ACCTAAAAATGGTTGCATTGTCCATGGCAA,TG,68839709,sense,68839712A>G;68839713A>G,A_4_5,1231A>G;1232A>G,Asn411Gly,Missense,NaN,NaN,GR
34244,ENST00000393412.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393412.7,CDS,AAAAATGGTTGCATTGTCCA,ACCTAAAAATGGTTGCATTGTCCATGGCAA,TG,68839709,sense,68839712A>G;68839713A>G,A_4_5,595A>G;596A>G,Asn199Gly,Missense,NaN,NaN,GR

In [23]:
df['Source Study'].value_counts()

Source Study
GR    12882
Name: count, dtype: int64

In [24]:
df['sgRNA Sequence'].value_counts()

sgRNA Sequence
AACATGTCTGTACCTACTGA    36
TCTGTACCTACTGATGGTGC    36
TGGTTAGTATTTTTGTCTCG    36
ACATGTCTGTACCTACTGAT    36
AGGGTCTCTTGTTCCGAAGC    36
ACAGCACCATCAGTAGGTAC    36
TCCGAAGCTGGAATCTGTGA    36
AGGTACAGACATGTTGGTAT    36
GGAATCTGTGAGGTGGTTAC    36
GCTTCGGAACAAGAGACCCT    36
CTTGTTCCGAAGCTGGAATC    36
ACATGTTGGTATTGCACATT    36
ATCAGTAGGTACAGACATGT    36
TGTTCCGAAGCTGGAATCTG    36
GATTCCAGCTTCGGAACAAG    36
GAGGTGGTTACAGCACCATC    36
GAAGCTGGAATCTGTGAGGT    36
GAGACCCTGGTTAGTATTTT    36
TGGTGCTGTAACCACCTCAC    36
ATGTCTGTACCTACTGATGG    36
TTCCGAAGCTGGAATCTGTG    36
TGGTTACAGCACCATCAGTA    36
ACCAACATGTCTGTACCTAC    36
CTAACCAGGGTCTCTTGTTC    36
GTGGTTACAGCACCATCAGT    36
GTAACCACCTCACAGATTCC    36
CCTGGTTAGTATTTTTGTCT    36
CGAAGCTGGAATCTGTGAGG    36
ACCAGGGTCTCTTGTTCCGA    36
CGGAACAAGAGACCCTGGTT    36
GGGTCTCTTGTTCCGAAGCT    36
ACCTCACAGATTCCAGCTTC    36
AGCTTCGGAACAAGAGACCC    36
TCAGTAGGTACAGACATGTT    36
CAGATTCCAGCTTCGGAACA    36
ACCATCAGTAGGTACAGACA    36
CACCTCACAGATTCCAGCTT    36
CATTGAAGGACTATTGGAAA    34
CATTTCCAATAGTCCTTCAA    34
TGGAAATGCACTTCATGCAA    34
AATAGTCCTTCAATGAAATA    34
ACTATTGGAAATGCACTTCA    34
GCATGAAGTGCATTTCCAAT    32
TATTGCACATTTGCCTACAA    32
GCAAATGTGCAATACCAACA    32
GGATTCATTTCATTGCATGA    32
GTATTGCACATTTGCCTACA    32
ATGCACTTCATGCAATGAAA    32
ATGTGCAATACCAACATGTC    32
ATTCATTTCATTGCATGAAG    32
GGGGGATTCATTTCATTGCA    30
AAGGGGGGGATTCATTTCAT    28
ATCCCCCCCTTCCATCACAT    28
ATGTAGACAACCAATTCAAA    26
GGCCATAAGATGTCCTGTTT    26
CAGGTCAACTAGGGGAAATA    26
GGCCTGCTTTACATGTGCAA    26
CTGCTTTACATGTGCAAAGA    26
GGCAAAACAGGACATCTTAT    26
CGACCTTGACAAATCACACA    26
CTTAATGCCATTGAACCTTG    26
CACATGTAAAGCAGGCCATA    26
AGGGAAGAAACCCAAGACAA    26
CACACTCTCTTCTTTGTCTT    26
CTAGTTGACCTGTCTATAAG    26
GGTTGTCTACATACTGGGCA    26
CGACCTAAAAATGGTTGCAT    26
CACAAGGTTCAATGGCATTA    26
CCCTTAATGCCATTGAACCT    26
CCATTGAACCTTGTGTGATT    26
GTCAAGGTCGACCTAAAAAT    26
AGATTCCACACTCTCTTCTT    26
CCAAGACAAAGAAGAGAGTG    26
GTGAAAGAGTTTGAAAGGGA    26
GTGCAAAGAAGCTAAAGAAA    26
CCACACTCTCTTCTTTGTCT    26
GTTAGCACAATCATTTGAAT    26
AGAGAGTGTGGAATCTAGTT    26
AGGGCTTATTCCTTTTCTTT    26
CAAGGTTCAATGGCATTAAG    26
CAATGCAACCATTTTTAGGT    26
CTTGTGTGATTTGTCAAGGT    26
ATGTAAAGCAGGCCATAAGA    26
ATGGCATTAAGGGGCAAACT    26
GTTGTCTACATACTGGGCAG    26
GAATTGGTTGTCTACATACT    26
GACCTTGACAAATCACACAA    26
GAATCTAGTTTGCCCCTTAA    26
GAAGCTAAAGAAAAGGAATA    26
ATCTTATGGCCTGCTTTACA    26
GAAGAAACCCAAGACAAAGA    26
GAACCTTGTGTGATTTGTCA    26
GCACAATCATTTGAATTGGT    26
GCATTGTCCATGGCAAAACA    26
CTTATGGCCTGCTTTACATG    26
GCTAACTTATTTCCCCTAGT    26
CTTCTTTGCACATGTAAAGC    26
ATAAGCCCTGCCCAGTATGT    26
AGTTTGCCCCTTAATGCCAT    26
CAAACTCTTTCACATCTTCT    26
GGAATAAGCCCTGCCCAGTA    26
CAAATCACACAAGGTTCAAT    26
GGACAATGCAACCATTTTTA    26
AAAAGGAATAAGCCCTGCCC    26
CAAGACAAAGAAGAGAGTGT    26
CTTATTTCCCCTAGTTGACC    26
AGACAACCAATTCAAATGAT    26
AAAAATGGTTGCATTGTCCA    26
TAAAGAAAAGGAATAAGCCC    26
TCCTGTTTTGCCATGGACAA    26
ACAACCAATTCAAATGATTG    26
ACAAATCACACAAGGTTCAA    26
AATTGGTTGTCTACATACTG    26
TGAATTGGTTGTCTACATAC    26
TGCAAAGAAGCTAAAGAAAA    26
TGCATTGTCCATGGCAAAAC    26
TGGACAATGCAACCATTTTT    26
AATAAGTTAGCACAATCATT    26
TGGCAAAACAGGACATCTTA    26
AAGGTTCAATGGCATTAAGG    26
AAGGTCGACCTAAAAATGGT    26
TGTCAAGGTCGACCTAAAAA    26
TGTGCTAACTTATTTCCCCT    26
AAGCAGGCCATAAGATGTCC    26
AAGATGTCCTGTTTTGCCAT    26
TTAGCACAATCATTTGAATT    26
AAGAAGAGAGTGTGGAATCT    26
AACCTTGTGTGATTTGTCAA    26
AACCATTTTTAGGTCGACCT    26
TTCCTTTTCTTTAGCTTCTT    26
TTCTTTAGCTTCTTTGCACA    26
TTCTTTGCACATGTAAAGCA    26
AAACTCTTTCACATCTTCTT    26
AAACCCAAGACAAAGAAGAG    26
TTTGAAAGGGAAGAAACCCA    26
AAACAGGACATCTTATGGCC    26
AAAATGGTTGCATTGTCCAT    26
ACAAGGTTCAATGGCATTAA    26
TGGTTGTCTACATACTGGGC    26
CCCTAGTTGACCTGTCTATA    26
TAAGATGTCCTGTTTTGCCA    26
TACATGTGCAAAGAAGCTAA    26
TCAACTAGGGGAAATAAGTT    26
TAATGCCATTGAACCTTGTG    26
ACCCAAGACAAAGAAGAGAG    26
TAGCTTCTTTGCACATGTAA    26
ACACTCTCTTCTTTGTCTTG    26
AGAAACCCAAGACAAAGAAG    26
TAAATAATGCTACTAGAAGT    24
TTCCATCACATTGCAACAGA    24
CTGTTGCAATGTGATGGAAG    24
CTTACCTCTTTCATAGTATA    24
TTTTAGGATCTTGATGCTGG    24
TAATGCTACTAGAAGTTGAT    24
TTCTTGGCTGCTATAAATAA    24
CTTATACTATGAAAGAGGTA    24
TTCCTCAACACATGACTCTC    24
TACCTCTTTCATAGTATAAG    24
CCCTTCCATCACATTGCAAC    24
TTCCAGTTTGGCTTTCTCAG    24
GTCTAACCTATAAAGAGAAA    24
TTCCAGAGAGTCATGTGTTG    24
CTTCAGGAAGCCAATTCTCA    24
TTATCTTTCCCTTTATCTTC    24
CTTCGTGAGAATTGGCTTCC    24
TTATAGCAGCCAAGAAGATG    24
CTTCTAGTAGCATTATTTAT    24
TAGACCAAAGCCATTGCTTT    24
CTGGTGTAAGTGAACATTCA    24
CTGGAAAACTCAACACAAGC    24
TTGAAGTTATTAAAGTCTGT    24
TTGCAATGTGATGGAAGGGG    24
CCTGATTGTAAAAAAACTAT    24
TTTCTTGTGATTGTGAAGCT    24
TTTACAATCAGGAACATCAA    24
TTTAATAACTTCAAAAGCAA    24
GTGTCTTTTTGTGCACCAAC    24
TTGTTTTAGGATCTTGATGC    24
CGTGAGAATTGGCTTCCTGA    24
TTGTGTTGAGTTTTCCAGTT    24
CTACTAGAAGTTGATGGCTG    24
CTAGTAGCATTATTTATAGC    24
TTGGGCCCTTCGTGAGAATT    24
TTGGCTTCCTGAAGATAAAG    24
CTATAAATAATGCTACTAGA    24
CTATAGTTTTTTTACAATCA    24
CTCACGAAGGGCCCAACATC    24
CTCAGCCATCAACTTCTAGT    24
CTCTTTCACATCTTCTTGGC    24
TTAATAACTTCAAAAGCAAT    24
GTTGCAATGTGATGGAAGGG    24
CTGCTATAAATAATGCTACT    24
TCCTCAACACATGACTCTCT    24
TGTTTTAGGATCTTGATGCT    24
TCACTTTCTTGTGATTGTGA    24
GATAAAGGGAAAGATAAAGG    24
GATCTTGATGCTGGTGTAAG    24
GATGTGAAAGAGTTTGAAAG    24
GATTCCAGAGAGTCATGTGT    24
TGATTGTAAAAAAACTATAG    24
TCATAGTATAAGTGTCTTTT    24
TGAATGATTCCAGAGAGTCA    24
TGAAGTTATTAAAGTCTGTT    24
GCAACAGATGTTGGGCCCTT    24
TCTTGTGATTGTGAAGCTTG    24
TCTTCACTTTCTTGTGATTG    24
TCATCATTTTCCTCAACACA    24
GCCCAACATCTGTTGCAATG    24
GCCCTCTTCAGCTTGTGTTG    24
TCTGTTGCAATGTGATGGAA    24
TCATGTGTTGAGGAAAATGA    24
TCCAGAGAGTCATGTGTTGA    24
GCTGGTGTAAGTGAACATTC    24
GCTTCACAATCACAAGAAAG    24
GGAACATCAAAGCCCTCTTC    24
GGAAGCCAATTCTCACGAAG    24
GAGTCATGTGTTGAGGAAAA    24
TGCAATGTGATGGAAGGGGG    24
TCTCTGGAATCATTCACTAT    24
GAGAATAGTCTTCACTTTCT    24
CTTTGGTCTAACCTATAAAG    24
CTTTTGAAGTTATTAAAGTC    24
GAAAACTCAACACAAGCTGA    24
GAAAGAGGTAAGCTGAATCA    24
TGTTGCAATGTGATGGAAGG    24
TATAGTGAATGATTCCAGAG    24
GAAGAGGGCTTTGATGTTCC    24
TATCTTTCCCTTTATCTTCA    24
GAAGATAAAGGGAAAGATAA    24
TGTGTTGAGTTTTCCAGTTT    24
GGTGTAAGTGAACATTCAGG    24
GAATAGTCTTCACTTTCTTG    24
TCAAAGCCCTCTTCAGCTTG    24
TGTAAAAAAACTATAGTGAA    24
GTTGGGCCCTTCGTGAGAAT    24
GGGCCCAACATCTGTTGCAA    24
TCACAATCACAAGAAAGTGA    24
GACACTTATACTATGAAAGA    24
GGCTTTGGTCTAACCTATAA    24
TCACATTGCAACAGATGTTG    24
TGCTACTAGAAGTTGATGGC    24
CTTTCCCTTTATCTTCAGGA    24
CTTCCTGAAGATAAAGGGAA    24
TTTTCCAGTTTGGCTTTCTC    24
ATTGGCTTCCTGAAGATAAA    24
ATCTGTTGCAATGTGATGGA    24
ACCAAAGCCATTGCTTTTGA    24
ACACAAGCTTCACAATCACA    24
ACACAAGCTGAAGAGGGCTT    24
ACAAAAAGACACTTATACTA    24
ATTATTTATAGCAGCCAAGA    24
AATTGGCTTCCTGAAGATAA    24
ATTCTCAGCCATCAACTTCT    24
ATTGCTTTTGAAGTTATTAA    24
AATGATTCCAGAGAGTCATG    24
ATCACATTGCAACAGATGTT    24
ATTTATAGCAGCCAAGAAGA    24
AATGATGATAAAATTACACA    24
AATCTCTGAGAAAGCCAAAC    24
AAGTTATTAAAGTCTGTTGG    24
CAACATCTGTTGCAATGTGA    24
CAAGAAGATGTGAAAGAGTT    24
CAAGCTGAAGAGGGCTTTGA    24
CAGACTTTAATAACTTCAAA    24
AAGTCTGTTGGTGCACAAAA    24
ATCTCTGAGAAAGCCAAACT    24
ACCTATAAAGAGAAAAGAAC    24
CAGCCAAGAAGATGTGAAAG    24
AGGAAGCCAATTCTCACGAA    24
AGATAAAGGGGAAATCTCTG    24
AGATGTGAAAGAGTTTGAAA    24
AGCAGCCAAGAAGATGTGAA    24
AGACACTTATACTATGAAAG    24
AGAAGTTGATGGCTGAGAAT    24
AGAAAGTGAAGACTATTCTC    24
ACTTCAAAAGCAATGGCTTT    24
AGCATCAAGATCCTAAAACA    24
AGCATTATTTATAGCAGCCA    24
AGGATCTTGATGCTGGTGTA    24
ATAGTATAAGTGTCTTTTTG    24
ACTCAACACAAGCTGAAGAG    24
AGGGCTTTGATGTTCCTGAT    24
ACTATAGTTTTTTTACAATC    24
ACTATAGTGAATGATTCCAG    24
AGTCTTCACTTTCTTGTGAT    24
ATAATGCTACTAGAAGTTGA    24
ATACTATGAAAGAGGTAAGC    24
ATAGGTTAGACCAAAGCCAT    24
ACGAAGGGCCCAACATCTGT    24
CAGATGTTGGGCCCTTCGTG    24
AGATAAAGGGAAAGATAAAG    24
AAAGGGGAAATCTCTGAGAA    24
CATCACATTGCAACAGATGT    24
CATCAAAGCCCTCTTCAGCT    24
AAGCCCTCTTCAGCTTGTGT    24
AAGATGTGAAAGAGTTTGAA    24
AAACTCAACACAAGCTGAAG    24
AAACTGGAAAACTCAACACA    24
AAGCTTCACAATCACAAGAA    24
AAACTATAGTGAATGATTCC    24
AACTCAACACAAGCTGAAGA    24
AACAGATGTTGGGCCCTTCG    24
AAAGACACTTATACTATGAA    24
AACTTCAAAAGCAATGGCTT    24
AAGATAAAGGGAAAGATAAA    24
AAAGATAAAGGGGAAATCTC    24
AAGAGGTAAGCTGAATCAAG    24
AACATCTGTTGCAATGTGAT    24
CAGCTTGTGTTGAGTTTTCC    24
CAGGAAGCCAATTCTCACGA    24
ATTCAGTTTCAGATCAGTTT    22
GAAGATTATAGCCTTAGTGA    22
ACTAAGGCTATAATCTTCTG    22
GAAGAAGGACAAGAACTCTC    22
GAAGGACAAGAACTCTCAGA    22
ACTACCTCATCATCTTCATC    22
GAACTCTCAGATGAAGATGA    22
ATTATAGCCTTAGTGAAGAA    22
TTCAGGTGATTGGTTGGATC    22
GAACATTCAGGTGATTGGTT    22
GAATTTGAAGTTGAATCTCT    22
TTCTTGTCCTTCTTCACTAA    22
GATTGGTTGGATCAGGATTC    22
TCACTAAGGCTATAATCTTC    22
GATTATAGCCTTAGTGAAGA    22
TCAGAAGATTATAGCCTTAG    22
TCCTGATCCAACCAATCACC    22
ACACTAAACTGATCTGAAAC    22
TCAGATGAAGATGATGAGGT    22
TCAGGATTCAGTTTCAGATC    22
CAGTTTAGTGTAGAATTTGA    22
TCAGGTGATTGGTTGGATCA    22
GATCCAACCAATCACCTGAA    22
TTGGATCAGGATTCAGTTTC    22
GAAGTTGAATCTCTCGACTC    22
TGAACATTCAGGTGATTGGT    22
AATTCTACACTAAACTGATC    22
GTTCACTTACACCAGCATCA    22
GTTCTTGTCCTTCTTCACTA    22
CTCTCGACTCAGAAGATTAT    22
GTTGAATCTCTCGACTCAGA    22
AAGGCTATAATCTTCTGAGT    22
CATCTTCATCTGAGAGTTCT    22
GTTTCAGATCAGTTTAGTGT    22
TTTAGTGTAGAATTTGAAGT    22
CCTCATCATCTTCATCTGAG    22
CTCTCAGATGAAGATGATGA    22
ACTGATCTGAAACTGAATCC    22
AAGTGAACATTCAGGTGATT    22
CCTGAATGTTCACTTACACC    22
CTTCAAATTCTACACTAAAC    22
AGCCTTAGTGAAGAAGGACA    22
TCAGTTTCAGATCAGTTTAG    22
CTATAATCTTCTGAGTCGAG    22
CAAGAACTCTCAGATGAAGA    22
TAAGTGAACATTCAGGTGAT    22
ACTCTCAGATGAAGATGATG    22
ACTCAGAAGATTATAGCCTT    22
GGCTATAATCTTCTGAGTCG    22
TACCTCATCATCTTCATCTG    22
GATCAGTTTAGTGTAGAATT    22
GGACAAGAACTCTCAGATGA    22
GTTACTGTGTATCAGGCAGG    20
GATCCTGAAATTTCCTTAGC    20
AGTGATACAGATTCATTTGA    20
TATTAGGTATATCAAGTTAC    20
AGTTACTGTGTATCAGGCAG    20
TATCAAGTTACTGTGTATCA    20
ATATCAAGTTACTGTGTATC    20
GGATCTTCTTCAAATGAATC    20
GATTCATTTGAAGAAGATCC    20
TACTGTGTATCAGGCAGGGG    20
CTGAAATTTCCTTAGCTGTA    20
CTGTATCACTCTCCCCTGCC    20
CAAGTTACTGTGTATCAGGC    20
CTGTGTATCAGGCAGGGGAG    20
TTAGGTATATCAAGTTACTG    20
GTGTATCAGGCAGGGGAGAG    20
GAATCTGTATCACTCTCCCC    20
TTACAGCTAAGGAAATTTCA    20
CTCTCCCCTGCCTGATACAC    20
CTTACAGCTAAGGAAATTTC    20
AAGTTACTGTGTATCAGGCA    20
GAAGATCCTGAAATTTCCTT    20
GATACAGATTCATTTGAAGA    20
CTGCCTGATACACAGTAACT    20
ATTTCAGGATCTTCTTCAAA    20
GAGAGTGATACAGATTCATT    20
CAGGCAGGGGAGAGTGATAC    20
TGGTAGTAGTCAATCAGCAG    16
AATATATACCATGATCTACA    16
AGTAGTCAATCAGCAGGGTA    16
ATTGACTACTACCAAGTTCC    16
TACCATGATCTACAGGAACT    16
TTGGTAGTAGTCAATCAGCA    16
GAACTTGGTAGTAGTCAATC    16
TACCAAGTTCCTGTAGATCA    16
CTTGGTAGTAGTCAATCAGC    16
TATATATTTTCCTTGTAGAC    16
TACAAGGAAAATATATACCA    16
CTGCTGATTGACTACTACCA    16
ACCAAGTTCCTGTAGATCAT    16
AAATATATACCATGATCTAC    16
TCAGCAGGGTAAGTTAATTT    16
ATGGTATATATTTTCCTTGT    16
ATGATCTACAGGAACTTGGT    16
ATCATGGTATATATTTTCCT    16
AGCAGGGTAAGTTAATTTTG    16
ACCATGATCTACAGGAACTT    16
ATCTACAGGAACTTGGTAGT    16
GACTACTACCAAGTTCCTGT    16
TGCTTAGGACCTTGTACAAG    14
AAAATTCAGATGAATTATCT    14
AGAGCCAGGCTTTCATCAAA    14
TGGCGTCCCTGTAGATTCAC    14
AAGGAAAGGGAAATACTATC    14
TGTGTGTAATAAGGGAGATA    14
AAACCAAATGTGAAGATGAA    14
GTTTCTCTTCCTGAAGCTCT    14
AAACCTTCATCTTCACATTT    14
TAAGGGAGATATGTTGTGAA    14
TGTACAAGAGCTTCAGGAAG    14
TTTCCCTTTCCTTTGATGAA    14
AAGGGAAATACTATCAGATT    14
GTTGTGAAAGAAGCAGTAGC    14
TGTGAAAGAAGCAGTAGCAG    14
AATTCATCTGAATTTTCTTC    14
TACAAGGTCCTAAGCATTTA    14
AATTTTCTTCTGGATATGTA    14
TTCCTGAAGCTCTTGTACAA    14
ACAGGGACGCCATCGAATCC    14
AACATTACCGGATTCGATGG    14
TCCTTCTAGATGAGGTAGAT    14
TCACTAATTGCTCTCCTTCT    14
TCTACCTCATCTAGAAGGAG    14
ACCGGATTCGATGGCGTCCC    14
TCTAGAAGGAGAGCAATTAG    14
TCTGAATTTTCTTCTGGATA    14
TATGTTGTGAAAGAAGCAGT    14
TATCCAGAAGAAAATTCAGA    14
TTGATGAAAGCCTGGCTCTG    14
TACAGGGACGCCATCGAATC    14
AAATACTATCAGATTTGTGG    14
TATATACCTGTCTCACTAAT    14
AATTGCTCTCCTTCTAGATG    14
TAGCAGTGAATCTACAGGGA    14
TAGATGGTCTAGAAACCAAA    14
TGAATCTACAGGGACGCCAT    14
TAGAAGGAGAGCAATTAGTG    14
AATTCAGATGAATTATCTGG    14
AATTATCTGGTGAACGACAA    14
AATGCTTAGGACCTTGTACA    14
AAGATGAAGGTTTCTCTTCC    14
ACCATCTACCTCATCTAGAA    14
GGTCTAGAAACCAAATGTGA    14
GTGTAATAAGGGAGATATGT    14
CAGTAGCAGTGAATCTACAG    14
GACGCCATCGAATCCGGTAA    14
CTCCTTCTAGATGAGGTAGA    14
ATGAAGGTTTCTCTTCCTGA    14
CAGGCTTTCATCAAAGGAAA    14
GATAGTATTTCCCTTTCCTT    14
ATCTCCCTTATTACACACAG    14
GATGAAAGCCTGGCTCTGTG    14
GATGGTCTAGAAACCAAATG    14
CAGATTTGTGGCGTTTTCTT    14
CTAGATGAGGTAGATGGTCT    14
CTAGACCATCTACCTCATCT    14
CTAGAAACCAAATGTGAAGA    14
ATATCTCCCTTATTACACAC    14
CGTTTTCTTTGTCGTTCACC    14
GCAGTAGCAGTGAATCTACA    14
GCCTGGCTCTGTGTGTAATA    14
GACCTTGTACAAGAGCTTCA    14
CTGGCTCTGTGTGTAATAAG    14
CGTTCACCAGATAATTCATC    14
GAAAATTCAGATGAATTATC    14
CTTGTACAAGAGCTTCAGGA    14
CAAAGAAAACGCCACAAATC    14
ATTTGTGGCGTTTTCTTTGT    14
CTTTCCTTTGATGAAAGCCT    14
CTTTGATGAAAGCCTGGCTC    14
CTTCCTGAAGCTCTTGTACA    14
GAAAACGCCACAAATCTGAT    14
GAAACCAAATGTGAAGATGA    14
GACCATCTACCTCATCTAGA    14
GAAACCTTCATCTTCACATT    14
ATTGCTCTCCTTCTAGATGA    14
CAGAGCCAGGCTTTCATCAA    14
ATTCATCTGAATTTTCTTCT    14
CAGATGAATTATCTGGTGAA    14
CTGGTGAACGACAAAGAAAA    14
ATTAGTGAGACAGGTATATA    14
GCTCTCCTTCTAGATGAGGT    14
CTAATTGCTCTCCTTCTAGA    14
ATTTTCTTCTGGATATGTAA    14
GGAGAGCAATTAGTGAGACA    14
GGGAAATACTATCAGATTTG    14
GGGAGATATGTTGTGAAAGA    14
AGCTCTTGTACAAGGTCCTA    14
CCTGGCTCTGTGTGTAATAA    14
CATCTTCACATTTGGTTTCT    14
AGCAGTAGCAGTGAATCTAC    14
CCTTATTACACACAGAGCCA    14
AGGCTTTCATCAAAGGAAAG    14
CCGGTAATGTTCTCATTTTA    14
GGATTCGATGGCGTCCCTGT    14
GTAATAAGGGAGATATGTTG    14
GTACAAGGTCCTAAGCATTT    14
CCTTTCCTTTGATGAAAGCC    14
AGGAGAGCAATTAGTGAGAC    14
CATCTAGAAGGAGAGCAATT    14
CATCTACCTCATCTAGAAGG    14
GGACCTTGTACAAGAGCTTC    14
AGATATGTTGTGAAAGAAGC    14
CCAGGCTTTCATCAAAGGAA    14
CCCTGTAGATTCACTGCTAC    14
GGAAATACTATCAGATTTGT    14
GGCTCTGTGTGTAATAAGGG    14
AGTATTTCCCTTTCCTTTGA    14
CCCTTATTACACACAGAGCC    14
TTTCACAGAGAAGCTTGGCA    12
CATTTGAACAATATACAATA    12
CACCTGTTCTCACTCACAGA    12
CTTCTAGGAGATTTGTTTGG    12
CACAGGTAATTCTTCAGTTT    12
TTTGATCACTCCCACCTTCA    12
CATCTGTGAGTGAGAACAGG    12
TTTGGCGTGCCAAGCTTCTC    12
TTTCAGGTTCTTTTTTATCT    12
TGGCGTGCCAAGCTTCTCTG    12
AAATGATCTTCTAGGAGATT    12
TGTCACCTTGAAGGTGGGAG    12
TTCAGGTTCTTTTTTATCTT    12
TTGAACAATATACAATATGT    12
AACAATATACAATATGTTGT    12
TTCTCATCATATAATCGTTT    12
CGGACTCAGGTACATCTGTG    12
TTCTCACTCACAGATGTACC    12
CATATTGTATATTGTTCAAA    12
AACAGGTGTCACCTTGAAGG    12
TTGATCACTCCCACCTTCAA    12
CTTCTCTGTGAAAGAGCACA    12
CGCCAAACAAATCTCCTAGA    12
TTATCTTGGCCAGTATATTA    12
CTGAGTCCGATGATTCTGAG    12
AAGAACCTGAAATACAAATA    12
CAGGTGTCACCTTGAAGGTG    12
AAGAGCACAGGTAATTCTTC    12
TTACCTGTGCTCTTTCACAG    12
CTCACAGATGTACCTGAGTC    12
CTCACTCACAGATGTACCTG    12
TGTTCAAATGATCTTCTAGG    12
AAATCTCCTAGAAGATCATT    12
CCTGTGCTCTTTCACAGAGA    12
CTCTCAGAATCATCGGACTC    12
CTCAGGTACATCTGTGAGTG    12
ATTCTGAGAGAAAAGAAAAA    12
TGCTCTTTCACAGAGAAGCT    12
GCTTCTCTGTGAAAGAGCAC    12
ATCGGACTCAGGTACATCTG    12
AATTACCTGTGCTCTTTCAC    12
ACCTGAGTCCGATGATTCTG    12
TATTGTTCAAATGATCTTCT    12
GCACGCCAAACAAATCTCCT    12
GCCAAGCTTCTCTGTGAAAG    12
GCCAGTATATTATGACTAAA    12
GCTCTTTCACAGAGAAGCTT    12
AGTGATCAAAAGGTAATCTA    12
TATACTGGCCAAGATAAAAA    12
TAGTCATAATATACTGGCCA    12
AGTGAGAACAGGTGTCACCT    12
GATGAGAAGCAACAACATAT    12
TACATCTGTGAGTGAGAACA    12
GGCCAAGATAAAAAAGAACC    12
CCCACCTTCAAGGTGACACC    12
GGTGTCACCTTGAAGGTGGG    12
GGTTCTTTTTTATCTTGGCC    12
TAAACGATTATATGATGAGA    12
AGAACAGGTGTCACCTTGAA    12
GTACATCTGTGAGTGAGAAC    12
GTTGCTTCTCATCATATAAT    12
GTACCTGAGTCCGATGATTC    12
AGCAACAACATATTGTATAT    12
ATCGTTTAGTCATAATATAC    12
GATTCTGAGAGAAAAGAAAA    12
TCCGATGATTCTGAGAGAAA    12
ATTATGACTAAACGATTATA    12
TCTAGGAGATTTGTTTGGCG    12
TCGTTTAGTCATAATATACT    12
GACTAAACGATTATATGATG    12
GAAGGTGGGAGTGATCAAAA    12
GTGCCAAGCTTCTCTGTGAA    12
GATCTTCTAGGAGATTTGTT    12
TGAAGGTGGGAGTGATCAAA    12
GACTCAGGTACATCTGTGAG    12
GAGAACAGGTGTCACCTTGA    12
TGACACCTGTTCTCACTCAC    12
ATGACTAAACGATTATATGA    12
TCTCAGAATCATCGGACTCA    12
ACAGATGTACCTGAGTCCGA    12
ACAGGTGTCACCTTGAAGGT    12
TCATCGGACTCAGGTACATC    12
GAGATTTGTTTGGCGTGCCA    12
ATCTTCTAGGAGATTTGTTT    12
ATTGTTCAAATGATCTTCTA    12
GATCACTCCCACCTTCAAGG    12
TGAGGAGCAGGTACTGGCCC     4
GTACCTGCTCCTCACCATCC     4
TTTGCCTACAAGGAAAAAAA     4
AGCAGGTACTGGCCCGGCAG     4
GTGAGGAGCAGGTACTGGCC     4
GATGGTGAGGAGCAGGTACT     4
CATCCGGGGTTTTCGCGCTT     4
GGATGGTGAGGAGCAGGTAC     4
GGAGCAGGTACTGGCCCGGC     4
TACCTGCTCCTCACCATCCG     4
AGTACCTGCTCCTCACCATC     4
TCCTCACCATCCGGGGTTTT     4
CTCACCATCCGGGGTTTTCG     4
CAGGTACTGGCCCGGCAGCG     4
ACCTGCTCCTCACCATCCGG     4
ACCCCGGATGGTGAGGAGCA     4
AACCCCGGATGGTGAGGAGC     4
CCATCCGGGGTTTTCGCGCT     4
Name: count, dtype: int64

In [25]:
df[df['sgRNA Sequence']=='AACATGTCTGTACCTACTGA']

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,Target Transcript ID,Target Domain,sgRNA Sequence,sgRNA Context Sequence,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note,Source Study
28882,ENST00000258149.11,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000258149.11,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,34A>G,Met12Val,Missense,NaN,NaN,GR
30096,ENST00000539479.6,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000539479.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
31310,ENST00000393416.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393416.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
32620,ENST00000544561.6,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000544561.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
33762,ENST00000393412.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393412.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
34364,ENST00000350057.9,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000350057.9,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
35552,ENST00000258148.11,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000258148.11,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,34A>G,Met12Val,Missense,NaN,NaN,GR
36606,ENST00000299252.8,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000299252.8,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
37384,ENST00000360430.6,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000360430.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
38100,ENST00000545204.2,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000545204.2,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
38286,ENST00000393415.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393415.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
38940,ENST00000348801.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000348801.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,2A>G,Met2Val,Missense,NaN,WARNING: Annotated CDS is 5' incomplete--base ...,GR
39602,ENST00000393410.5,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393410.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
40196,ENST00000478070.2,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000478070.2,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,2A>G,Met2Val,Missense,NaN,WARNING: Annotated CDS is 5' incomplete--base ...,GR
40342,ENST00000393413.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393413.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
40882,ENST00000523991.5,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000523991.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
41226,ENST00000543323.5,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000543323.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
41516,ENST00000517852.5,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000517852.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809227A>G,A_4,16A>G,Met6Val,Missense,NaN,NaN,GR
28883,ENST00000258149.11,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000258149.11,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,38C>T,Ser13Phe,Missense,NaN,NaN,GR
30097,ENST00000539479.6,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000539479.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
31311,ENST00000393416.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393416.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
32621,ENST00000544561.6,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000544561.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
33763,ENST00000393412.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393412.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
34365,ENST00000350057.9,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000350057.9,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
35553,ENST00000258148.11,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000258148.11,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,38C>T,Ser13Phe,Missense,NaN,NaN,GR
36607,ENST00000299252.8,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000299252.8,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
37385,ENST00000360430.6,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000360430.6,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
38101,ENST00000545204.2,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000545204.2,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
38287,ENST00000393415.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393415.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
38941,ENST00000348801.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000348801.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,6C>T,Ser3Phe,Missense,NaN,WARNING: Annotated CDS is 5' incomplete--base ...,GR
39603,ENST00000393410.5,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393410.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
40197,ENST00000478070.2,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000478070.2,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,6C>T,Ser3Phe,Missense,NaN,WARNING: Annotated CDS is 5' incomplete--base ...,GR
40343,ENST00000393413.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000393413.7,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
40883,ENST00000523991.5,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000523991.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
41227,ENST00000543323.5,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000543323.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR
41517,ENST00000517852.5,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000012.12,ENSG00000135679,MDM2,+,ENST00000517852.5,CDS,AACATGTCTGTACCTACTGA,TACCAACATGTCTGTACCTACTGATGGTGC,TG,68809224,sense,68809231C>T,C_8,20C>T,Ser7Phe,Missense,NaN,NaN,GR

## Inspect Z-scores dataset

In [203]:
zscores.head()

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,MELJUSO_Cisplatin_RepB_RH,MELJUSO_Cisplatin_RepC_RH,MELJUSO_Talazoparib_RepA_RH,MELJUSO_Talazoparib_RepB_RH,MELJUSO_Talazoparib_RepC_RH,MELJUSO_A1331852_RepA_RH,MELJUSO_A1331852_RepB_RH,MELJUSO_A1331852+S63845_RepA_RH,MELJUSO_A1331852+S63845_RepB_RH,MELJUSO_S63845_RepA_RH,MELJUSO_S63845_RepB_RH,MELJUSO_S63845_RepC_RH,MELJUSO_A1331852+S63845_RepC_RH,HAP1_Niraparib_RepA_RH,HAP1_Niraparib_RepB_RH,HAP1_Olaparib_RepA_RH,HAP1_Olaparib_RepB_RH,HAP1_Rucaparib_RepA_RH,HAP1_Rucaparib_RepB_RH,HAP1_Talazoparib_RepA_RH,HAP1_Talazoparib_RepB_RH,HAP1_Veliparib_RepA_RH,HAP1_Veliparib_RepB_RH,A549_repA_GR,A549_repB_GR,Meljuso_repA_GR,Meljuso_repB_GR,MeljusoDO__RepA-Day21_GR,MeljusoDO__RepB-Day21_GR,H23_Adag_RepA_MC,H23_Adag_RepB_MC,H23_Sotor_RepA_MC,H23_Sotor_RepB_MC,H23_T0_RepA_MC,H23_T0_RepB_MC,H_T29_Deb_Cet_RepA_MC,H_T29_Deb_Cet_RepB_MC,H_T29_Pict_RepA_MC,H_T29_Pict_RepB_MC,H_T29_T0_RepA_MC,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
0,AAAAAACAAAGAGGTTAAGT,NaN,NaN,-0.951173,-0.705150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.399766,-0.850045,-0.261749,0.247165,0.659803,-0.665224,0.447552,-0.097511,0.465241,-0.251476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AAAAAACATACCTCAACCCT,Unknown,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.139106,0.336076,NaN,NaN,1.197063,0.766154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAAAAACATACCTCAACCCT,Unknown,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.193520,-1.198078,0.255265,0.108357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,-0.224693,-0.401662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.568177,0.085975,-0.298666,-0.452660,0.011691,-0.337209,-0.528347,0.278782,0.075638,-0.156649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAAAAACTCAACAGCAGTGA,NRAS,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.089015,1.179011,NaN,NaN,0.680350,0.367874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [204]:
zscores['Editor'].value_counts()

Editor
CBE    29465
ABE    28060
Name: count, dtype: int64

### Check if the combination guide + editor is unique

In [183]:
unique_guide_editor = zscores[["Guide", "Editor"]].drop_duplicates()

In [212]:
#Duplicates without the first occurence - just extra ones
duplicates_guide_editor_exclude_first = zscores[zscores.duplicated(subset=["Guide", "Editor"], keep='first')]

In [186]:
print(f"Total combinations: {len(zscores)}")
print(f"Unique guide+editor combinations: {len(zscores) - len(duplicates_guide_editor_exclude_first)}")
print(f"Total duplicated guide+editor: {len(duplicates_guide_editor_exclude_first)}")

Total combinations: 69280
Unique guide+editor combinations: 68541
Total duplicated guide+editor: 739

In [213]:
duplicates_guide_editor_exclude_first['Gene'].value_counts()

Gene
Intergenic control        300
Non-targeting control     300
Panlethal splice donor    102
KIF11                       6
CHEK1                       6
Name: count, dtype: int64

In [227]:
duplicates_guide_editor_exclude_first[duplicates_guide_editor_exclude_first['Gene']=="CHEK1"]

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,MELJUSO_Cisplatin_RepB_RH,MELJUSO_Cisplatin_RepC_RH,MELJUSO_Talazoparib_RepA_RH,MELJUSO_Talazoparib_RepB_RH,MELJUSO_Talazoparib_RepC_RH,MELJUSO_A1331852_RepA_RH,MELJUSO_A1331852_RepB_RH,MELJUSO_A1331852+S63845_RepA_RH,MELJUSO_A1331852+S63845_RepB_RH,MELJUSO_S63845_RepA_RH,MELJUSO_S63845_RepB_RH,MELJUSO_S63845_RepC_RH,MELJUSO_A1331852+S63845_RepC_RH,HAP1_Niraparib_RepA_RH,HAP1_Niraparib_RepB_RH,HAP1_Olaparib_RepA_RH,HAP1_Olaparib_RepB_RH,HAP1_Rucaparib_RepA_RH,HAP1_Rucaparib_RepB_RH,HAP1_Talazoparib_RepA_RH,HAP1_Talazoparib_RepB_RH,HAP1_Veliparib_RepA_RH,HAP1_Veliparib_RepB_RH,A549_repA_GR,A549_repB_GR,Meljuso_repA_GR,Meljuso_repB_GR,MeljusoDO__RepA-Day21_GR,MeljusoDO__RepB-Day21_GR,H23_Adag_RepA_MC,H23_Adag_RepB_MC,H23_Sotor_RepA_MC,H23_Sotor_RepB_MC,H23_T0_RepA_MC,H23_T0_RepB_MC,H_T29_Deb_Cet_RepA_MC,H_T29_Deb_Cet_RepB_MC,H_T29_Pict_RepA_MC,H_T29_Pict_RepB_MC,H_T29_T0_RepA_MC,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
30369,ACTTACCCCTTTCATCCAAC,CHEK1,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.713820,0.431606,0.248641,-0.228750,-0.636608,-0.713824,-0.039964,0.088819,0.419999,0.606257,1.413069,-0.573026,0.345271,0.485681,0.520012,0.554125,NaN,0.653256,0.421779,-0.273685,-0.092107
30370,ACTTACCCCTTTCATCCAAC,CHEK1,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.529895,0.353101,-0.180849,-0.225341,0.291157,-0.095908,0.661442,0.559151,0.919432,0.159796,-0.185153,0.232496,0.391571,0.570022,0.464314,-0.062049,0.073851,0.470035,0.207169,-0.102038,0.563068
39994,CCATACCTATTCTGTCAAAA,CHEK1,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.031199,-0.450196,-0.010970,-0.085167,0.632236,-1.420106,0.598947,-0.484460,0.656078,0.009182,0.046809,-0.430836,0.438667,0.222304,-0.173335,0.627538,NaN,0.074962,0.691846,-0.220005,0.075426
39995,CCATACCTATTCTGTCAAAA,CHEK1,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.081916,0.017688,0.142524,-0.647135,0.129998,-0.515950,0.504722,0.355162,-0.123621,0.101847,-0.406443,-0.475761,0.289555,0.457606,0.186735,-0.024477,0.593854,0.537809,0.155624,-0.081612,-0.706473
59368,TACCTACCACCCCTGCCATG,CHEK1,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.261301,-2.226856,-1.362710,-1.927411,0.833941,-0.374345,-3.190286,-3.043873,-3.296336,-3.423602,1.603771,-0.426943,-3.122489,-2.860290,-2.455743,-3.025585,NaN,-3.647102,-3.443451,0.465147,0.609416
59369,TACCTACCACCCCTGCCATG,CHEK1,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.771976,0.595955,1.125842,0.064811,1.017133,0.384554,0.486008,0.618423,0.840831,0.483348,0.757549,0.450990,0.804919,0.913818,0.799729,-0.459076,-0.496823,0.585211,0.370099,0.330696,1.252828

#### Find Duplicates

In [188]:
#Keep all occurences
duplicates_guide_editor_all = zscores[zscores.duplicated(subset=["Guide", "Editor"], keep=False)]
duplicates_guide_editor_all = duplicates_guide_editor_all.sort_values(by=["Guide", "Editor"])

In [221]:
duplicates_guides_editor_2 = zscores[['Guide','Gene', 'Editor']][zscores[['Guide', 'Editor']].duplicated(keep=False)]
duplicates_guides_editor_2 = duplicates_guides_editor_2.sort_values(by="Guide")

In [ ]:
duplicates_guides_editor_2

In [191]:
duplicates_guide_editor_all.head(30)

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,MELJUSO_Cisplatin_RepB_RH,MELJUSO_Cisplatin_RepC_RH,MELJUSO_Talazoparib_RepA_RH,MELJUSO_Talazoparib_RepB_RH,MELJUSO_Talazoparib_RepC_RH,MELJUSO_A1331852_RepA_RH,MELJUSO_A1331852_RepB_RH,MELJUSO_A1331852+S63845_RepA_RH,MELJUSO_A1331852+S63845_RepB_RH,MELJUSO_S63845_RepA_RH,MELJUSO_S63845_RepB_RH,MELJUSO_S63845_RepC_RH,MELJUSO_A1331852+S63845_RepC_RH,HAP1_Niraparib_RepA_RH,HAP1_Niraparib_RepB_RH,HAP1_Olaparib_RepA_RH,HAP1_Olaparib_RepB_RH,HAP1_Rucaparib_RepA_RH,HAP1_Rucaparib_RepB_RH,HAP1_Talazoparib_RepA_RH,HAP1_Talazoparib_RepB_RH,HAP1_Veliparib_RepA_RH,HAP1_Veliparib_RepB_RH,A549_repA_GR,A549_repB_GR,Meljuso_repA_GR,Meljuso_repB_GR,MeljusoDO__RepA-Day21_GR,MeljusoDO__RepB-Day21_GR,H23_Adag_RepA_MC,H23_Adag_RepB_MC,H23_Sotor_RepA_MC,H23_Sotor_RepB_MC,H23_T0_RepA_MC,H23_T0_RepB_MC,H_T29_Deb_Cet_RepA_MC,H_T29_Deb_Cet_RepB_MC,H_T29_Pict_RepA_MC,H_T29_Pict_RepB_MC,H_T29_T0_RepA_MC,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
49,AAAACGACCACCCGAAACCT,Intergenic control,NaN,0.358829,0.398810,0.491665,0.343819,0.541732,0.428779,0.506140,0.473278,0.416660,0.397684,0.714714,0.692261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,AAAACGACCACCCGAAACCT,Intergenic control,NaN,0.381906,0.415234,0.320488,0.473810,0.512631,0.243859,0.227668,0.509492,0.154346,0.549584,0.724715,0.347595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,AAAACGACCACCCGAAACCT,Intergenic control,NaN,NaN,NaN,NaN,-0.059376,-0.103101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.089156,0.174013,0.037794,0.499306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,AAAACGACCACCCGAAACCT,Intergenic control,NaN,NaN,NaN,NaN,0.184070,0.141041,0.149054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.049103,0.294921,0.226127,0.260674,0.232652,0.104482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,AAAACGACCACCCGAAACCT,Intergenic control,NaN,-0.394636,-0.209558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.146135,-0.209743,-0.297471,-0.647489,-0.108410,0.373883,-0.449512,-0.357660,-0.475640,-0.137061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,AAAGAAAAGGGACACACAAG,NaN,NaN,NaN,NaN,NaN,0.118646,0.060589,0.018551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.057903,0.063059,0.129129,0.142368,0.115514,0.120159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
234,AAAGAAAAGGGACACACAAG,NaN,NaN,-0.309396,-0.052298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.982533,-0.851708,-0.273344,-0.385301,-0.133441,0.243361,-0.045976,-0.002284,-0.400066,-0.606220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,AAAGCTATTTATCGCGTCGT,Non-targeting control,NaN,0.731711,0.751685,0.603324,1.089284,1.080425,0.856131,1.084410,1.188381,0.848919,1.258195,1.268452,0.665045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,AAAGCTATTTATCGCGTCGT,Non-targeting control,NaN,0.780848,0.654370,0.646133,0.850416,1.010726,1.019904,0.682538,0.977962,1.013086,1.049080,1.106750,0.950232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,AAAGCTATTTATCGCGTCGT,Non-targeting control,NaN,NaN,NaN,NaN,0.038038,0.086937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.128261,0.277760,-0.112866,-0.058145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,AAAGCTATTTATCGCGTCGT,Non-targeting control,NaN,NaN,NaN,NaN,0.349055,0.314872,0.271189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.288458,0.253222,0.409945,0.325650,0.445364,0.465116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,AAAGCTATTTATCGCGTCGT,Non-targeting control,NaN,0.333923,0.572500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.063679,0.203611,0.407791,0.147482,0.272895,0.585305,0.240719,0.538336,-0.168531,0.236455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,AAAGGGACACACAAGGGGCT,NaN,NaN,NaN,NaN,NaN,0.475202,0.387260,0.428881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.317038,0.263015,0.530449,0.534646,0.526331,0.279854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,AAAGGGACACACAAGGGGCT,NaN,NaN,0.748790,0.714548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258736,0.642446,0.245280,0.296237,0.235635,1.027067,0.477344,0.918486,0.148029,0.367313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
413,AAATACTCGATCGACGACTA,Non-targeting control,NaN,0.214334,0.324260,0.396224,0.283177,0.656410,0.384221,0.564401,0.664997,0.574866,0.649387,0.603505,0.608221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,AAATACTCGATCGACGACTA,Non-targeting control,NaN,0.397331,0.517444,0.342853,0.594530,0.500525,0.518944,0.592074,0.587990,0.464464,0.565920,0.507360,0.648970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,AAATACTCGATCGACGACTA,Non-targeting control,NaN,NaN,NaN,NaN,-0.036242,-0.015119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.056294,0.183115,-0.099651,-0.277487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,AAATACTCGATCGACGACTA,Non-targeting control,NaN,NaN,NaN,NaN,-0.014785,0.025419,-0.012872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.235832,0.160043,0.139035,0.121061,0.206411,0.238603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,AAATACTCGATCGACGACTA,Non-targeting control,NaN,0.039318,0.280213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.309604,-0.131581,0.266381,-0.097696,0.102531,0.501414,0.634483,0.257860,0.282778,1.320167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
449,AAATCGCTAAGGTAGCATAT,Intergenic control,NaN,0.556991,0.427480,0.491764,0.081356,0.346465,0.077816,0.510779,0.470952,0.492401,-0.076131,0.524323,0.347067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450,AAATCGCTAAGGTAGCATAT,Intergenic control,NaN,0.493772,0.473508,0.567202,0.154352,0.151639,0.192725,0.451820,0.490759,0.418826,0.177861,0.445888,0.319909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,AAATCGCTAAGGTAGCATAT,Intergenic control,NaN,NaN,NaN,NaN,0.367986,0.046735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.731878,0.153813,0.930630,0.255975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,AAATCGCTAAGGTAGCATAT,Intergenic control,NaN,NaN,NaN,NaN,0.123059,0.178068,0.143081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.114388,0.235864,0.345220,0.295955,0.287074,0.195595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,AAATCGCTAAGGTAGCATAT,Intergenic control,NaN,0.784517,0.282301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.132436,0.185167,0.298583,0.390531,0.461825,0.446000,0.368737,0.542187,0.477209,-0.176446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
508,AACAACGCGTCGCGATAGTG,Non-targeting control,NaN,0.642725,0.658511,0.706422,0.600802,0.927961,0.918884,1.122555,1.004794,0.815065,0.764165,1.192721,1.084365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
509,AACAACGCGTCGCGATAGTG,Non-targeting control,NaN,0.587016,0.781391,0.676977,0.757886,0.439719,0.785588,0.840422,0.851368,0.366738,0.990128,0.761844,0.969099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
510,AACAACGCGTCGCGATAGTG,Non-targeting control,NaN,NaN,NaN,NaN,0.380215,0.296770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.463510,0.410219,0.857227,0.492076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
511,AACAACGCGTCGCGATAGTG,Non-targeting control,NaN,NaN,NaN,NaN,0.464501,0.434269,0.393957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.322712,0.287965,0.514825,0.452136,0.493171,0.447882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
512,AACAACGCGTCGCGATAGTG,Non-targeting control,NaN,0.697311,0.492017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.353095,0.641483,0.503136,0.745588,0.798585,0.918960,0.691744,0.719473,0.671297,0.517598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,AACTCCTACGAAGATAGTAC,Intergenic control,NaN,-1.015327,-0.714903,-1.140326,-1.479212,-1.300507,-1.554576,-1.569762,-1.642923,-1.685711,-0.916969,-1.272790,-1.194196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [173]:
dup_counts = duplicates_guide_editor_all.groupby(["Guide", "Editor"]).size().reset_index(name='Count')
dup_counts = dup_counts.sort_values(by='Count', ascending=False)
dup_counts.head()

                   Guide Editor  Count
0   AACTTACATGATACACCCAA    ABE      2
1   AACTTACATGATACACCCAA    CBE      2
16  TACCTACCACCCCTGCCATG    ABE      2
15  GTTACCATATCAAAAGTGTA    CBE      2
14  GTTACCATATCAAAAGTGTA    ABE      2

In [194]:
duplicates_guide_editor_all[duplicates_guide_editor_all['Gene']=="KIF11"]

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,MELJUSO_Cisplatin_RepB_RH,MELJUSO_Cisplatin_RepC_RH,MELJUSO_Talazoparib_RepA_RH,MELJUSO_Talazoparib_RepB_RH,MELJUSO_Talazoparib_RepC_RH,MELJUSO_A1331852_RepA_RH,MELJUSO_A1331852_RepB_RH,MELJUSO_A1331852+S63845_RepA_RH,MELJUSO_A1331852+S63845_RepB_RH,MELJUSO_S63845_RepA_RH,MELJUSO_S63845_RepB_RH,MELJUSO_S63845_RepC_RH,MELJUSO_A1331852+S63845_RepC_RH,HAP1_Niraparib_RepA_RH,HAP1_Niraparib_RepB_RH,HAP1_Olaparib_RepA_RH,HAP1_Olaparib_RepB_RH,HAP1_Rucaparib_RepA_RH,HAP1_Rucaparib_RepB_RH,HAP1_Talazoparib_RepA_RH,HAP1_Talazoparib_RepB_RH,HAP1_Veliparib_RepA_RH,HAP1_Veliparib_RepB_RH,A549_repA_GR,A549_repB_GR,Meljuso_repA_GR,Meljuso_repB_GR,MeljusoDO__RepA-Day21_GR,MeljusoDO__RepB-Day21_GR,H23_Adag_RepA_MC,H23_Adag_RepB_MC,H23_Sotor_RepA_MC,H23_Sotor_RepB_MC,H23_T0_RepA_MC,H23_T0_RepB_MC,H_T29_Deb_Cet_RepA_MC,H_T29_Deb_Cet_RepB_MC,H_T29_Pict_RepA_MC,H_T29_Pict_RepB_MC,H_T29_T0_RepA_MC,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
30357,ACTTACCAAATAAGGTCTTA,KIF11,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.417944,-2.880408,-1.938050,-1.932047,-0.008614,0.330512,-4.580494,-3.710864,-3.097162,-6.057163,-0.068485,0.349273,-5.358400,-5.243727,-6.340259,-6.014284,NaN,-5.666649,-6.591256,-0.053646,0.065124
30358,ACTTACCAAATAAGGTCTTA,KIF11,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.773737,-3.471023,-4.202262,-3.387995,0.877371,-0.084933,-0.764474,-0.014912,-0.333121,-0.742626,-0.695132,0.698085,-1.107200,-0.407144,-1.459019,0.584743,-1.173693,-1.009990,-0.529065,0.361174,-0.258186
52998,GCTTACCAAGTTCAACTTTC,KIF11,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.174736,-0.228366,-0.091821,-1.037850,0.023417,-1.122295,0.442462,-0.751747,0.554392,0.613103,-0.218770,-1.518848,0.059052,-0.089589,-0.174878,0.365289,NaN,0.066551,0.128231,-0.199503,0.229045
52999,GCTTACCAAGTTCAACTTTC,KIF11,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.147866,0.150448,-0.252601,-0.326692,0.462815,-0.405228,0.708243,0.509147,0.567549,-0.123706,-1.251673,-0.009896,0.249923,0.253674,-0.357331,-0.585100,-1.189055,-0.048489,0.118248,-1.165441,-0.381622
58162,GTTACCATATCAAAAGTGTA,KIF11,ABE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.397776,-0.743674,0.488165,-1.473123,-1.508308,-0.156078,-1.129735,-2.554066,-3.346577,-3.922919,-0.867063,-0.533651,-1.987718,-3.338375,-3.552989,-3.355616,NaN,-4.167681,-4.508446,-0.354380,-0.173860
58163,GTTACCATATCAAAAGTGTA,KIF11,CBE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.056505,-4.065147,-2.542023,-3.651041,0.234705,0.186452,-0.207498,-0.139085,0.641425,-0.647020,-0.683178,0.045265,-0.600415,-1.105157,-0.565936,-0.605108,-0.646182,-1.262851,-0.550633,-0.502903,0.254499

Check If some are actually duplicated rows

In [196]:
duplicated_rows = duplicates_guide_editor_all[duplicates_guide_editor_all.duplicated(keep="first")]

In [197]:
len(duplicated_rows)

0

In [223]:
duplicated_rows.head(20)

Empty DataFrame
Columns: [Guide, Gene, Editor, HAP1_Dropout_RepA_RH, HAP1_Dropout_RepB_RH, HAP1_Dropout_RepC_RH, MELJUSO_Dropout_RepA_RH, MELJUSO_Dropout_RepB_RH, MELJUSO_Dropout_RepC_RH, MELJUSO_Cisplatin_RepA_RH, MELJUSO_Cisplatin_RepB_RH, MELJUSO_Cisplatin_RepC_RH, MELJUSO_Talazoparib_RepA_RH, MELJUSO_Talazoparib_RepB_RH, MELJUSO_Talazoparib_RepC_RH, MELJUSO_A1331852_RepA_RH, MELJUSO_A1331852_RepB_RH, MELJUSO_A1331852+S63845_RepA_RH, MELJUSO_A1331852+S63845_RepB_RH, MELJUSO_S63845_RepA_RH, MELJUSO_S63845_RepB_RH, MELJUSO_S63845_RepC_RH, MELJUSO_A1331852+S63845_RepC_RH, HAP1_Niraparib_RepA_RH, HAP1_Niraparib_RepB_RH, HAP1_Olaparib_RepA_RH, HAP1_Olaparib_RepB_RH, HAP1_Rucaparib_RepA_RH, HAP1_Rucaparib_RepB_RH, HAP1_Talazoparib_RepA_RH, HAP1_Talazoparib_RepB_RH, HAP1_Veliparib_RepA_RH, HAP1_Veliparib_RepB_RH, A549_repA_GR, A549_repB_GR, Meljuso_repA_GR, Meljuso_repB_GR, MeljusoDO__RepA-Day21_GR, MeljusoDO__RepB-Day21_GR, H23_Adag_RepA_MC, H23_Adag_RepB_MC, H23_Sotor_RepA_MC, H23_Sotor_RepB_MC, H23_T0_RepA_MC, H23_T0_RepB_MC, H_T29_Deb_Cet_RepA_MC, H_T29_Deb_Cet_RepB_MC, H_T29_Pict_RepA_MC, H_T29_Pict_RepB_MC, H_T29_T0_RepA_MC, H_T29_T0_RepB_MC, H_T29_Tram_RepA_MC, H_T29_Tram_RepB_MC, P_C9_Gefit_RepA_MC, P_C9_Gefit_RepB_MC, P_C9_Gefit_RepC_MC, P_C9_Osim_RepA_MC, P_C9_Osim_RepB_MC, P_C9_T0_RepA_MC, P_C9_T0_RepB_MC]
Index: []

In [101]:
duplicated_rows["Gene"].value_counts()

Gene
Panlethal splice donor    34
PLK1                       6
Name: count, dtype: int64

In [79]:
duplicated_rows = duplicated_rows.sort_values(by=["Guide", "Editor"])

In [102]:
duplicates_guide_editor_all[duplicates_guide_editor_all['Gene'].isin(['SNRPD1', 'RPS20'])]

,Guide,Gene,Editor,HAP1_Dropout_RepA_RH,HAP1_Dropout_RepB_RH,HAP1_Dropout_RepC_RH,MELJUSO_Dropout_RepA_RH,MELJUSO_Dropout_RepB_RH,MELJUSO_Dropout_RepC_RH,MELJUSO_Cisplatin_RepA_RH,MELJUSO_Cisplatin_RepB_RH,MELJUSO_Cisplatin_RepC_RH,MELJUSO_Talazoparib_RepA_RH,MELJUSO_Talazoparib_RepB_RH,MELJUSO_Talazoparib_RepC_RH,MELJUSO_A1331852_RepA_RH,MELJUSO_A1331852_RepB_RH,MELJUSO_A1331852+S63845_RepA_RH,MELJUSO_A1331852+S63845_RepB_RH,MELJUSO_S63845_RepA_RH,MELJUSO_S63845_RepB_RH,MELJUSO_S63845_RepC_RH,MELJUSO_A1331852+S63845_RepC_RH,HAP1_Niraparib_RepA_RH,HAP1_Niraparib_RepB_RH,HAP1_Olaparib_RepA_RH,HAP1_Olaparib_RepB_RH,HAP1_Rucaparib_RepA_RH,HAP1_Rucaparib_RepB_RH,HAP1_Talazoparib_RepA_RH,HAP1_Talazoparib_RepB_RH,HAP1_Veliparib_RepA_RH,HAP1_Veliparib_RepB_RH,A549_repA_GR,A549_repB_GR,Meljuso_repA_GR,Meljuso_repB_GR,MeljusoDO__RepA-Day21_GR,MeljusoDO__RepB-Day21_GR,H23_Adag_RepA_MC,H23_Adag_RepB_MC,H23_Sotor_RepA_MC,H23_Sotor_RepB_MC,H23_T0_RepA_MC,H23_T0_RepB_MC,H_T29_Deb_Cet_RepA_MC,H_T29_Deb_Cet_RepB_MC,H_T29_Pict_RepA_MC,H_T29_Pict_RepB_MC,H_T29_T0_RepA_MC,H_T29_T0_RepB_MC,H_T29_Tram_RepA_MC,H_T29_Tram_RepB_MC,P_C9_Gefit_RepA_MC,P_C9_Gefit_RepB_MC,P_C9_Gefit_RepC_MC,P_C9_Osim_RepA_MC,P_C9_Osim_RepB_MC,P_C9_T0_RepA_MC,P_C9_T0_RepB_MC
5735,CCGTACCTGTGATTGTTCCA,SNRPD1,CBE,-6.534114,-5.296860,-6.609487,-3.918466,-4.961585,-5.332899,-4.353594,-4.146240,-4.695254,-4.143514,-4.279334,-4.653640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.211831,-8.386984,-6.859871,-7.773726,0.097808,0.380523,-4.231161,-3.409385,-5.662972,-5.526494,-0.340714,-1.292572,-6.528938,-4.622018,-2.530514,-1.647726,-1.563514,-3.617379,-1.807372,-0.995542,-1.397876
5736,CCGTACCTGTGATTGTTCCA,SNRPD1,CBE,-6.286240,-6.073250,-6.099765,-5.534955,-5.878389,-6.235645,-5.437615,-5.288653,-5.565868,-4.530137,-4.189612,-5.493696,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.211831,-8.386984,-6.859871,-7.773726,0.097808,0.380523,-4.231161,-3.409385,-5.662972,-5.526494,-0.340714,-1.292572,-6.528938,-4.622018,-2.530514,-1.647726,-1.563514,-3.617379,-1.807372,-0.995542,-1.397876
5737,CCGTACCTGTGATTGTTCCA,SNRPD1,CBE,NaN,NaN,NaN,-5.536486,-5.729262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.694300,-4.712445,-4.490440,-3.638169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.211831,-8.386984,-6.859871,-7.773726,0.097808,0.380523,-4.231161,-3.409385,-5.662972,-5.526494,-0.340714,-1.292572,-6.528938,-4.622018,-2.530514,-1.647726,-1.563514,-3.617379,-1.807372,-0.995542,-1.397876
5738,CCGTACCTGTGATTGTTCCA,SNRPD1,CBE,NaN,NaN,NaN,-5.163081,-5.232361,-5.189369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.592989,-4.538641,-3.901856,-4.023920,-4.191349,-4.350735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.211831,-8.386984,-6.859871,-7.773726,0.097808,0.380523,-4.231161,-3.409385,-5.662972,-5.526494,-0.340714,-1.292572,-6.528938,-4.622018,-2.530514,-1.647726,-1.563514,-3.617379,-1.807372,-0.995542,-1.397876
6864,CTCACCATGGCTGTTGCGCG,RPS20,CBE,-2.153313,-2.384335,-1.894698,0.615911,0.680435,0.468495,-0.774529,-0.171912,-0.445356,1.270381,0.725081,0.840660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.611546,-2.007531,-1.978845,-2.602807,-0.207238,-0.373473,0.048889,0.400142,-0.326631,-0.393037,-1.206402,-0.969924,-0.344409,-0.113246,2.893856,0.132943,-1.473483,-0.967577,-0.023235,-0.866334,-0.100183
6865,CTCACCATGGCTGTTGCGCG,RPS20,CBE,-2.015319,-2.148343,-2.208505,0.820794,1.355135,0.834903,0.447030,0.548915,0.474840,0.881518,1.226989,0.553087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.611546,-2.007531,-1.978845,-2.602807,-0.207238,-0.373473,0.048889,0.400142,-0.326631,-0.393037,-1.206402,-0.969924,-0.344409,-0.113246,2.893856,0.132943,-1.473483,-0.967577,-0.023235,-0.866334,-0.100183
6866,CTCACCATGGCTGTTGCGCG,RPS20,CBE,NaN,NaN,NaN,-1.803546,-1.718805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.808812,-1.724993,-2.110765,-1.894978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.611546,-2.007531,-1.978845,-2.602807,-0.207238,-0.373473,0.048889,0.400142,-0.326631,-0.393037,-1.206402,-0.969924,-0.344409,-0.113246,2.893856,0.132943,-1.473483,-0.967577,-0.023235,-0.866334,-0.100183
6867,CTCACCATGGCTGTTGCGCG,RPS20,CBE,NaN,NaN,NaN,-1.569905,-1.497773,-1.845665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.711169,-1.524247,-1.414889,-1.205273,-1.534772,-1.437470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.611546,-2.007531,-1.978845,-2.602807,-0.207238,-0.373473,0.048889,0.400142,-0.326631,-0.393037,-1.206402,-0.969924,-0.344409,-0.113246,2.893856,0.132943,-1.473483,-0.967577,-0.023235,-0.866334,-0.100183