In [45]:
import re
import numpy as np
import pandas as pd

## Import Beagle sgRNA annotation

In [40]:
variants = pd.read_csv(f"../data/BeagleCoelho/EG_collab-guides.txt", sep="\t")
variants.shape

(24752, 24)

In [46]:
variants.sample(10)

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,...,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
475,ENST00000262948.10,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,...,TG,4097335,sense,4097351G>A,C_4,920-8C>T,(NC),Intron,NaN,NaN
7831,ENST00000275493.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,...,AG,55181285,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6244,ENST00000275493.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,...,TG,55156636,antisense,55156652T>C,A_4,1126T>C,Phe376Leu,Missense,NaN,NaN
5832,ENST00000275493.7,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,...,GG,55154053,antisense,"55154066T>C, 55154069T>C","A_7, A_4","803T>C, 806T>C","Met268Thr, Leu269Pro","Missense, Missense",NaN,NaN
9257,ENST00000275493.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,...,AG,55205352,sense,"55205356C>T, 55205359C>T","C_5, C_8","3372C>T, 3375C>T","His1124His, Tyr1125Tyr","Silent, Silent",NaN,NaN
3426,ENST00000263967.4,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000003.12,ENSG00000121879,PIK3CA,+,...,AG,179219238,antisense,179219251T>C,A_7,1720T>C,Trp574Arg,Missense,NaN,NaN
21952,ENST00000646891.2,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000007.14,ENSG00000157764,BRAF,-,...,GG,140834629,antisense,140834635A>G;140834634A>G,A_7;A_6,478T>C;479T>C,Phe160Pro,Missense,NaN,NaN
10751,ENST00000307102.10,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,...,TG,66487217,sense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12753,ENST00000366794.10,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000001.11,ENSG00000143799,PARP1,-,...,TG,226361999,sense,226362014G>A;226362013G>A,C_5;C_6,2918C>T;2919C>T,Thr973Ile,Missense,NaN,NaN
5325,ENST00000275493.7,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000007.14,ENSG00000146648,EGFR,+,...,GG,55146601,antisense,"55146613G>A, 55146617G>A","C_8, C_4","432G>A, 436G>A","Leu144Leu, Gly146Ser","Silent, Missense",NaN,NaN

In [49]:
variants.loc[5325]

Input                                              ENST00000275493.7
CRISPR Enzyme                                             SpyoCas9NG
Edit Type                                                        C-T
Edit Window                                                     4..8
Target Taxon                                                    9606
Target Assembly                                               GRCh38
Target Genome Sequence                                  NC_000007.14
Target Gene ID                                       ENSG00000146648
Target Gene Symbol                                              EGFR
Target Gene Strand                                                 +
Target Transcript ID                               ENST00000275493.7
Target Domain                                                    CDS
sgRNA Sequence                                  CGCCATGCAGGATTTCTGCG
sgRNA Context Sequence                ACGGCGCCATGCAGGATTTCTGCGGGAGAA
PAM Sequence                                                      GG
sgRNA Sequence Start Pos. (global)                          55146601
sgRNA Orientation                                          antisense
Nucleotide Edits (global)                   55146613G>A, 55146617G>A
Guide Edits                                                 C_8, C_4
Nucleotide Edits                                      432G>A, 436G>A
Amino Acid Edits                                Leu144Leu, Gly146Ser
Mutation Category                                   Silent, Missense
Constraint Violations                                            NaN
Note                                                             NaN
Name: 5325, dtype: object

In [57]:
variants.loc[21952]

Input                                              ENST00000646891.2
CRISPR Enzyme                                             SpyoCas9NG
Edit Type                                                        A-G
Edit Window                                                     4..8
Target Taxon                                                    9606
Target Assembly                                               GRCh38
Target Genome Sequence                                  NC_000007.14
Target Gene ID                                       ENSG00000157764
Target Gene Symbol                                              BRAF
Target Gene Strand                                                 -
Target Transcript ID                               ENST00000646891.2
Target Domain                                                    CDS
sgRNA Sequence                                  GCAGGAAGACTCTAACGATA
sgRNA Context Sequence                TTGGGCAGGAAGACTCTAACGATAGGTTTT
PAM Sequence                                                      GG
sgRNA Sequence Start Pos. (global)                         140834629
sgRNA Orientation                                          antisense
Nucleotide Edits (global)                  140834635A>G;140834634A>G
Guide Edits                                                  A_7;A_6
Nucleotide Edits                                       478T>C;479T>C
Amino Acid Edits                                           Phe160Pro
Mutation Category                                           Missense
Constraint Violations                                            NaN
Note                                                             NaN
Name: 21952, dtype: object

In [56]:
variants["sgRNA Sequence"].value_counts().value_counts()

count
2    12346
4       15
Name: count, dtype: int64

In [53]:
variants.query("`sgRNA Sequence` == 'GGAGTTGGCCATGGAGTCGA'")

,Input,CRISPR Enzyme,Edit Type,Edit Window,Target Taxon,Target Assembly,Target Genome Sequence,Target Gene ID,Target Gene Symbol,Target Gene Strand,...,PAM Sequence,sgRNA Sequence Start Pos. (global),sgRNA Orientation,Nucleotide Edits (global),Guide Edits,Nucleotide Edits,Amino Acid Edits,Mutation Category,Constraint Violations,Note
890,ENST00000262948.10,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,...,TG,4101046,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,ENST00000262948.10,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000019.10,ENSG00000126934,MAP2K2,-,...,TG,4101046,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10410,ENST00000307102.10,SpyoCas9NG,A-G,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,...,TG,66481833,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10411,ENST00000307102.10,SpyoCas9NG,C-T,4..8,9606,GRCh38,NC_000015.10,ENSG00000169032,MAP2K1,+,...,TG,66481833,antisense,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Format for ENSEMBL VEP input

Use the Beagle columns [input, Nucleotide Edits] and format as HGVS identifiers for ENSEMBL VEP. Examples include:

- `ENST00000618231.3:c.9G>C`
- `ENST00000471631.1:c.28_33delTCGCGG`
- `ENST00000285667.3:c.1047_1048insC`
- `5:g.140532G>C`

In [47]:
def format_variant(variant="1033T>C;1034T>C;1035T>C") -> str:
    if ";" not in variant:
        return variant

    else:
        # input: 1033T>C;1034T>C;1035T>C
        # output: 1033_1035T>C

        # Parse the input string into a list of tuples (position, original_base, altered_base)
        edits = re.findall(r"(\d+)([A-Z])>([A-Z])", variant)

        # Extract positions from the parsed data
        positions = [int(edit[0]) for edit in edits]

        # Check if the positions are consecutive
        if all(positions[i] + 1 == positions[i + 1] for i in range(len(positions) - 1)):
            # Return the compact format
            return f"{positions[0]}_{positions[-1]}{edits[0][1]}>{edits[0][2]}"

        else:
            # If not consecutive, return the input as it is
            return variant

'1033_1035T>C'

In [48]:
ensembl_vep_input = "\n".join(
    [
        f"{g}:c.{format_variant(e)}"
        for g, v in variants[["Input", "Nucleotide Edits"]].values
        if v is not np.nan
        for e in v.split(", ")
    ]
)
print(ensembl_vep_input)

ENST00000262948.10:c.*12C>T
ENST00000262948.10:c.*14C>T
ENST00000262948.10:c.*7C>T
ENST00000262948.10:c.*8C>T
ENST00000262948.10:c.*2A>G
ENST00000262948.10:c.1203A>G
ENST00000262948.10:c.*2A>G
ENST00000262948.10:c.*1C>T
ENST00000262948.10:c.*9G>A
ENST00000262948.10:c.*10G>A
ENST00000262948.10:c.*11G>A
ENST00000262948.10:c.*9G>A
ENST00000262948.10:c.*10G>A
ENST00000262948.10:c.*11G>A
ENST00000262948.10:c.*5G>A
ENST00000262948.10:c.*6G>A
ENST00000262948.10:c.*9G>A
ENST00000262948.10:c.*4T>C
ENST00000262948.10:c.*5G>A
ENST00000262948.10:c.*6G>A
ENST00000262948.10:c.1196_1197C>T
ENST00000262948.10:c.*4T>C
ENST00000262948.10:c.*3G>A
ENST00000262948.10:c.*5G>A
ENST00000262948.10:c.*6G>A
ENST00000262948.10:c.1196_1197C>T
ENST00000262948.10:c.1194C>T
ENST00000262948.10:c.1196_1197C>T
ENST00000262948.10:c.*4T>C
ENST00000262948.10:c.*3G>A
ENST00000262948.10:c.1201T>C
ENST00000262948.10:c.1202G>A
ENST00000262948.10:c.1192A>G
ENST00000262948.10:c.1191C>T
ENST00000262948.10:c.1193_1194C>T
ENST00000262948.10:c.1192A>G
ENST00000262948.10:c.1191C>T
ENST00000262948.10:c.1193_1194C>T
ENST00000262948.10:c.1199T>C
ENST00000262948.10:c.1201T>C
ENST00000262948.10:c.1200G>A
ENST00000262948.10:c.1202G>A
ENST00000262948.10:c.1199T>C
ENST00000262948.10:c.1201T>C
ENST00000262948.10:c.1198G>A;1200G>A
ENST00000262948.10:c.1202G>A
ENST00000262948.10:c.1192A>G
ENST00000262948.10:c.1189C>T;1191C>T
ENST00000262948.10:c.1199T>C
ENST00000262948.10:c.1201T>C
ENST00000262948.10:c.1198G>A;1200G>A
ENST00000262948.10:c.1199T>C
ENST00000262948.10:c.1195G>A
ENST00000262948.10:c.1198G>A
ENST00000262948.10:c.1186A>G
ENST00000262948.10:c.1184_1185C>T
ENST00000262948.10:c.1187C>T
ENST00000262948.10:c.1195G>A
ENST00000262948.10:c.1182A>G
ENST00000262948.10:c.1186A>G
ENST00000262948.10:c.1183_1185C>T
ENST00000262948.10:c.1190G>A
ENST00000262948.10:c.1180A>G;1182A>G
ENST00000262948.10:c.1181C>T
ENST00000262948.10:c.1183_1184C>T
ENST00000262948.10:c.1190G>A
ENST00000262948.10:c.1188G>A
ENST00000262948.10:c.1190G>A
ENST00000262948.10:c.1180A>G
ENST00000262948.10:c.1179C>T
ENST00000262948.10:c.1181C>T
ENST00000262948.10:c.1188G>A
ENST00000262948.10:c.1188G>A
ENST00000262948.10:c.1172A>G
ENST00000262948.10:c.1174_1176C>T
ENST00000262948.10:c.1172A>G
ENST00000262948.10:c.1170C>T
ENST00000262948.10:c.1171C>T
ENST00000262948.10:c.1174C>T
ENST00000262948.10:c.1177_1178G>A
ENST00000262948.10:c.1173G>A
ENST00000262948.10:c.1177G>A
ENST00000262948.10:c.1173G>A
ENST00000262948.10:c.1173G>A
ENST00000262948.10:c.1162C>T
ENST00000262948.10:c.1159C>T
ENST00000262948.10:c.1162C>T
ENST00000262948.10:c.1155A>G
ENST00000262948.10:c.1156A>G
ENST00000262948.10:c.1157_1158C>T
ENST00000262948.10:c.1159C>T
ENST00000262948.10:c.1153A>G
ENST00000262948.10:c.1160T>C
ENST00000262948.10:c.1161G>A
ENST00000262948.10:c.1143C>T
ENST00000262948.10:c.1133A>G
ENST00000262948.10:c.1133A>G
ENST00000262948.10:c.1128A>G
ENST00000262948.10:c.1127_1128A>G
ENST00000262948.10:c.1124_1125A>G
ENST00000262948.10:c.1127_1128A>G
ENST00000262948.10:c.1124_1125A>G
ENST00000262948.10:c.1127A>G
ENST00000262948.10:c.1130T>C
ENST00000262948.10:c.1134T>C
ENST00000262948.10:c.1131G>A
ENST00000262948.10:c.1132G>A
ENST00000262948.10:c.1124A>G
ENST00000262948.10:c.1130T>C
ENST00000262948.10:c.1129G>A;1131G>A
ENST00000262948.10:c.1132G>A
ENST00000262948.10:c.1126G>A
ENST00000262948.10:c.1129G>A
ENST00000262948.10:c.1118A>G
ENST00000262948.10:c.1115_1116C>T
ENST00000262948.10:c.1115_1116C>T
ENST00000262948.10:c.1121T>C
ENST00000262948.10:c.1122G>A
ENST00000262948.10:c.1123G>A
ENST00000262948.10:c.1111C>T
ENST00000262948.10:c.1115C>T
ENST00000262948.10:c.1121T>C
ENST00000262948.10:c.1119G>A
ENST00000262948.10:c.1120G>A;1122G>A
ENST00000262948.10:c.1108_1109A>G
ENST00000262948.10:c.1111C>T
ENST00000262948.10:c.1117G>A;1119G>A
ENST00000262948.10:c.1105A>G
ENST00000262948.10:c.1108_1109A>G
ENST00000262948.10:c.1107C>T
ENST00000262948.10:c.1114T>C
ENST00000262948.10:c.1117G>A
ENST00000262948.10:c.1105A>G
ENST00000262948.10:c.1108A>G
ENST00000262948.10:c.1104C>T
ENST00000262948.10:c.1107C>T
ENST00000262948.10:c.1114T>C
ENST00000262948.10:c.1112_1113G>A
ENST00000262948.10:c.1105A>G
ENST00000262948.10:c.1104C>T
ENST00000262948.10:c.1105A>G
ENST00000262948.10:c.1101C>T
ENST00000262948.10:c.1104C>T
ENST00000262948.10:c.1114T>C
ENST00000262948.10:c.1110G>A
ENST00000262948.10:c.1112_1113G>A
ENST00000262948.10:c.1110G>A
ENST00000262948.10:c.1112_1113G>A
ENST00000262948.10:c.1099A>G
ENST00000262948.10:c.1100_1101C>T
ENST00000262948.10:c.1097A>G
ENST00000262948.10:c.1099A>G
ENST00000262948.10:c.1095C>T
ENST00000262948.10:c.1096C>T;1098C>T
ENST00000262948.10:c.1106T>C
ENST00000262948.10:c.1094A>G
ENST00000262948.10:c.1097A>G
ENST00000262948.10:c.1095C>T
ENST00000262948.10:c.1096C>T;1098C>T
ENST00000262948.10:c.1093_1094A>G
ENST00000262948.10:c.1095C>T
ENST00000262948.10:c.1096C>T
ENST00000262948.10:c.1102_1103T>C
ENST00000262948.10:c.1102_1103T>C
ENST00000262948.10:c.1093-1G>A
ENST00000262948.10:c.1093-1G>A
ENST00000262948.10:c.1093-6T>C
ENST00000262948.10:c.1093-5T>C
ENST00000262948.10:c.1093-4G>A
ENST00000262948.10:c.1093-6T>C
ENST00000262948.10:c.1093-5T>C
ENST00000262948.10:c.1093-4G>A
ENST00000262948.10:c.1093-10T>C
ENST00000262948.10:c.1093-9T>C
ENST00000262948.10:c.1093-6T>C
ENST00000262948.10:c.1092+8A>G
ENST00000262948.10:c.1092+11C>T
ENST00000262948.10:c.1092+8A>G
ENST00000262948.10:c.1092+8A>G
ENST00000262948.10:c.1092A>G
ENST00000262948.10:c.1092+4A>G
ENST00000262948.10:c.1092+9T>C
ENST00000262948.10:c.1092+10G>A
ENST00000262948.10:c.1092A>G
ENST00000262948.10:c.1091C>T
ENST00000262948.10:c.1090A>G;1092A>G
ENST00000262948.10:c.1091C>T
ENST00000262948.10:c.1090A>G;1092A>G
ENST00000262948.10:c.1089C>T
ENST00000262948.10:c.1091C>T
ENST00000262948.10:c.1084A>G
ENST00000262948.10:c.1087C>T
ENST00000262948.10:c.1092+2T>C
ENST00000262948.10:c.1092+1G>A
ENST00000262948.10:c.1092+3G>A
ENST00000262948.10:c.1092+2T>C
ENST00000262948.10:c.1092+1G>A
ENST00000262948.10:c.1092+3G>A
ENST00000262948.10:c.1081_1082A>G
ENST00000262948.10:c.1084A>G
ENST00000262948.10:c.1081_1082A>G
ENST00000262948.10:c.1088T>C
ENST00000262948.10:c.1081A>G
ENST00000262948.10:c.1077C>T
ENST00000262948.10:c.1078C>T
ENST00000262948.10:c.1076A>G
ENST00000262948.10:c.1077C>T
ENST00000262948.10:c.1078C>T
ENST00000262948.10:c.1085T>C
ENST00000262948.10:c.1083G>A
ENST00000262948.10:c.1086G>A
ENST00000262948.10:c.1079T>C
ENST00000262948.10:c.1080G>A
ENST00000262948.10:c.1069C>T
ENST00000262948.10:c.1079T>C
ENST00000262948.10:c.1075G>A
ENST00000262948.10:c.1067A>G
ENST00000262948.10:c.1069C>T
ENST00000262948.10:c.1074G>A
ENST00000262948.10:c.1075G>A
ENST00000262948.10:c.1074G>A
ENST00000262948.10:c.1075G>A
ENST00000262948.10:c.1062A>G
ENST00000262948.10:c.1064C>T
ENST00000262948.10:c.1068G>A
ENST00000262948.10:c.1070_1071G>A
ENST00000262948.10:c.1057_1058A>G
ENST00000262948.10:c.1059C>T
ENST00000262948.10:c.1060_1061C>T
ENST00000262948.10:c.1057_1058A>G
ENST00000262948.10:c.1059C>T
ENST00000262948.10:c.1060C>T
ENST00000262948.10:c.1065G>A
ENST00000262948.10:c.1066G>A;1068G>A
ENST00000262948.10:c.1054_1055A>G
ENST00000262948.10:c.1057_1058A>G
ENST00000262948.10:c.1054_1055A>G
ENST00000262948.10:c.1057A>G
ENST00000262948.10:c.1053C>T
ENST00000262948.10:c.1063G>A;1065G>A
ENST00000262948.10:c.1066G>A
ENST00000262948.10:c.1054_1055A>G
ENST00000262948.10:c.1053C>T
ENST00000262948.10:c.1063G>A;1065G>A
ENST00000262948.10:c.1051A>G
ENST00000262948.10:c.1054A>G
ENST00000262948.10:c.1050C>T
ENST00000262948.10:c.1053C>T
ENST00000262948.10:c.1051A>G
ENST00000262948.10:c.1048C>T;1050C>T
ENST00000262948.10:c.1051A>G
ENST00000262948.10:c.1047C>T
ENST00000262948.10:c.1048C>T;1050C>T
ENST00000262948.10:c.1056G>A
ENST00000262948.10:c.1056G>A
ENST00000262948.10:c.1047-2A>G
ENST00000262948.10:c.1047C>T
ENST00000262948.10:c.1048C>T
ENST00000262948.10:c.1056G>A
ENST00000262948.10:c.1047-9A>G
ENST00000262948.10:c.1047-8A>G
ENST00000262948.10:c.1047-7C>T
ENST00000262948.10:c.1047-6C>T
ENST00000262948.10:c.1047-5C>T
ENST00000262948.10:c.1049T>C
ENST00000262948.10:c.1049T>C
ENST00000262948.10:c.1047-1G>A
ENST00000262948.10:c.1047-1G>A
ENST00000262948.10:c.1047-11G>A
ENST00000262948.10:c.1047-10G>A
ENST00000262948.10:c.1047-12T>C
ENST00000262948.10:c.1047-11G>A
ENST00000262948.10:c.1047-10G>A
ENST00000262948.10:c.1047-13T>C
ENST00000262948.10:c.1047-12T>C
ENST00000262948.10:c.1047-11G>A
ENST00000262948.10:c.1047-10G>A
ENST00000262948.10:c.1046+3A>G
ENST00000262948.10:c.1043_1044A>G
ENST00000262948.10:c.1046+6T>C
ENST00000262948.10:c.1046+7G>A
ENST00000262948.10:c.1046+8G>A
ENST00000262948.10:c.1046+10G>A
ENST00000262948.10:c.1042_1044A>G
ENST00000262948.10:c.1042_1044A>G
ENST00000262948.10:c.1039_1040A>G
ENST00000262948.10:c.1042A>G
ENST00000262948.10:c.1038C>T
ENST00000262948.10:c.1039_1040A>G
ENST00000262948.10:c.1038C>T
ENST00000262948.10:c.1039A>G
ENST00000262948.10:c.1038C>T
ENST00000262948.10:c.1041T>C
ENST00000262948.10:c.1045T>C
ENST00000262948.10:c.1041T>C
ENST00000262948.10:c.1031A>G
ENST00000262948.10:c.1028A>G
ENST00000262948.10:c.1031A>G
ENST00000262948.10:c.1037T>C
ENST00000262948.10:c.1041T>C
ENST00000262948.10:c.1034_1035T>C
ENST00000262948.10:c.1037T>C
ENST00000262948.10:c.1036G>A
ENST00000262948.10:c.1033_1035T>C
ENST00000262948.10:c.1037T>C
ENST00000262948.10:c.1036G>A
ENST00000262948.10:c.1033_1035T>C
ENST00000262948.10:c.1032G>A
ENST00000262948.10:c.1036G>A
ENST00000262948.10:c.1033_1035T>C
ENST00000262948.10:c.1032G>A
ENST00000262948.10:c.1033_1034T>C
ENST00000262948.10:c.1030G>A;1032G>A
ENST00000262948.10:c.1029G>A
ENST00000262948.10:c.1030G>A;1032G>A
ENST00000262948.10:c.1022A>G
ENST00000262948.10:c.1018_1020C>T
ENST00000262948.10:c.1015A>G
ENST00000262948.10:c.1014C>T
ENST00000262948.10:c.1016_1017C>T
ENST00000262948.10:c.1018C>T
ENST00000262948.10:c.1015A>G
ENST00000262948.10:c.1014C>T
ENST00000262948.10:c.1016C>T
ENST00000262948.10:c.1015A>G
ENST00000262948.10:c.1014C>T
ENST00000262948.10:c.1021G>A
ENST00000262948.10:c.1003_1004A>G
ENST00000262948.10:c.1005C>T
ENST00000262948.10:c.1012_1013T>C
ENST00000262948.10:c.1011G>A
ENST00000262948.10:c.1008T>C
ENST00000262948.10:c.1010T>C
ENST00000262948.10:c.1006_1007G>A
ENST00000262948.10:c.1009G>A
ENST00000262948.10:c.1008T>C
ENST00000262948.10:c.1006_1007G>A
ENST00000262948.10:c.1009G>A
ENST00000262948.10:c.1006_1007G>A
ENST00000262948.10:c.994_995A>G
ENST00000262948.10:c.997C>T
ENST00000262948.10:c.1006G>A
ENST00000262948.10:c.994_995A>G
ENST00000262948.10:c.991_992C>T
ENST00000262948.10:c.999G>A
ENST00000262948.10:c.989C>T
ENST00000262948.10:c.991_992C>T
ENST00000262948.10:c.988_989C>T
ENST00000262948.10:c.991_992C>T
ENST00000262948.10:c.998T>C
ENST00000262948.10:c.996G>A
ENST00000262948.10:c.999G>A
ENST00000262948.10:c.998T>C
ENST00000262948.10:c.996G>A
ENST00000262948.10:c.993T>C
ENST00000262948.10:c.996G>A
ENST00000262948.10:c.993T>C
ENST00000262948.10:c.985-4A>G
ENST00000262948.10:c.985-2A>G
ENST00000262948.10:c.985-3C>T
ENST00000262948.10:c.985C>T
ENST00000262948.10:c.990T>C
ENST00000262948.10:c.993T>C
ENST00000262948.10:c.990T>C
ENST00000262948.10:c.985-4A>G
ENST00000262948.10:c.985-6C>T
ENST00000262948.10:c.985-5C>T
ENST00000262948.10:c.985-3C>T
ENST00000262948.10:c.985-1G>A
ENST00000262948.10:c.985-1G>A
ENST00000262948.10:c.985-1G>A
ENST00000262948.10:c.985-7T>C
ENST00000262948.10:c.985-7T>C
ENST00000262948.10:c.985-10T>C
ENST00000262948.10:c.985-7T>C
ENST00000262948.10:c.985-10T>C
ENST00000262948.10:c.985-7T>C
ENST00000262948.10:c.984+8C>T
ENST00000262948.10:c.980A>G
ENST00000262948.10:c.983A>G
ENST00000262948.10:c.981C>T
ENST00000262948.10:c.979_980A>G
ENST00000262948.10:c.981C>T
ENST00000262948.10:c.984+2T>C
ENST00000262948.10:c.984+3T>C
ENST00000262948.10:c.984G>A
ENST00000262948.10:c.984+1G>A
ENST00000262948.10:c.973A>G
ENST00000262948.10:c.971A>G
ENST00000262948.10:c.973A>G
ENST00000262948.10:c.978G>A
ENST00000262948.10:c.982G>A
ENST00000262948.10:c.977T>C
ENST00000262948.10:c.978G>A
ENST00000262948.10:c.968A>G
ENST00000262948.10:c.971A>G
ENST00000262948.10:c.969C>T
ENST00000262948.10:c.968A>G
ENST00000262948.10:c.969C>T
ENST00000262948.10:c.975T>C
ENST00000262948.10:c.977T>C
ENST00000262948.10:c.976G>A;978G>A
ENST00000262948.10:c.968A>G
ENST00000262948.10:c.964C>T
ENST00000262948.10:c.960A>G
ENST00000262948.10:c.961C>T;963C>T
ENST00000262948.10:c.964C>T
ENST00000262948.10:c.970T>C;972T>C
ENST00000262948.10:c.959_960A>G
ENST00000262948.10:c.961C>T
ENST00000262948.10:c.965T>C
ENST00000262948.10:c.966G>A
ENST00000262948.10:c.967G>A
ENST00000262948.10:c.965T>C
ENST00000262948.10:c.966G>A
ENST00000262948.10:c.967G>A
ENST00000262948.10:c.962T>C
ENST00000262948.10:c.952A>G
ENST00000262948.10:c.950_951C>T
ENST00000262948.10:c.962T>C
ENST00000262948.10:c.958G>A
ENST00000262948.10:c.952A>G
ENST00000262948.10:c.950_951C>T
ENST00000262948.10:c.955_957T>C
ENST00000262948.10:c.958G>A
ENST00000262948.10:c.955_957T>C
ENST00000262948.10:c.958G>A
ENST00000262948.10:c.953T>C
ENST00000262948.10:c.955T>C
ENST00000262948.10:c.953T>C
ENST00000262948.10:c.940_941C>T
ENST00000262948.10:c.944C>T
ENST00000262948.10:c.932A>G
ENST00000262948.10:c.934A>G
ENST00000262948.10:c.932A>G
ENST00000262948.10:c.934A>G
ENST00000262948.10:c.942T>C
ENST00000262948.10:c.938_939G>A
ENST00000262948.10:c.938_939G>A
ENST00000262948.10:c.928A>G
ENST00000262948.10:c.933T>C
ENST00000262948.10:c.931G>A
ENST00000262948.10:c.935G>A
ENST00000262948.10:c.923A>G
ENST00000262948.10:c.922C>T;924C>T
ENST00000262948.10:c.923A>G
ENST00000262948.10:c.922C>T;924C>T
ENST00000262948.10:c.920-2A>G
ENST00000262948.10:c.920-3C>T
ENST00000262948.10:c.929T>C
ENST00000262948.10:c.926_927G>A
ENST00000262948.10:c.930G>A
ENST00000262948.10:c.929T>C
ENST00000262948.10:c.925_927G>A
ENST00000262948.10:c.925_927G>A
ENST00000262948.10:c.920-3C>T
ENST00000262948.10:c.925_926G>A
ENST00000262948.10:c.920-8C>T
ENST00000262948.10:c.921T>C
ENST00000262948.10:c.920G>A
ENST00000262948.10:c.920-10C>T
ENST00000262948.10:c.920-9C>T
ENST00000262948.10:c.920-8C>T
ENST00000262948.10:c.921T>C
ENST00000262948.10:c.920-1G>A
ENST00000262948.10:c.920G>A
ENST00000262948.10:c.920-12C>T
ENST00000262948.10:c.920-10C>T
ENST00000262948.10:c.920-9C>T
ENST00000262948.10:c.920-8C>T
ENST00000262948.10:c.920-12C>T
ENST00000262948.10:c.920-10C>T
ENST00000262948.10:c.920-9C>T
ENST00000262948.10:c.920-5T>C
ENST00000262948.10:c.920-4G>A
ENST00000262948.10:c.920-1G>A
ENST00000262948.10:c.920-5T>C
ENST00000262948.10:c.920-6G>A
ENST00000262948.10:c.920-4G>A
ENST00000262948.10:c.920-7T>C
ENST00000262948.10:c.920-5T>C
ENST00000262948.10:c.920-6G>A
ENST00000262948.10:c.920-4G>A
ENST00000262948.10:c.920-7T>C
ENST00000262948.10:c.920-5T>C
ENST00000262948.10:c.920-6G>A
ENST00000262948.10:c.920-11T>C
ENST00000262948.10:c.920-7T>C
ENST00000262948.10:c.920-13T>C
ENST00000262948.10:c.920-11T>C
ENST00000262948.10:c.919+11A>G
ENST00000262948.10:c.919+12A>G
ENST00000262948.10:c.919+8C>T
ENST00000262948.10:c.919+11A>G
ENST00000262948.10:c.919+7C>T
ENST00000262948.10:c.919+8C>T
ENST00000262948.10:c.919+13T>C
ENST00000262948.10:c.919+10G>A
ENST00000262948.10:c.918C>T
ENST00000262948.10:c.919+9T>C
ENST00000262948.10:c.919+10G>A
ENST00000262948.10:c.919+9T>C
ENST00000262948.10:c.919+6G>A
ENST00000262948.10:c.919+10G>A
ENST00000262948.10:c.919+9T>C
ENST00000262948.10:c.919+5G>A
ENST00000262948.10:c.919+6G>A
ENST00000262948.10:c.919+5G>A
ENST00000262948.10:c.919+6G>A
ENST00000262948.10:c.919+2T>C
ENST00000262948.10:c.919+5G>A
ENST00000262948.10:c.919+6G>A
ENST00000262948.10:c.911_912C>T
ENST00000262948.10:c.915C>T
ENST00000262948.10:c.919+2T>C
ENST00000262948.10:c.917G>A
ENST00000262948.10:c.919G>A
ENST00000262948.10:c.919+1G>A
ENST00000262948.10:c.907C>T;909C>T
ENST00000262948.10:c.910_911C>T
ENST00000262948.10:c.917G>A
ENST00000262948.10:c.919G>A
ENST00000262948.10:c.919+1G>A
ENST00000262948.10:c.907C>T;909C>T
ENST00000262948.10:c.910C>T
ENST00000262948.10:c.917G>A
ENST00000262948.10:c.919G>A
ENST00000262948.10:c.914T>C
ENST00000262948.10:c.917G>A
ENST00000262948.10:c.914T>C
ENST00000262948.10:c.913G>A
ENST00000262948.10:c.917G>A
ENST00000262948.10:c.914T>C
ENST00000262948.10:c.913G>A
ENST00000262948.10:c.902_903C>T
ENST00000262948.10:c.901_903C>T
ENST00000262948.10:c.899_900C>T
ENST00000262948.10:c.901_903C>T
ENST00000262948.10:c.908G>A
ENST00000262948.10:c.906G>A
ENST00000262948.10:c.908G>A
ENST00000262948.10:c.895A>G
ENST00000262948.10:c.898_899C>T
ENST00000262948.10:c.904_906G>A
ENST00000262948.10:c.904_905G>A
ENST00000262948.10:c.904G>A
ENST00000262948.10:c.892_893C>T
ENST00000262948.10:c.889C>T
ENST00000262948.10:c.892C>T
ENST00000262948.10:c.887C>T
ENST00000262948.10:c.889C>T
ENST00000262948.10:c.896_897G>A
ENST00000262948.10:c.886_887C>T
ENST00000262948.10:c.889C>T
ENST00000262948.10:c.894G>A
ENST00000262948.10:c.896_897G>A
ENST00000262948.10:c.890_891G>A
ENST00000262948.10:c.894G>A
ENST00000262948.10:c.880A>G
ENST00000262948.10:c.879C>T
ENST00000262948.10:c.882C>T
ENST00000262948.10:c.888T>C
ENST00000262948.10:c.890_891G>A
ENST00000262948.10:c.880A>G
ENST00000262948.10:c.879C>T
ENST00000262948.10:c.882C>T
ENST00000262948.10:c.888T>C
ENST00000262948.10:c.890G>A
ENST00000262948.10:c.877A>G
ENST00000262948.10:c.880A>G
ENST00000262948.10:c.876C>T
ENST00000262948.10:c.879C>T
ENST00000262948.10:c.888T>C
ENST00000262948.10:c.885G>A
ENST00000262948.10:c.875A>G
ENST00000262948.10:c.877A>G
ENST00000262948.10:c.874C>T;876C>T
ENST00000262948.10:c.875A>G
ENST00000262948.10:c.872C>T
ENST00000262948.10:c.874C>T;876C>T
ENST00000262948.10:c.867A>G
ENST00000262948.10:c.869A>G
ENST00000262948.10:c.871C>T
ENST00000262948.10:c.860_861A>G
ENST00000262948.10:c.863_864A>G
ENST00000262948.10:c.873T>C
ENST00000262948.10:c.870G>A
ENST00000262948.10:c.866G>A
ENST00000262948.10:c.868G>A;870G>A
ENST00000262948.10:c.854A>G
ENST00000262948.10:c.852C>T
ENST00000262948.10:c.855C>T
ENST00000262948.10:c.862G>A
ENST00000262948.10:c.854A>G
ENST00000262948.10:c.852C>T
ENST00000262948.10:c.859G>A
ENST00000262948.10:c.862G>A
ENST00000262948.10:c.858G>A
ENST00000262948.10:c.859G>A
ENST00000262948.10:c.862G>A
ENST00000262948.10:c.852C>T
ENST00000262948.10:c.856_858G>A
ENST00000262948.10:c.859G>A
ENST00000262948.10:c.856_858G>A
ENST00000262948.10:c.844_846C>T
ENST00000262948.10:c.841C>T
ENST00000262948.10:c.844_845C>T
ENST00000262948.10:c.840C>T
ENST00000262948.10:c.841C>T
ENST00000262948.10:c.844C>T
ENST00000262948.10:c.840C>T
ENST00000262948.10:c.841C>T
ENST00000262948.10:c.848T>C
ENST00000262948.10:c.851T>C
ENST00000262948.10:c.849G>A
ENST00000262948.10:c.850G>A
ENST00000262948.10:c.840C>T
ENST00000262948.10:c.841C>T
ENST00000262948.10:c.848T>C
ENST00000262948.10:c.847G>A;849G>A
ENST00000262948.10:c.848T>C
ENST00000262948.10:c.847G>A
ENST00000262948.10:c.832A>G
ENST00000262948.10:c.834C>T
ENST00000262948.10:c.832A>G
ENST00000262948.10:c.831C>T
ENST00000262948.10:c.834C>T
ENST00000262948.10:c.832A>G
ENST00000262948.10:c.830_831C>T
ENST00000262948.10:c.837T>C
ENST00000262948.10:c.838_839G>A
ENST00000262948.10:c.827A>G
ENST00000262948.10:c.827A>G
ENST00000262948.10:c.821A>G
ENST00000262948.10:c.823C>T
ENST00000262948.10:c.833T>C
ENST00000262948.10:c.821A>G
ENST00000262948.10:c.823C>T
ENST00000262948.10:c.833T>C
ENST00000262948.10:c.829G>A
ENST00000262948.10:c.828G>A
ENST00000262948.10:c.829G>A
ENST00000262948.10:c.824T>C
ENST00000262948.10:c.825G>A
ENST00000262948.10:c.826G>A;828G>A
ENST00000262948.10:c.824T>C
ENST00000262948.10:c.825G>A
ENST00000262948.10:c.826G>A
ENST00000262948.10:c.824T>C
ENST00000262948.10:c.822G>A
ENST00000262948.10:c.825G>A
ENST00000262948.10:c.826G>A
ENST00000262948.10:c.812A>G
ENST00000262948.10:c.813C>T
ENST00000262948.10:c.815C>T
ENST00000262948.10:c.824T>C
ENST00000262948.10:c.820G>A;822G>A
ENST00000262948.10:c.812A>G
ENST00000262948.10:c.810C>T
ENST00000262948.10:c.813C>T
ENST00000262948.10:c.820G>A;822G>A
ENST00000262948.10:c.820G>A;822G>A
ENST00000262948.10:c.812A>G
ENST00000262948.10:c.808_810C>T
ENST00000262948.10:c.820G>A
ENST00000262948.10:c.808_810C>T
ENST00000262948.10:c.820G>A
ENST00000262948.10:c.804C>T
ENST00000262948.10:c.805_806C>T

In [41]:
with open("../data/BeagleCoelho/EG_collab-guides-VEP-HGVS-input.txt", "w") as f:
    f.write(ensembl_vep_input)

## ENSEMBL VEP command

In [ ]:
!./vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --domains --gencode_primary --mane --plugin SpliceAI,snv=[path_to]/spliceai_scores.masked.snv.hg38.vcf.gz,indel=[path_to]/spliceai_scores.masked.indel.hg38.vcf.gz,snv_ensembl=[path_to]/spliceai_scores.raw.snv.ensembl_mane.grch38.110.vcf.gz --plugin AncestralAllele,[path_to]/homo_sapiens_ancestor_GRCh38_109.fa.gz --plugin Enformer,file=[path_to]/enformer_grch38.vcf.gz --plugin AlphaMissense,file=[path_to]/AlphaMissense_hg38.tsv.gz --plugin dbscSNV,[path_to]/dbscSNV1.1_GRCh38.txt.gz --plugin ClinPred,file=[path_to]/ClinPred_hg38_sorted_tabbed.tsv.gz --plugin MaxEntScan,[path_to]/maxentscan --plugin LOEUF,file=[path_to]/loeuf_dataset_grch38.tsv.gz,match_by=gene --plugin REVEL,file=[path_to]/new_tabbed_revel_grch38.tsv.gz --plugin CADD,snv=[path_to]/CADD_GRCh38_1.7_whole_genome_SNVs.tsv.gz,indels=[path_to]/CADD_GRCh38_1.7_InDels.tsv.gz --plugin EVE,file=[path_to]/eve_merged.vcf.gz --plugin mutfunc,db=[path_to]/mutfunc_data.db,motif=1,int=1,mod=1,exp=1 --plugin Blosum62 --plugin NMD --plugin MaveDB,file=[path_to]/MaveDB_variants.tsv.gz --polyphen b --pubmed --regulatory --show_ref_allele --sift b --species homo_sapiens --symbol --transcript_version --tsl --uploaded_allele --cache --input_file [input_data] --output_file [output_file]