# RH merge

In [1]:
import numpy as np
import pandas as pd
from dotenv import load_dotenv
import os

# load_dotenv()
# base_dir = os.getenv("BASE_DIR")

In [7]:
import os

print(os.path.exists("data"))  # Check if Jupyter sees the symlink
print(os.path.islink("data"))  # Check if Jupyter recognizes it as a symlink
print(os.path.realpath("data"))
print(os.path.exists("data/4_Screen_zscores/MC/MC_zscores.csv"))

True
True
/Users/joanacorreia/Library/CloudStorage/GoogleDrive-joana.d.correia@tecnico.ulisboa.pt/Discos partilhados/Cancer Scanning manuscript 2024/data
True

In [9]:
pd.read_csv('data/4_Screen_zscores/MC/MC_zscores.csv')

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,...,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,2.207324,0.402861,0.380062,0.498358,0.679475,-0.234903,-0.376278,...,-0.734241,-0.689801,0.240439,-0.370762,1.908978,NaN,-0.488552,1.837751,-0.158499,-0.000764
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,-1.449741,0.918920,-0.479678,0.626708,1.157473,0.264743,1.192417,...,0.468737,0.893703,2.496363,0.562802,2.152187,0.633014,-0.098675,0.476921,-0.139716,-0.328849
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,-1.188256,0.362693,-1.739719,0.661547,-0.935847,-1.540695,0.036072,...,-1.243106,0.548338,-1.459784,-0.265151,0.625855,NaN,-0.785432,-0.331351,-0.492798,-0.541818
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,-0.355967,0.737102,0.167383,-0.420221,-0.166197,0.000072,-0.607708,...,0.047498,-1.650291,-0.109189,-0.871263,-0.700061,-0.462142,0.832627,1.455213,0.324469,-0.294009
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,-1.144441,-0.043888,-3.221753,1.729673,-2.269742,0.380462,0.423973,...,0.068710,1.035790,0.660678,-0.716366,0.230420,NaN,-1.708553,-0.489586,-0.411487,-0.165079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45177,TTTTGTGCCCTGGACAAAGT,BRAF,CBE,-0.841507,-0.119980,-0.492832,0.024459,-0.545747,-0.910439,-0.263816,...,-0.438185,0.164489,-0.379012,-0.199170,0.694581,-0.228893,-1.447168,-1.064631,-0.744056,-0.533870
45178,TTTTGTGTGACAAAGCGTAA,EGFR,ABE,1.390007,0.312096,2.553973,0.915124,0.522594,-0.568829,-0.193819,...,-0.864846,0.089058,-0.963291,0.551462,-0.038006,NaN,0.531138,-0.757486,-0.215732,-0.158617
45179,TTTTGTGTGACAAAGCGTAA,EGFR,CBE,-1.340372,0.427779,-0.820609,-1.022415,-0.356682,-0.463192,0.281531,...,0.446262,-0.221084,1.179719,-0.296102,0.242962,0.821810,-0.157905,-0.522281,-0.850626,-0.495864
45180,TTTTGTTTCCTTGCTCACTG,BRAF,ABE,0.037051,-0.403228,-0.902262,1.595037,-1.235673,-0.016791,0.799449,...,-1.422284,1.016320,-2.068058,-0.568062,1.538046,NaN,-0.236400,0.464143,-0.572432,-0.588536
45181,TTTTGTTTCCTTGCTCACTG,BRAF,CBE,0.359126,0.485873,-0.091158,-0.558137,-0.487569,-0.699294,-0.308453,...,-0.297554,-1.331969,-0.115764,0.176681,-0.771864,1.423653,-0.323313,-0.217585,-0.379419,-0.531391

In [11]:
a=pd.read_csv("data/3_Counts/RH/RH_BRCA2_processed.csv")
b=pd.read_csv("data/3_Counts/RH/RH_BRCA2_processed.csv")
c=pd.read_csv("data/3_Counts/RH/RH_MCL1_processed.csv")
d=pd.read_csv("data/3_Counts/RH/RH_BCL2L1_processed.csv")
e=pd.read_csv("data/3_Counts/RH/RH_PARP1_processed.csv")

In [12]:
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

In [13]:
merge_BRCA=pd.concat([a, b], ignore_index=True)
merge_2=pd.concat([c, d], ignore_index=True)
merged_RH=pd.concat([merge_BRCA,merge_2,e], ignore_index=True)

merged_RH.to_csv('data/3_Counts/RH/merge_RH.csv')

In [31]:
# a.merge(b, on=['Guide','Gene','Editor'],how='outer')

In [24]:
merge_2

,Guide,Gene,Editor,pDNA,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_A1331852_RepA,MELJUSO_A1331852_RepB,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepC
0,AAGAAACCGATGGGACGCCG,Intergenic control,Unknown,8232,1654,1477,1564.0,1603.0,1766,1175,NaN,NaN,NaN,NaN,NaN
1,AGGAATGGAATTAGCGGACC,Intergenic control,Unknown,58089,9880,9246,9540.0,9423.0,6530,6938,NaN,NaN,NaN,NaN,NaN
2,ACTAACAATTAGCGCAGTTG,Intergenic control,Unknown,40478,7836,7969,7831.0,7972.0,6364,6273,NaN,NaN,NaN,NaN,NaN
3,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,65826,13781,12647,13360.0,12265.0,11955,7505,NaN,NaN,NaN,NaN,NaN
4,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,31162,5919,4504,6509.0,4379.0,4487,3186,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,332561,46331,52822,NaN,NaN,46049,48726,49665.0,53164.0,52653.0,56513.0,45511.0
704,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,272366,25939,30133,NaN,NaN,19716,21454,30949.0,31143.0,29537.0,31576.0,24565.0
705,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,337974,47757,53388,NaN,NaN,43296,50076,51898.0,56662.0,54237.0,58747.0,49465.0
706,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,297543,40244,48550,NaN,NaN,38967,39693,47602.0,49196.0,49324.0,50473.0,40460.0
707,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,213898,25199,29586,NaN,NaN,25303,24057,29919.0,30575.0,30256.0,31558.0,23759.0

In [ ]:
# merge zscores

a=pd.read_csv("data/4_Screen_zscores/RH/RH_BRCA2_zscores.csv")
b=pd.read_csv("data/4_Screen_zscores/RH/RH_BRCA2_zscores.csv")
c=pd.read_csv("data/4_Screen_zscores/RH/RH_MCL1_zscores.csv")
d=pd.read_csv("data/4_Screen_zscores/RH/RH_BCL2L1_zscores.csv")
e=pd.read_csv("data/4_Screen_zscores/RH/RH_PARP1_zscores.csv")
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

merge_BRCA_z=pd.concat([a, b], ignore_index=True)
merge_2_z=pd.concat([c, d], ignore_index=True)
merged_RH_z=pd.concat([merge_BRCA_z,merge_2_z,e], ignore_index=True)

merged_RH_z.to_csv("data/4_Screen_zscores/RH/merge_RH_z.csv")

In [ ]:
# merge LFC

a=pd.read_csv("data/5_LFC/RH/RH_BRCA2_LFC.csv")
b=pd.read_csv("data/5_LFC/RH/RH_BRCA2_LFC.csv")
c=pd.read_csv("data/5_LFC/RH/RH_MCL1_LFC.csv")
d=pd.read_csv("data/5_LFC/RH/RH_BCL2L1_LFC.csv")
e=pd.read_csv("data/5_LFC/RH/RH_PARP1_LFC.csv")
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

merge_BRCA_LFC=pd.concat([a, b], ignore_index=True)
merge_2_LFC=pd.concat([c, d], ignore_index=True)
merged_RH_LFC=pd.concat([merge_BRCA_LFC,merge_2_LFC,e], ignore_index=True)

merged_RH_LFC.to_csv("data/5_LFC/RH/merge_RH_z.csv")

# GR merge

In [ ]:
#for counts files better concat
A540="data/3_Counts/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Processed.csv")
MELJURO="data/3_Counts/GR/GR_MELJUSO_ABE_Processed.csv")
f=pd.read_csv(A540)
g=pd.read_csv(MELJURO)

f["Gene"] = f["Gene"].fillna("Unknown")
f['Editor']=  f["Editor"].fillna("Unknown")
g["Gene"] = g["Gene"].fillna("Unknown")
g['Editor']=  g["Editor"].fillna("Unknown")
merge_GR=pd.concat([f,g],ignore_index=True)
merge_GR.to_csv("data/5_LFC/GR/merge_GR.csv")

In [16]:
#for counts files better concat
A540="data/4_Screen_zscores/GR/GR_A549_ABE_CBE_MELJUSO_CBE_zscores.csv"
MELJURO="data/4_Screen_zscores/GR/GR_MELJUSO_ABE_zscores.csv"
f=pd.read_csv(A540)
g=pd.read_csv(MELJURO)

f["Gene"] = f["Gene"].fillna("Unknown")
f['Editor']=  f["Editor"].fillna("Unknown")
g["Gene"] = g["Gene"].fillna("Unknown")
g['Editor']=  g["Editor"].fillna("Unknown")
merge_GR_lfc=pd.concat([f,g],ignore_index=True)
merge_GR_lfc.to_csv("data/4_Screen_zscores/GR/merge_GR_z.csv")

In [38]:
pd.concat([f,g],ignore_index=True)

,Guide,Gene,Editor,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_A1331852+S63845_RepC
0,GTTCTACCTTCAGTCCGATG,Intergenic control,Unknown,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,0.368644,0.196900
1,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,0.359094,0.379809
2,GAAAAGTCATCCCACGAAGT,Intergenic control,Unknown,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,0.306998,0.388792
3,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,0.077617,0.087227
4,ACTAACGGCGCATCACCTAA,Intergenic control,Unknown,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,-0.072112,0.017476
...,...,...,...,...,...,...,...,...,...,...,...,...
627,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,0.501937,0.382684
628,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,-0.320942,-0.161255
629,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,0.516765,0.470306
630,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,0.377605,0.374369
631,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,0.151301,0.110477

In [39]:
g.merge(f,on=["Guide","Editor","Gene"])

,Guide,Gene,Editor,MELJUSO_Dropout_RepA_x,MELJUSO_Dropout_RepB_x,MELJUSO_Dropout_RepC_x,MELJUSO_S63845_RepA_x,MELJUSO_S63845_RepB_x,MELJUSO_S63845_RepC_x,MELJUSO_A1331852+S63845_RepA_x,...,MELJUSO_A1331852+S63845_RepC_x,MELJUSO_Dropout_RepA_y,MELJUSO_Dropout_RepB_y,MELJUSO_Dropout_RepC_y,MELJUSO_S63845_RepA_y,MELJUSO_S63845_RepB_y,MELJUSO_S63845_RepC_y,MELJUSO_A1331852+S63845_RepA_y,MELJUSO_A1331852+S63845_RepB_y,MELJUSO_A1331852+S63845_RepC_y
0,GTTCTACCTTCAGTCCGATG,Intergenic control,Unknown,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,...,0.196900,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,0.368644,0.196900
1,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,...,0.379809,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,0.359094,0.379809
2,GAAAAGTCATCCCACGAAGT,Intergenic control,Unknown,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,...,0.388792,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,0.306998,0.388792
3,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,...,0.087227,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,0.077617,0.087227
4,ACTAACGGCGCATCACCTAA,Intergenic control,Unknown,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,...,0.017476,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,-0.072112,0.017476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,...,0.382684,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,0.501937,0.382684
312,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,...,-0.161255,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,-0.320942,-0.161255
313,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,...,0.470306,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,0.516765,0.470306
314,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,...,0.374369,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,0.377605,0.374369
315,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,...,0.110477,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,0.151301,0.110477

# merge total

In [19]:
RH=pd.read_csv("data/4_Screen_zscores/RH/merge_RH_z.csv")
GR=pd.read_csv("data/4_Screen_zscores/GR/merge_GR_z.csv")
MC=pd.read_csv("data/4_Screen_zscores/MC/MC_zscores.csv")

In [23]:
RH.columns

Index(['Unnamed: 0', 'Guide', 'Gene', 'Editor', 'HAP1_Dropout_RepA',
       'HAP1_Dropout_RepB', 'HAP1_Dropout_RepC', 'MELJUSO_Dropout_RepA',
       'MELJUSO_Dropout_RepB', 'MELJUSO_Dropout_RepC',
       'MELJUSO_Cisplatin_RepA', 'MELJUSO_Cisplatin_RepB',
       'MELJUSO_Cisplatin_RepC', 'MELJUSO_Talazoparib_RepA',
       'MELJUSO_Talazoparib_RepB', 'MELJUSO_Talazoparib_RepC',
       'MELJUSO_A1331852_RepA', 'MELJUSO_A1331852_RepB',
       'MELJUSO_A1331852+S63845_RepA', 'MELJUSO_A1331852+S63845_RepB',
       'MELJUSO_S63845_RepA', 'MELJUSO_S63845_RepB', 'MELJUSO_S63845_RepC',
       'MELJUSO_A1331852+S63845_RepC', 'HAP1_Niraparib_RepA',
       'HAP1_Niraparib_RepB', 'HAP1_Olaparib_RepA', 'HAP1_Olaparib_RepB',
       'HAP1_Rucaparib_RepA', 'HAP1_Rucaparib_RepB', 'HAP1_Talazoparib_RepA',
       'HAP1_Talazoparib_RepB', 'HAP1_Veliparib_RepA', 'HAP1_Veliparib_RepB'],
      dtype='object')

In [24]:
GR.columns

Index(['Unnamed: 0', 'Guide', 'Gene', 'Editor', 'MELJUSO_Dropout_RepA',
       'MELJUSO_Dropout_RepB', 'MELJUSO_Dropout_RepC', 'MELJUSO_S63845_RepA',
       'MELJUSO_S63845_RepB', 'MELJUSO_S63845_RepC',
       'MELJUSO_A1331852+S63845_RepA', 'MELJUSO_A1331852+S63845_RepB',
       'MELJUSO_A1331852+S63845_RepC'],
      dtype='object')

In [25]:
MC.columns

Index(['Guide', 'Gene', 'Editor', 'H23_Adag_RepA', 'H23_Adag_RepB',
       'H23_Sotor_RepA', 'H23_Sotor_RepB', 'H23_T0_RepA', 'H23_T0_RepB',
       'H_T29_Deb_Cet_RepA', 'H_T29_Deb_Cet_RepB', 'H_T29_Pict_RepA',
       'H_T29_Pict_RepB', 'H_T29_T0_RepA', 'H_T29_T0_RepB', 'H_T29_Tram_RepA',
       'H_T29_Tram_RepB', 'P_C9_Gefit_RepA', 'P_C9_Gefit_RepB',
       'P_C9_Gefit_RepC', 'P_C9_Osim_RepA', 'P_C9_Osim_RepB', 'P_C9_T0_RepA',
       'P_C9_T0_RepB'],
      dtype='object')

In [ ]:
RH.concat(GR, on=["Guide", "Gene"],how='outer')

,Unnamed: 0_x,Guide,Gene,Editor_x,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Dropout_RepC,MELJUSO_Dropout_RepA_x,MELJUSO_Dropout_RepB_x,MELJUSO_Dropout_RepC_x,...,Editor_y,MELJUSO_Dropout_RepA_y,MELJUSO_Dropout_RepB_y,MELJUSO_Dropout_RepC_y,MELJUSO_S63845_RepA_y,MELJUSO_S63845_RepB_y,MELJUSO_S63845_RepC_y,MELJUSO_A1331852+S63845_RepA_y,MELJUSO_A1331852+S63845_RepB_y,MELJUSO_A1331852+S63845_RepC_y
0,2400,AAAAAACAAAGAGGTTAAGT,Unknown,Unknown,-0.951173,-0.705150,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2401,AAAAAACCAAATCGCCACGT,Unknown,Unknown,-0.224693,-0.401662,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2402,AAAAAACTGTTTGGGACCTC,Unknown,Unknown,0.628855,0.114103,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2403,AAAAAAGAGATCCACAAAGA,Unknown,Unknown,-1.110632,-1.137100,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,AAAAAATGTTGGCCTCTCTT,BRCA2,CBE,0.370728,0.399599,0.422990,0.483982,0.469075,0.426036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14843,13697,TTTGTGGATGGTAAGAATTG,Unknown,Unknown,0.709514,0.769138,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14844,479,TTTGTGTAGCTGTATACGTA,BRCA2,CBE,0.523799,0.673458,0.598981,1.054009,1.012350,0.860802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14845,1248,TTTGTGTAGCTGTATACGTA,BRCA2,CBE,0.523799,0.673458,0.598981,1.054009,1.012350,0.860802,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14846,13698,TTTGTTCTCCACTAGCACCA,Unknown,Unknown,-1.234291,-1.702548,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14847,13699,TTTGTTGATGGCCTCTCGGA,Unknown,Unknown,0.528186,0.188317,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
print(f'RH shape:{ RH.shape}, GR shape: {GR.shape}')
print('RH and GR merge has len', RH.shape[0]+GR.shape[0])

RH shape:(13700, 34), GR shape: (632, 13)
RH and GR merge has len 14332

In [42]:
RH

,Unnamed: 0,Guide,Gene,Editor,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Dropout_RepC,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,...,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,0,AAAAAATGTTGGCCTCTCTT,BRCA2,CBE,0.370728,0.399599,0.422990,0.483982,0.469075,0.426036,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,GGGTTTCTCTTATCAACACG,BRCA2,CBE,-0.063817,0.282144,-0.105366,0.492081,0.774597,0.352714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,GGTAAATTAATTTGCACTCT,BRCA2,CBE,0.657471,0.859864,0.688051,0.744574,0.640885,0.673288,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,GGTAAGGAAAGTTTATGGAC,BRCA2,CBE,0.564656,0.607026,0.526379,0.794225,0.556425,0.858420,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,GGTAAGTTAATGTAAACTCA,BRCA2,CBE,0.161711,0.201272,0.335373,0.125419,0.156684,0.062418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13695,13695,TTTGTCCCCCAGCTCCGGAG,Unknown,Unknown,-2.248273,-1.913056,NaN,NaN,NaN,NaN,...,-1.545293,-1.511750,-1.562834,-1.386141,-1.499506,-1.919152,-1.999304,-2.198791,-2.242263,-2.347193
13696,13696,TTTGTGAATAAATGGTAAGT,Unknown,Unknown,0.917868,0.494135,NaN,NaN,NaN,NaN,...,0.421920,0.858094,0.188714,0.680748,0.374610,0.608099,0.479682,0.348705,0.364481,0.599635
13697,13697,TTTGTGGATGGTAAGAATTG,Unknown,Unknown,0.709514,0.769138,NaN,NaN,NaN,NaN,...,0.459944,0.356770,0.464642,0.437727,0.582997,1.051311,0.470501,0.638449,0.360223,0.665164
13698,13698,TTTGTTCTCCACTAGCACCA,Unknown,Unknown,-1.234291,-1.702548,NaN,NaN,NaN,NaN,...,-1.374469,-1.307379,-0.827814,-0.742341,-0.493298,-1.396976,-0.940567,-0.894818,-1.103237,-0.539141
13699,13699,TTTGTTGATGGCCTCTCGGA,Unknown,Unknown,0.528186,0.188317,NaN,NaN,NaN,NaN,...,0.180396,-0.423997,0.355185,0.240905,-0.029683,-0.154475,0.437650,-0.536482,0.568022,0.010610