# RH merge

In [1]:
import numpy as np
import pandas as pd
from dotenv import load_dotenv
import os

load_dotenv()
base_dir = os.getenv("BASE_DIR")

In [ ]:
a=pd.read_csv(os.path.join(base_dir,"3_Counts/RH/RH_BRCA2_processed.csv"))
b=pd.read_csv(os.path.join(base_dir,'3_Counts/RH/RH_BRCA2_processed.csv'))
c=pd.read_csv(os.path.join(base_dir,'3_Counts/RH/RH_MCL1_processed.csv'))
d=pd.read_csv(os.path.join(base_dir,'3_Counts/RH/RH_BCL2L1_processed.csv'))
e=pd.read_csv(os.path.join(base_dir,'3_Counts/RH/RH_PARP1_processed.csv'))

In [10]:
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

In [13]:
merge_BRCA=pd.concat([a, b], ignore_index=True)
merge_2=pd.concat([c, d], ignore_index=True)
merged_RH=pd.concat([merge_BRCA,merge_2,e], ignore_index=True)

merged_RH.to_csv(os.path.join(base_dir,'3_Counts/RH/merge_RH.csv'))

In [31]:
# a.merge(b, on=['Guide','Gene','Editor'],how='outer')

In [24]:
merge_2

,Guide,Gene,Editor,pDNA,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_A1331852_RepA,MELJUSO_A1331852_RepB,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepC
0,AAGAAACCGATGGGACGCCG,Intergenic control,Unknown,8232,1654,1477,1564.0,1603.0,1766,1175,NaN,NaN,NaN,NaN,NaN
1,AGGAATGGAATTAGCGGACC,Intergenic control,Unknown,58089,9880,9246,9540.0,9423.0,6530,6938,NaN,NaN,NaN,NaN,NaN
2,ACTAACAATTAGCGCAGTTG,Intergenic control,Unknown,40478,7836,7969,7831.0,7972.0,6364,6273,NaN,NaN,NaN,NaN,NaN
3,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,65826,13781,12647,13360.0,12265.0,11955,7505,NaN,NaN,NaN,NaN,NaN
4,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,31162,5919,4504,6509.0,4379.0,4487,3186,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,332561,46331,52822,NaN,NaN,46049,48726,49665.0,53164.0,52653.0,56513.0,45511.0
704,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,272366,25939,30133,NaN,NaN,19716,21454,30949.0,31143.0,29537.0,31576.0,24565.0
705,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,337974,47757,53388,NaN,NaN,43296,50076,51898.0,56662.0,54237.0,58747.0,49465.0
706,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,297543,40244,48550,NaN,NaN,38967,39693,47602.0,49196.0,49324.0,50473.0,40460.0
707,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,213898,25199,29586,NaN,NaN,25303,24057,29919.0,30575.0,30256.0,31558.0,23759.0

In [31]:
# merge zscores

a=pd.read_csv(os.path.join(base_dir,"4_Screen_zscores/RH/RH_BRCA2_zscores.csv"))
b=pd.read_csv(os.path.join(base_dir,'4_Screen_zscores/RH/RH_BRCA2_zscores.csv'))
c=pd.read_csv(os.path.join(base_dir,'4_Screen_zscores/RH/RH_MCL1_zscores.csv'))
d=pd.read_csv(os.path.join(base_dir,'4_Screen_zscores/RH/RH_BCL2L1_zscores.csv'))
e=pd.read_csv(os.path.join(base_dir,'4_Screen_zscores/RH/RH_PARP1_zscores.csv'))
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

merge_BRCA_z=pd.concat([a, b], ignore_index=True)
merge_2_z=pd.concat([c, d], ignore_index=True)
merged_RH_z=pd.concat([merge_BRCA_z,merge_2_z,e], ignore_index=True)

merged_RH_z.to_csv(os.path.join(base_dir,'4_Screen_zscores/RH/merge_RH_z.csv'))

In [30]:
# merge LFC

a=pd.read_csv(os.path.join(base_dir,"5_LFC/RH/RH_BRCA2_LFC.csv"))
b=pd.read_csv(os.path.join(base_dir,'5_LFC/RH/RH_BRCA2_LFC.csv'))
c=pd.read_csv(os.path.join(base_dir,'5_LFC/RH/RH_MCL1_LFC.csv'))
d=pd.read_csv(os.path.join(base_dir,'5_LFC/RH/RH_BCL2L1_LFC.csv'))
e=pd.read_csv(os.path.join(base_dir,'5_LFC/RH/RH_PARP1_LFC.csv'))
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

merge_BRCA_LFC=pd.concat([a, b], ignore_index=True)
merge_2_LFC=pd.concat([c, d], ignore_index=True)
merged_RH_LFC=pd.concat([merge_BRCA_LFC,merge_2_LFC,e], ignore_index=True)

merged_RH_LFC.to_csv(os.path.join(base_dir,'5_LFC/RH/merge_RH_z.csv'))

# GR merge

In [36]:
#for counts files better concat
A540=os.path.join(base_dir,'3_Counts/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Processed.csv')
MELJURO=os.path.join(base_dir,'3_Counts/GR/GR_MELJUSO_ABE_Processed.csv')
f=pd.read_csv(A540)
g=pd.read_csv(MELJURO)

f["Gene"] = f["Gene"].fillna("Unknown")
f['Editor']=  f["Editor"].fillna("Unknown")
g["Gene"] = g["Gene"].fillna("Unknown")
g['Editor']=  g["Editor"].fillna("Unknown")
merge_GR=pd.concat([f,g],ignore_index=True)
merge_GR.to_csv(os.path.join(base_dir,'5_LFC/GR/merge_RH.csv'))

In [43]:
#for counts files better concat
A540=os.path.join(base_dir,'5_LFC/GR/GR_A549_ABE_CBE_MELJUSO_CBE_LFC.csv')
MELJURO=os.path.join(base_dir,'5_LFC/GR/GR_MELJUSO_ABE_LFC.csv')
f=pd.read_csv(A540)
g=pd.read_csv(MELJURO)

f["Gene"] = f["Gene"].fillna("Unknown")
f['Editor']=  f["Editor"].fillna("Unknown")
g["Gene"] = g["Gene"].fillna("Unknown")
g['Editor']=  g["Editor"].fillna("Unknown")
merge_GR_lfc=pd.concat([f,g],ignore_index=True)
merge_GR_lfc.to_csv(os.path.join(base_dir,'5_LFC/GR/merge_RH_z.csv'))

In [38]:
pd.concat([f,g],ignore_index=True)

,Guide,Gene,Editor,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_A1331852+S63845_RepC
0,GTTCTACCTTCAGTCCGATG,Intergenic control,Unknown,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,0.368644,0.196900
1,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,0.359094,0.379809
2,GAAAAGTCATCCCACGAAGT,Intergenic control,Unknown,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,0.306998,0.388792
3,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,0.077617,0.087227
4,ACTAACGGCGCATCACCTAA,Intergenic control,Unknown,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,-0.072112,0.017476
...,...,...,...,...,...,...,...,...,...,...,...,...
627,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,0.501937,0.382684
628,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,-0.320942,-0.161255
629,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,0.516765,0.470306
630,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,0.377605,0.374369
631,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,0.151301,0.110477

In [39]:
g.merge(f,on=["Guide","Editor","Gene"])

,Guide,Gene,Editor,MELJUSO_Dropout_RepA_x,MELJUSO_Dropout_RepB_x,MELJUSO_Dropout_RepC_x,MELJUSO_S63845_RepA_x,MELJUSO_S63845_RepB_x,MELJUSO_S63845_RepC_x,MELJUSO_A1331852+S63845_RepA_x,...,MELJUSO_A1331852+S63845_RepC_x,MELJUSO_Dropout_RepA_y,MELJUSO_Dropout_RepB_y,MELJUSO_Dropout_RepC_y,MELJUSO_S63845_RepA_y,MELJUSO_S63845_RepB_y,MELJUSO_S63845_RepC_y,MELJUSO_A1331852+S63845_RepA_y,MELJUSO_A1331852+S63845_RepB_y,MELJUSO_A1331852+S63845_RepC_y
0,GTTCTACCTTCAGTCCGATG,Intergenic control,Unknown,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,...,0.196900,0.132920,-0.030528,-0.045048,0.099922,0.153565,0.194734,0.000964,0.368644,0.196900
1,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,...,0.379809,0.479803,0.427497,0.454357,0.519290,0.520734,0.520995,0.330573,0.359094,0.379809
2,GAAAAGTCATCCCACGAAGT,Intergenic control,Unknown,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,...,0.388792,0.393636,0.239794,0.303593,0.336222,0.356071,0.427228,0.272137,0.306998,0.388792
3,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,...,0.087227,-0.032211,0.070854,0.020622,0.236248,0.162107,0.246087,0.216544,0.077617,0.087227
4,ACTAACGGCGCATCACCTAA,Intergenic control,Unknown,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,...,0.017476,-0.072999,-0.058731,-0.099913,0.111520,0.112130,0.116762,0.037520,-0.072112,0.017476
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,...,0.382684,0.599184,0.547244,0.506038,0.585258,0.597640,0.624796,0.475640,0.501937,0.382684
312,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,...,-0.161255,-0.043106,-0.055632,0.055485,0.129425,0.089573,0.106881,-0.346796,-0.320942,-0.161255
313,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,...,0.470306,0.623108,0.538095,0.551928,0.649974,0.615758,0.655438,0.376997,0.516765,0.470306
314,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,...,0.374369,0.549230,0.592144,0.619536,0.631094,0.659341,0.622404,0.404980,0.377605,0.374369
315,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,...,0.110477,0.316064,0.316692,0.398093,0.433093,0.446326,0.433404,0.275991,0.151301,0.110477