# RH merge

In [2]:
import numpy as np
import pandas as pd

In [2]:
BRCA1='/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/BRCA1/RH_BRCA1_processed.csv'
BRCA2='/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/BRCA2/RH_BRCA2_processed.csv'
MCL1='/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/MCL1/RH_MCL1_processed.csv'
BCL2L1='/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/BCL2L1/RH_BCL2L1_processed.csv'
PARP1='/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/PARP1/RH_PARP1_processed.csv'

In [18]:
a=pd.read_csv(BRCA1)
b=pd.read_csv(BRCA2)
c=pd.read_csv(MCL1)
d=pd.read_csv(BCL2L1)
e=pd.read_csv(PARP1)

In [19]:
a["Gene"] = a["Gene"].fillna("Unknown")
a['Editor']=  a["Editor"].fillna("Unknown")
b["Gene"] = b["Gene"].fillna("Unknown")
b['Editor']=  b["Editor"].fillna("Unknown")
c["Gene"] = c["Gene"].fillna("Unknown")
c['Editor']=  c["Editor"].fillna("Unknown")
d["Gene"] = d["Gene"].fillna("Unknown")
d['Editor']=  d["Editor"].fillna("Unknown")
e["Gene"] = e["Gene"].fillna("Unknown")
e['Editor']=  e["Editor"].fillna("Unknown")

In [ ]:
merge_BRCA=pd.concat([a, b], ignore_index=True)
merge_2=pd.concat([c, d], ignore_index=True)
final_RH=pd.concat([merge_BRCA,merge_2,e], ignore_index=True)
#final_RH.to_csv('/Users/joanacorreia/Desktop/Tese/Processed Tables/RH/merge_RH.csv')

In [31]:
# a.merge(b, on=['Guide','Gene','Editor'],how='outer')

In [24]:
merge_2

,Guide,Gene,Editor,pDNA,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_A1331852_RepA,MELJUSO_A1331852_RepB,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepC
0,AAGAAACCGATGGGACGCCG,Intergenic control,Unknown,8232,1654,1477,1564.0,1603.0,1766,1175,NaN,NaN,NaN,NaN,NaN
1,AGGAATGGAATTAGCGGACC,Intergenic control,Unknown,58089,9880,9246,9540.0,9423.0,6530,6938,NaN,NaN,NaN,NaN,NaN
2,ACTAACAATTAGCGCAGTTG,Intergenic control,Unknown,40478,7836,7969,7831.0,7972.0,6364,6273,NaN,NaN,NaN,NaN,NaN
3,CAATTTGCTTAGGCGACCTG,Intergenic control,Unknown,65826,13781,12647,13360.0,12265.0,11955,7505,NaN,NaN,NaN,NaN,NaN
4,ATATATTTCTAACTCGGAGG,Intergenic control,Unknown,31162,5919,4504,6509.0,4379.0,4487,3186,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,AAGGGGGTGGGAGGGTAGAG,Unknown,Unknown,332561,46331,52822,NaN,NaN,46049,48726,49665.0,53164.0,52653.0,56513.0,45511.0
704,GAGCAGAGAAGGGGGTGGGA,Unknown,Unknown,272366,25939,30133,NaN,NaN,19716,21454,30949.0,31143.0,29537.0,31576.0,24565.0
705,GGAGCAGAGAAGGGGGTGGG,Unknown,Unknown,337974,47757,53388,NaN,NaN,43296,50076,51898.0,56662.0,54237.0,58747.0,49465.0
706,GGTGGAGCAGAGAAGGGGGT,Unknown,Unknown,297543,40244,48550,NaN,NaN,38967,39693,47602.0,49196.0,49324.0,50473.0,40460.0
707,TGGTGGAGCAGAGAAGGGGG,Unknown,Unknown,213898,25199,29586,NaN,NaN,25303,24057,29919.0,30575.0,30256.0,31558.0,23759.0

# GR merge

In [37]:
A540='/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/A549_ABE_CBE_MELJUSO_CBE/GR_A549_ABE_CBE_MELJUSO_CBE_Processed.csv'
MELJURO='/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/MELJUSO_ABE/GR_MELJUSO_ABE_Processed.csv'

In [42]:
f=pd.read_csv(A540)
g=pd.read_csv(MELJURO)

f["Gene"] = f["Gene"].fillna("Unknown")
f['Editor']=  f["Editor"].fillna("Unknown")
g["Gene"] = g["Gene"].fillna("Unknown")
g['Editor']=  g["Editor"].fillna("Unknown")

merge_GR=pd.concat([f,g],ignore_index=True)

In [43]:
merge_GR.to_csv('/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/merge_GR.csv')

In [47]:
merge_GR

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB,MeljusoDO__RepA-Day21,MeljusoDO__RepB-Day21
0,AAAAAACATACCTCAACCCT,Unknown,ABE,6186,7196.0,7384.0,NaN,NaN,NaN,NaN
1,AAAAAACATACCTCAACCCT,Unknown,CBE,6186,7115.0,5185.0,7695.0,11196.0,NaN,NaN
2,AAAAAACTCAACAGCAGTGA,NRAS,ABE,8010,12030.0,11611.0,NaN,NaN,NaN,NaN
3,AAAAAACTCAACAGCAGTGA,NRAS,CBE,8010,10438.0,11090.0,10779.0,18113.0,NaN,NaN
4,AAAAACATACCTCAACCCTT,Unknown,ABE,7427,6941.0,9996.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
17044,TTTGTATCAACTGTCCTTGT,NRAS,ABE,1369,NaN,NaN,NaN,NaN,5694.0,4985.0
17045,TTTGTGGAAGACTGGGACTT,Unknown,ABE,1764,NaN,NaN,NaN,NaN,6020.0,6088.0
17046,TTTGTGGTGTCACCTGAACC,Unknown,ABE,1785,NaN,NaN,NaN,NaN,6222.0,6186.0
17047,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,1982,NaN,NaN,NaN,NaN,6815.0,6320.0
17048,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,1430,NaN,NaN,NaN,NaN,4403.0,3534.0

In [48]:
teste

,Guide,Gene,Editor,pDNA_x,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB,pDNA_y,MeljusoDO__RepA-Day21,MeljusoDO__RepB-Day21
0,AAAAAACATACCTCAACCCT,Unknown,ABE,6186,7196,7384,NaN,NaN,1286.0,5778.0,4657.0
1,AAAAAACATACCTCAACCCT,Unknown,CBE,6186,7115,5185,7695.0,11196.0,NaN,NaN,NaN
2,AAAAAACTCAACAGCAGTGA,NRAS,ABE,8010,12030,11611,NaN,NaN,1895.0,7372.0,6146.0
3,AAAAAACTCAACAGCAGTGA,NRAS,CBE,8010,10438,11090,10779.0,18113.0,NaN,NaN,NaN
4,AAAAACATACCTCAACCCTT,Unknown,ABE,7427,6941,9996,NaN,NaN,1524.0,5725.0,6159.0
...,...,...,...,...,...,...,...,...,...,...,...
11361,TTTGTGGTGTCACCTGAACC,Unknown,CBE,7232,9055,6288,7598.0,11234.0,NaN,NaN,NaN
11362,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,8657,8636,9770,NaN,NaN,1982.0,6815.0,6320.0
11363,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,8657,9148,8581,9986.0,16557.0,NaN,NaN,NaN
11364,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,5534,5668,7111,NaN,NaN,1430.0,4403.0,3534.0
11365,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,CBE,5534,4216,5046,6084.0,8681.0,NaN,NaN,NaN

In [40]:
f

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,AAAAAACATACCTCAACCCT,Unknown,ABE,6186,7196,7384,NaN,NaN
1,AAAAAACATACCTCAACCCT,Unknown,CBE,6186,7115,5185,7695.0,11196.0
2,AAAAAACTCAACAGCAGTGA,NRAS,ABE,8010,12030,11611,NaN,NaN
3,AAAAAACTCAACAGCAGTGA,NRAS,CBE,8010,10438,11090,10779.0,18113.0
4,AAAAACATACCTCAACCCTT,Unknown,ABE,7427,6941,9996,NaN,NaN
...,...,...,...,...,...,...,...,...
11361,TTTGTGGTGTCACCTGAACC,Unknown,CBE,7232,9055,6288,7598.0,11234.0
11362,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,8657,8636,9770,NaN,NaN
11363,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,8657,9148,8581,9986.0,16557.0
11364,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,5534,5668,7111,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,CBE,5534,4216,5046,6084.0,8681.0

In [41]:
g

,Guide,Gene,Editor,pDNA,MeljusoDO__RepA-Day21,MeljusoDO__RepB-Day21
0,AAAAAACATACCTCAACCCT,Unknown,ABE,1286,5778,4657
1,AAAAAACTCAACAGCAGTGA,NRAS,ABE,1895,7372,6146
2,AAAAACATACCTCAACCCTT,Unknown,ABE,1524,5725,6159
3,AAAAAGAAGAACCAGTGGTT,PLK1,ABE,1331,4471,4603
4,AAAAAGCATCCTCCACTCTC,Unknown,ABE,1811,7389,6088
...,...,...,...,...,...,...
5678,TTTGTATCAACTGTCCTTGT,NRAS,ABE,1369,5694,4985
5679,TTTGTGGAAGACTGGGACTT,Unknown,ABE,1764,6020,6088
5680,TTTGTGGTGTCACCTGAACC,Unknown,ABE,1785,6222,6186
5681,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,1982,6815,6320
5682,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,1430,4403,3534

In [45]:
teste=f.merge(g, on=['Guide','Gene','Editor'],how='outer')
nan_counts_per_column = teste.isna().sum()
print(nan_counts_per_column)

Guide                       0
Gene                        0
Editor                      0
pDNA_x                      0
A549_repA                   0
A549_repB                   0
Meljuso_repA             5683
Meljuso_repB             5683
pDNA_y                   5683
MeljusoDO__RepA-Day21    5683
MeljusoDO__RepB-Day21    5683
dtype: int64

In [46]:
nan_counts_per_column = merge_GR.isna().sum()
print(nan_counts_per_column)

Guide                        0
Gene                         0
Editor                       0
pDNA                         0
A549_repA                 5683
A549_repB                 5683
Meljuso_repA             11366
Meljuso_repB             11366
MeljusoDO__RepA-Day21    11366
MeljusoDO__RepB-Day21    11366
dtype: int64

In [3]:
bes= pd.read_excel("/Users/joanacorreia/Desktop/Tese/Original Counts files/Base Editing Screens Samplesheet.xlsx",sheet_name='BE sgRNA library_GR' )

In [7]:
bes

,sgRNA sequence,GeneID,TranscriptID,Isoform,sgRNA Target Sequence Start Pos. (global),Editor,Nucleotide Edits,Amino Acid Edits,Mutation Category,Unnamed: 9,Beagle file,https://drive.google.com/drive/folders/1GaD6i9Ok_CYnoOaGKEVdQN6naH9WiwA-?usp=drive_link
0,CATCGCGGCCCTGGGGACGG,WEE1,ENSG00000166483,ENST00000450114.7,9573917.0,A-G,"-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN,NaN
1,CATCGCGGCCCTGGGGACGG,WEE1,ENSG00000166483,ENST00000450114.7,9573917.0,C-T,NaN,NaN,NaN,NaN,NaN,NaN
2,TCATCGCGGCCCTGGGGACG,WEE1,ENSG00000166483,ENST00000450114.7,9573918.0,A-G,"-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN,NaN
3,TCATCGCGGCCCTGGGGACG,WEE1,ENSG00000166483,ENST00000450114.7,9573918.0,C-T,2T>C,Met1Thr,Missense,NaN,NaN,NaN
4,CTCATCGCGGCCCTGGGGAC,WEE1,ENSG00000166483,ENST00000450114.7,9573919.0,A-G,"-3G>A, -1G>A","(NC), (NC)","UTR, UTR",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
8354,GAAGACCATAACCGCGAGAA,Intergenic control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8355,CACACACTCCTACTTGACAC,Intergenic control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8356,GTGGGCTTAAGCACGCTAAG,Intergenic control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8357,AGCATTTGGATACTCGAGGC,Intergenic control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8358,TCTTACATTCGGCGTTCGCA,Intergenic control,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN