In [1]:
import pandas as pd
from Process import *
import os

In [6]:
!pip install python-dotenv

Defaulting to user installation because normal site-packages is not writeable
Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [2]:
from dotenv import load_dotenv

load_dotenv()
base_dir = os.getenv("BASE_DIR")

# MC

``

In [4]:
df=pd.read_csv(os.path.join(base_dir, "3_Counts/MC/~$MC_readcouns.csv"))
df.sort_values(by='guide')
df=process_MC(df)
df

/var/folders/_b/vg6mlp993fs42rqbm_7nm25h0000gn/T/ipykernel_3968/2719160463.py:1: DtypeWarning: Columns (76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(os.path.join(base_dir, "3_Counts/MC/~$MC_readcouns.csv"))
/Users/joanacorreia/Desktop/BECancerResistome/BECancerResistome/Processing/Process.py:151: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_pivot = df_pivot.fillna("Na")

['exonic' 'splice_essential' 'splice_nonessential' 'intergenic'
 'non_targeting']

,Guide,Gene,Editor,pDNA,H23_Adag_RepA,H23_Adag_RepB,H23_Control_RepA,H23_Control_RepB,H23_Sotor_RepA,H23_Sotor_RepB,...,H_T29_Tram_RepB,P_C9_Control_RepA,P_C9_Control_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,468,627,345,244,337,311,338,...,369,458,469,323,736,Na,401,611,663,593
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,468,226,372,416,330,380,339,...,470,446,363,418,622,139,425,354,653,376
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,720,522,569,859,560,482,579,...,516,1006,923,733,912,Na,826,758,1190,840
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,720,654,584,756,536,887,453,...,433,601,777,364,476,161,701,933,1164,822
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,965,1090,551,1760,585,557,738,...,736,1519,1083,965,928,Na,1021,860,1887,1239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45177,TTTTGTGCCCTGGACAAAGT,BRAF,CBE,1263,1238,1250,1758,1346,1598,1236,...,1041,1930,1790,1435,1813,424,1373,1258,1962,1637
45178,TTTTGTGTGACAAAGCGTAA,EGFR,ABE,1175,1056,1080,582,1073,1718,1163,...,795,1244,1441,1162,1121,Na,1359,1081,1739,1655
45179,TTTTGTGTGACAAAGCGTAA,EGFR,CBE,1175,718,1229,1260,1195,1009,903,...,858,1521,1372,1098,1181,586,1431,1082,1450,1284
45180,TTTTGTTTCCTTGCTCACTG,BRAF,ABE,1434,1948,1095,1906,1243,1479,1529,...,1003,2159,1899,1435,2606,Na,1997,1847,2434,1680
45181,TTTTGTTTCCTTGCTCACTG,BRAF,CBE,1434,1673,1600,1428,1539,1516,1268,...,1092,1820,1974,1517,1179,1182,1652,1661,2305,1808

In [6]:
df.to_csv(os.path.join(base_dir,"3_Counts/MC/MC_processed.csv"), index=False)

In [7]:
lfc_data,zscores=LFC_Z(df,'MC_processed')

In [10]:
lfc_data.to_csv(os.path.join(base_dir,"5_LFC/MC/MC_LFC.csv"), index=False)
zscores.to_csv(os.path.join(base_dir,"4_Screen_zscores/MC/MC_zscores.csv"), index=False)

# RH

In [51]:
df=pd.read_excel(os.path.join(base_dir, "3_Counts/RH/counts_MCL1_BCL2L1.xlsx"),header=None, sheet_name='BCL2L1')
#df has all unique guides
df=process_RH(df)
df

/Users/joanacorreia/Desktop/BECancerResistome/BECancerResistome/Processing/Process.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'sgRNA sequence': 'Guide'}, inplace=True)
/Users/joanacorreia/Desktop/BECancerResistome/BECancerResistome/Processing/Process.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'GeneID': 'Gene'}, inplace=True)
/Users/joanacorreia/Desktop/BECancerResistome/BECancerResistome/Processing/Process.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected['Editor'] = df2_selected['Editor'].replace({'A-G': 'ABE', 'C-T': 'CBE'})

,Guide,Gene,Editor,pDNA,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_A1331852+S63845_RepC
0,GTTCTACCTTCAGTCCGATG,Intergenic control,NaN,224259,23704,25187,23975,25092,25507,27741,21356,29715,26616
1,CAATTTGCTTAGGCGACCTG,Intergenic control,NaN,463619,60181,68535,67101,70607,69317,72972,57257,60991,63307
2,GAAAAGTCATCCCACGAAGT,Intergenic control,NaN,297159,36654,39250,39250,39557,39301,43643,35046,37586,40857
3,ATATATTTCTAACTCGGAGG,Intergenic control,NaN,294734,28251,35178,32790,36454,33737,37868,33269,31357,32160
4,ACTAACGGCGCATCACCTAA,Intergenic control,NaN,199298,18647,22008,20609,22490,21979,23274,19534,18939,20614
...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,AAGGGGGTGGGAGGGTAGAG,NaN,NaN,332561,46331,52822,49665,53164,52653,56513,46049,48726,45511
312,GAGCAGAGAAGGGGGTGGGA,NaN,NaN,272366,25939,30133,30949,31143,29537,31576,19716,21454,24565
313,GGAGCAGAGAAGGGGGTGGG,NaN,NaN,337974,47757,53388,51898,56662,54237,58747,43296,50076,49465
314,GGTGGAGCAGAGAAGGGGGT,NaN,NaN,297543,40244,48550,47602,49196,49324,50473,38967,39693,40460
315,TGGTGGAGCAGAGAAGGGGG,NaN,NaN,213898,25199,29586,29919,30575,30256,31558,25303,24057,23759

In [32]:
df.to_csv(os.path.join(base_dir,"3_Counts/RH/RH_BCL2L1_processed.csv"), index=False)

In [52]:
lfc_data,zscores=LFC_Z(df,'RH_BCL2L1_processed')
lfc_data

,Guide,Gene,Editor,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_S63845_RepA,MELJUSO_S63845_RepB,MELJUSO_S63845_RepC,MELJUSO_A1331852+S63845_RepA,MELJUSO_A1331852+S63845_RepB,MELJUSO_A1331852+S63845_RepC
0,GTTCTACCTTCAGTCCGATG,Intergenic control,NaN,-3.241909,-3.154364,-3.225509,-3.159815,-3.136151,-3.015029,-3.392391,-2.915860,-3.074752
1,CAATTTGCTTAGGCGACCTG,Intergenic control,NaN,-2.945539,-2.758009,-2.788515,-2.715039,-2.741641,-2.667508,-3.017394,-2.926251,-2.872483
2,GAAAAGTCATCCCACGAAGT,Intergenic control,NaN,-3.019158,-2.920439,-2.920439,-2.909199,-2.918565,-2.767385,-3.083877,-2.982934,-2.862549
3,ATATATTTCTAACTCGGAGG,Intergenic control,NaN,-3.382993,-3.066632,-3.168047,-3.015230,-3.126972,-2.960329,-3.147125,-3.232513,-3.196034
4,ACTAACGGCGCATCACCTAA,Intergenic control,NaN,-3.417842,-3.178769,-3.273518,-3.147515,-3.180671,-3.098081,-3.350801,-3.395426,-3.273168
...,...,...,...,...,...,...,...,...,...,...,...,...
311,AAGGGGGTGGGAGGGTAGAG,NaN,NaN,-2.843542,-2.654385,-2.743293,-2.645075,-2.659008,-2.556943,-2.852350,-2.770830,-2.869304
312,GAGCAGAGAAGGGGGTGGGA,NaN,NaN,-3.392302,-3.176088,-3.137541,-3.128526,-3.204908,-3.108606,-3.788040,-3.666166,-3.470817
313,GGAGCAGAGAAGGGGGTGGG,NaN,NaN,-2.823102,-2.662302,-2.703138,-2.576438,-2.639541,-2.524305,-2.964578,-2.754696,-2.772407
314,GGTGGAGCAGAGAAGGGGGT,NaN,NaN,-2.886222,-2.615530,-2.643979,-2.596461,-2.592712,-2.559491,-2.932741,-2.906110,-2.878499
315,TGGTGGAGCAGAGAAGGGGG,NaN,NaN,-3.085434,-2.853894,-2.837748,-2.806458,-2.821589,-2.760806,-3.079492,-3.152341,-3.170323

In [34]:
lfc_data.to_csv(os.path.join(base_dir,"5_LFC/RH/RH_BCL2L1_LFC.csv"), index=False)
zscores.to_csv(os.path.join(base_dir,"4_Screen_zscores/RH/RH_BCL2L1_zscores.csv"), index=False)

In [ ]:
from Process import process_RH, RH_LFC_Z
df=process_RH(df,subset='PARP1_set') #only CBE editors and Nan, no ABE
df.sort_values(by="Gene")
#df.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_processed.csv", index=False)

,Guide,Gene,Editor,pDNA,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,1214,685,658,511,641,506,382,581,472,747,1096,854,842
329,CGGCGTACAGCCTATCCGCG,Intergenic control,NaN,783,465,408,390,340,249,209,362,327,559,470,640,687
328,GGGCTCAGGAATATCACGTC,Intergenic control,NaN,1200,979,1193,851,853,603,731,671,813,986,1286,757,1362
327,GGGGAGTTTCAGCCCAACGA,Intergenic control,NaN,1068,627,667,600,458,413,405,506,507,778,917,675,684
326,CTCCGAGTGGGAACTAACAC,Intergenic control,NaN,935,744,857,679,704,841,694,678,688,803,934,848,1126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449,TTTGTCCCCCAGCTCCGGAG,NaN,NaN,1183,238,294,293,260,236,216,248,186,337,287,230,243
11450,TTTGTGAATAAATGGTAAGT,NaN,NaN,871,879,749,627,702,482,530,508,581,908,816,719,919
11451,TTTGTGGATGGTAAGAATTG,NaN,NaN,1094,993,1084,804,670,711,578,715,940,1135,1195,901,1197
11452,TTTGTTCTCCACTAGCACCA,NaN,NaN,1508,509,418,410,371,462,401,548,320,748,731,552,846
11453,TTTGTTGATGGCCTCTCGGA,NaN,NaN,1515,1254,1113,957,605,924,714,709,654,1545,888,1400,1153

In [ ]:
df_lfc, df_zscores=RH_LFC_Z(df,"RH_PARP1_processed")

In [5]:
df_zscores

,Guide,Gene,Editor,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Dropout_RepC,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_Cisplatin_RepA,MELJUSO_Cisplatin_RepB,MELJUSO_Cisplatin_RepC,MELJUSO_Talazoparib_RepA,MELJUSO_Talazoparib_RepB,MELJUSO_Talazoparib_RepC
0,AAAACATGGAGTTGTTCCTT,BRCA1,CBE,-0.067902,-0.191317,-0.028048,-0.769246,-0.908601,-0.457504,0.489469,0.052373,0.327700,-0.444731,-0.591862,-0.572317
1,GGAGCTTTACCTTTCTGTCC,BRCA1,CBE,0.721139,0.660436,0.578326,0.485537,0.490892,0.554888,0.528246,0.515365,0.670153,0.717140,0.514648,0.593413
2,GGATGACCTAGAAAGATAAA,BRCA1,CBE,-2.993899,-2.847287,-3.166242,-1.605330,-1.119865,-1.826955,-3.363738,-3.452971,-3.826157,-1.769763,-2.108277,-2.015196
3,GGATGCTTACAATTACTTCC,BRCA1,CBE,-0.360763,-0.569328,-0.300821,-0.176436,-0.478690,-0.378277,-0.727600,-0.870004,-0.689082,-0.352784,-0.516000,-0.444177
4,GGCAGAAGAGTCACTTATGA,BRCA1,CBE,0.211217,0.194566,0.302843,0.226914,-0.209703,0.017608,0.081403,-0.006661,-0.033784,0.198334,0.176083,0.140673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,TTCTCAAACAATTTAATTTC,NaN,NaN,0.108962,0.061859,0.074224,0.209171,0.409529,0.065121,0.205099,0.457144,0.069542,0.398917,0.302376,0.276092
738,TTGAATGCTCTTTCCTTCCT,NaN,NaN,0.682309,0.747108,0.661413,0.855409,0.918213,0.691848,0.884119,1.082500,0.703684,0.804584,0.938252,0.713367
739,TTGCTTAAGATATCAGTGTT,NaN,NaN,0.761209,0.842240,0.721081,0.935271,1.088162,1.048669,1.132066,1.096573,1.099279,1.090041,1.208691,1.149188
740,TTGTGTCCTCCCTCTCTGAC,NaN,NaN,0.445878,0.378574,0.361259,0.196193,0.263135,0.004163,0.506210,0.528410,0.291991,0.191170,0.452933,0.206297
741,TTGTTAAGTCTTAGTCATTA,NaN,NaN,0.332411,0.397114,0.392667,0.241393,0.492657,0.612475,0.522443,0.426836,0.602131,0.386305,0.473161,0.755573

In [51]:
df_lfc.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_Zscores.csv", index=False)

# GR

In [41]:
import pandas as pd
#/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-MELJUSO_ABE.txt
#"/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-A549_ABE_CBE_MELJUSO_CBE.txt
df=pd.read_csv(os.path.join(base_dir,"3_Counts/GR/counts-MELJUSO_ABE.txt"))
df.sort_values(by="Construct Barcode") #all unique guides

,Construct Barcode,Construct IDs,Meljuso_ABE_DO_RepA-Day21,Meljuso_ABE_DO_RepB-Day21,CP1965 pDNA
2267,AAAAAACATACCTCAACCCT,ENSG00000149554,5778,4657,1286
2732,AAAAAACTCAACAGCAGTGA,ENSG00000213281,7372,6146,1895
2268,AAAAACATACCTCAACCCTT,ENSG00000149554,5725,6159,1524
4690,AAAAAGAAGAACCAGTGGTT,ENSG00000166851,4471,4603,1331
4059,AAAAAGCATCCTCCACTCTC,ENSG00000133703,7389,6088,1811
...,...,...,...,...,...
2783,TTTGTATCAACTGTCCTTGT,ENSG00000213281,5694,4985,1369
2006,TTTGTGGAAGACTGGGACTT,ENSG00000149554,6020,6088,1764
3446,TTTGTGGTGTCACCTGAACC,ENSG00000170836,6222,6186,1785
3894,TTTGTGTCTACTGTTCTAGA,ENSG00000133703,6815,6320,1982
5636,TTTGTTACCTTATCGGCCAC,ENSG00000138160,4403,3534,1430

In [49]:
from Process import process_GR
df=process_GR(df)
df
df.to_csv(os.path.join(base_dir,"3_Counts/GR/GR_MELJUSO_ABE_Processed.csv"), index=False)

In [46]:
df

,Guide,Gene,Editor,pDNA,MeljusoDO__RepA-Day21,MeljusoDO__RepB-Day21
0,AAAAAACATACCTCAACCCT,NaN,ABE,1286,5778,4657
1,AAAAAACTCAACAGCAGTGA,NRAS,ABE,1895,7372,6146
3,AAAAACATACCTCAACCCTT,NaN,ABE,1524,5725,6159
4,AAAAAGAAGAACCAGTGGTT,PLK1,ABE,1331,4471,4603
6,AAAAAGCATCCTCCACTCTC,NaN,ABE,1811,7389,6088
...,...,...,...,...,...,...
10081,TTTGTATCAACTGTCCTTGT,NRAS,ABE,1369,5694,4985
10083,TTTGTGGAAGACTGGGACTT,NaN,ABE,1764,6020,6088
10084,TTTGTGGTGTCACCTGAACC,NaN,ABE,1785,6222,6186
10085,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,1982,6815,6320
10089,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,1430,4403,3534

In [47]:
df_lfc, df_zscores=LFC_Z(df,"GR_MELJUSO_ABE_Processed")

In [50]:
df_zscores

,Guide,Gene,Editor,MeljusoDO__RepA-Day21,MeljusoDO__RepB-Day21
0,AAAAAACATACCTCAACCCT,NaN,ABE,1.197063,0.766154
1,AAAAAACTCAACAGCAGTGA,NRAS,ABE,0.680350,0.367874
3,AAAAACATACCTCAACCCTT,NaN,ABE,0.554419,1.163551
4,AAAAAGAAGAACCAGTGGTT,PLK1,ABE,0.152552,0.599580
6,AAAAAGCATCCTCCACTCTC,NaN,ABE,0.851410,0.497558
...,...,...,...,...,...
10081,TTTGTATCAACTGTCCTTGT,NRAS,ABE,0.919956,0.786243
10083,TTTGTGGAAGACTGGGACTT,NaN,ABE,0.209844,0.592666
10084,TTTGTGGTGTCACCTGAACC,NaN,ABE,0.285896,0.607643
10085,TTTGTGTCTACTGTTCTAGA,KRAS,ABE,0.236999,0.306528
10089,TTTGTTACCTTATCGGCCAC,Panlethal splice donor,ABE,-0.160032,-0.616037

In [48]:
lfc_data.to_csv(os.path.join(base_dir,"5_lfc/GR/GR_MELJUSO_ABE_LFC.csv"), index=False)
zscores.to_csv(os.path.join(base_dir,"4_Screen_zscores/GR/GR_MELJUSO_ABE_zscores.csv"), index=False)