In [1]:
import pandas as pd
from Process import *

# MC

In [2]:
df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/MC/~$MC_readcouns.csv")
df.sort_values(by='guide')
df=process_MC(df)

/var/folders/_b/vg6mlp993fs42rqbm_7nm25h0000gn/T/ipykernel_4229/1825216120.py:1: DtypeWarning: Columns (76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/MC/~$MC_readcouns.csv")
/Users/joanacorreia/Desktop/Tese_Git/BECancerResistome/BECancerResistome/Processing/Process.py:200: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_pivot = df_pivot.fillna("Na")

In [3]:
df.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/MC/MC_processed.csv", index=False)

In [4]:
df,lfc_data,zscores=process_all(df,"MC")
df

TypeError: process_all() missing 1 required positional argument: 'subset'

In [5]:
(lfc_data,df_zscores)=RH_LFC_Z(df,"MC_processed")

In [9]:
lfc_data.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/MC/MC_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/MC/MC_zscores.csv", index=False)

In [8]:
df_zscores

,Guide,Gene,Editor,H23_Adag_RepA,H23_Adag_RepB,H23_Sotor_RepA,H23_Sotor_RepB,H23_T0_RepA,H23_T0_RepB,H_T29_Deb_Cet_RepA,...,H_T29_T0_RepB,H_T29_Tram_RepA,H_T29_Tram_RepB,P_C9_Gefit_RepA,P_C9_Gefit_RepB,P_C9_Gefit_RepC,P_C9_Osim_RepA,P_C9_Osim_RepB,P_C9_T0_RepA,P_C9_T0_RepB
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,2.207324,0.402861,0.380062,0.498358,0.679475,-0.234903,-0.376278,...,-0.734241,-0.689801,0.240439,-0.370762,1.908978,NaN,-0.488552,1.837751,-0.158499,-0.000764
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,-1.449741,0.918920,-0.479678,0.626708,1.157473,0.264743,1.192417,...,0.468737,0.893703,2.496363,0.562802,2.152187,0.633014,-0.098675,0.476921,-0.139716,-0.328849
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,-1.188256,0.362693,-1.739719,0.661547,-0.935847,-1.540695,0.036072,...,-1.243106,0.548338,-1.459784,-0.265151,0.625855,NaN,-0.785432,-0.331351,-0.492798,-0.541818
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,-0.355967,0.737102,0.167383,-0.420221,-0.166197,0.000072,-0.607708,...,0.047498,-1.650291,-0.109189,-0.871263,-0.700061,-0.462142,0.832627,1.455213,0.324469,-0.294009
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,-1.144441,-0.043888,-3.221753,1.729673,-2.269742,0.380462,0.423973,...,0.068710,1.035790,0.660678,-0.716366,0.230420,NaN,-1.708553,-0.489586,-0.411487,-0.165079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45177,TTTTGTGCCCTGGACAAAGT,BRAF,CBE,-0.841507,-0.119980,-0.492832,0.024459,-0.545747,-0.910439,-0.263816,...,-0.438185,0.164489,-0.379012,-0.199170,0.694581,-0.228893,-1.447168,-1.064631,-0.744056,-0.533870
45178,TTTTGTGTGACAAAGCGTAA,EGFR,ABE,1.390007,0.312096,2.553973,0.915124,0.522594,-0.568829,-0.193819,...,-0.864846,0.089058,-0.963291,0.551462,-0.038006,NaN,0.531138,-0.757486,-0.215732,-0.158617
45179,TTTTGTGTGACAAAGCGTAA,EGFR,CBE,-1.340372,0.427779,-0.820609,-1.022415,-0.356682,-0.463192,0.281531,...,0.446262,-0.221084,1.179719,-0.296102,0.242962,0.821810,-0.157905,-0.522281,-0.850626,-0.495864
45180,TTTTGTTTCCTTGCTCACTG,BRAF,ABE,0.037051,-0.403228,-0.902262,1.595037,-1.235673,-0.016791,0.799449,...,-1.422284,1.016320,-2.068058,-0.568062,1.538046,NaN,-0.236400,0.464143,-0.572432,-0.588536
45181,TTTTGTTTCCTTGCTCACTG,BRAF,CBE,0.359126,0.485873,-0.091158,-0.558137,-0.487569,-0.699294,-0.308453,...,-0.297554,-1.331969,-0.115764,0.176681,-0.771864,1.423653,-0.323313,-0.217585,-0.379419,-0.531391

# RH

In [2]:
df=pd.read_excel("/Users/joanacorreia/Desktop/Tese/Original Counts files/RH/counts_PARP1.xlsx",header=None, sheet_name='BE3_HAP1')
#df has all unique guides

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Cell line,pDNA,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1
1,Condition,pDNA,Dropout,Dropout,Niraparib,Niraparib,Olaparib,Olaparib,Rucaparib,Rucaparib,Talazoparib,Talazoparib,Veliparib,Veliparib
2,sgRNA sequence,pDNA,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB
3,AAAAAACAAAGAGGTTAAGT,637,248,295,453,201,271,301,434,205,653,471,556,419
4,AAAAAACCAAATCGCCACGT,1214,685,658,511,641,506,382,581,472,747,1096,854,842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11452,TTTGTCCCCCAGCTCCGGAG,1183,238,294,293,260,236,216,248,186,337,287,230,243
11453,TTTGTGAATAAATGGTAAGT,871,879,749,627,702,482,530,508,581,908,816,719,919
11454,TTTGTGGATGGTAAGAATTG,1094,993,1084,804,670,711,578,715,940,1135,1195,901,1197
11455,TTTGTTCTCCACTAGCACCA,1508,509,418,410,371,462,401,548,320,748,731,552,846
11456,TTTGTTGATGGCCTCTCGGA,1515,1254,1113,957,605,924,714,709,654,1545,888,1400,1153

In [4]:
df,lfc_data,zscores=process_all(df,"RH",subset='PARP1_set')

/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'sgRNA sequence': 'Guide'}, inplace=True)
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'GeneID': 'Gene'}, inplace=True)
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected['Editor'] = df2_selected['Editor'].replace({'A-G': 'ABE', 'C-T': 'CBE'})

In [ ]:
from Process import process_RH, RH_LFC_Z
df=process_RH(df,subset='PARP1_set') #only CBE editors and Nan, no ABE
df.sort_values(by="Gene")
#df.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_processed.csv", index=False)

,Guide,Gene,Editor,pDNA,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,1214,685,658,511,641,506,382,581,472,747,1096,854,842
329,CGGCGTACAGCCTATCCGCG,Intergenic control,NaN,783,465,408,390,340,249,209,362,327,559,470,640,687
328,GGGCTCAGGAATATCACGTC,Intergenic control,NaN,1200,979,1193,851,853,603,731,671,813,986,1286,757,1362
327,GGGGAGTTTCAGCCCAACGA,Intergenic control,NaN,1068,627,667,600,458,413,405,506,507,778,917,675,684
326,CTCCGAGTGGGAACTAACAC,Intergenic control,NaN,935,744,857,679,704,841,694,678,688,803,934,848,1126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449,TTTGTCCCCCAGCTCCGGAG,NaN,NaN,1183,238,294,293,260,236,216,248,186,337,287,230,243
11450,TTTGTGAATAAATGGTAAGT,NaN,NaN,871,879,749,627,702,482,530,508,581,908,816,719,919
11451,TTTGTGGATGGTAAGAATTG,NaN,NaN,1094,993,1084,804,670,711,578,715,940,1135,1195,901,1197
11452,TTTGTTCTCCACTAGCACCA,NaN,NaN,1508,509,418,410,371,462,401,548,320,748,731,552,846
11453,TTTGTTGATGGCCTCTCGGA,NaN,NaN,1515,1254,1113,957,605,924,714,709,654,1545,888,1400,1153

In [ ]:
df_lfc, df_zscores=RH_LFC_Z(df,"RH_PARP1_processed")

In [5]:
df_zscores

,Guide,Gene,Editor,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Dropout_RepC,MELJUSO_Dropout_RepA,MELJUSO_Dropout_RepB,MELJUSO_Dropout_RepC,MELJUSO_Cisplatin_RepA,MELJUSO_Cisplatin_RepB,MELJUSO_Cisplatin_RepC,MELJUSO_Talazoparib_RepA,MELJUSO_Talazoparib_RepB,MELJUSO_Talazoparib_RepC
0,AAAACATGGAGTTGTTCCTT,BRCA1,CBE,-0.067902,-0.191317,-0.028048,-0.769246,-0.908601,-0.457504,0.489469,0.052373,0.327700,-0.444731,-0.591862,-0.572317
1,GGAGCTTTACCTTTCTGTCC,BRCA1,CBE,0.721139,0.660436,0.578326,0.485537,0.490892,0.554888,0.528246,0.515365,0.670153,0.717140,0.514648,0.593413
2,GGATGACCTAGAAAGATAAA,BRCA1,CBE,-2.993899,-2.847287,-3.166242,-1.605330,-1.119865,-1.826955,-3.363738,-3.452971,-3.826157,-1.769763,-2.108277,-2.015196
3,GGATGCTTACAATTACTTCC,BRCA1,CBE,-0.360763,-0.569328,-0.300821,-0.176436,-0.478690,-0.378277,-0.727600,-0.870004,-0.689082,-0.352784,-0.516000,-0.444177
4,GGCAGAAGAGTCACTTATGA,BRCA1,CBE,0.211217,0.194566,0.302843,0.226914,-0.209703,0.017608,0.081403,-0.006661,-0.033784,0.198334,0.176083,0.140673
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,TTCTCAAACAATTTAATTTC,NaN,NaN,0.108962,0.061859,0.074224,0.209171,0.409529,0.065121,0.205099,0.457144,0.069542,0.398917,0.302376,0.276092
738,TTGAATGCTCTTTCCTTCCT,NaN,NaN,0.682309,0.747108,0.661413,0.855409,0.918213,0.691848,0.884119,1.082500,0.703684,0.804584,0.938252,0.713367
739,TTGCTTAAGATATCAGTGTT,NaN,NaN,0.761209,0.842240,0.721081,0.935271,1.088162,1.048669,1.132066,1.096573,1.099279,1.090041,1.208691,1.149188
740,TTGTGTCCTCCCTCTCTGAC,NaN,NaN,0.445878,0.378574,0.361259,0.196193,0.263135,0.004163,0.506210,0.528410,0.291991,0.191170,0.452933,0.206297
741,TTGTTAAGTCTTAGTCATTA,NaN,NaN,0.332411,0.397114,0.392667,0.241393,0.492657,0.612475,0.522443,0.426836,0.602131,0.386305,0.473161,0.755573

In [51]:
df_lfc.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_Zscores.csv", index=False)

# GR

In [6]:
import pandas as pd
#/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-MELJUSO_ABE.txt
#"/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-A549_ABE_CBE_MELJUSO_CBE.txt
df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-A549_ABE_CBE_MELJUSO_CBE.txt")
df.sort_values(by="Construct Barcode") #all unique guides

,Construct Barcode,Construct IDs,A549_ABE_repA,A549_ABE_repB,A549_CBE_repA,A549_CBE_repB,Meljuso_CBE_repA,Meljuso_CBE_repB,pDNA_CP1965
2267,AAAAAACATACCTCAACCCT,ENSG00000149554,7196,7384,7115,5185,7695,11196,6186
2732,AAAAAACTCAACAGCAGTGA,ENSG00000213281,12030,11611,10438,11090,10779,18113,8010
2268,AAAAACATACCTCAACCCTT,ENSG00000149554,6941,9996,8747,7866,8759,11528,7427
4690,AAAAAGAAGAACCAGTGGTT,ENSG00000166851,7849,8036,5563,7116,7171,11166,5380
4059,AAAAAGCATCCTCCACTCTC,ENSG00000133703,9682,9476,7024,6181,8963,13702,7379
...,...,...,...,...,...,...,...,...,...
2783,TTTGTATCAACTGTCCTTGT,ENSG00000213281,9864,8046,7473,6704,8376,12561,6030
2006,TTTGTGGAAGACTGGGACTT,ENSG00000149554,10202,9902,10802,8152,9347,14213,8113
3446,TTTGTGGTGTCACCTGAACC,ENSG00000170836,9799,9639,9055,6288,7598,11234,7232
3894,TTTGTGTCTACTGTTCTAGA,ENSG00000133703,8636,9770,9148,8581,9986,16557,8657
5636,TTTGTTACCTTATCGGCCAC,ENSG00000138160,5668,7111,4216,5046,6084,8681,5534

In [7]:
from Process import process_GR,GR_LFC_Z
df=process_GR(df)
df
#df.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Processed.csv", index=False)

Warning: Some reordered columns not found in DataFrame.

/Users/joanacorreia/Desktop/Tese_Git/BECancerResistome/BECancerResistome/Processing/Process.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'sgRNA sequence': 'Guide'}, inplace=True)
/Users/joanacorreia/Desktop/Tese_Git/BECancerResistome/BECancerResistome/Processing/Process.py:138: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected['Editor'] = df2_selected['Editor'].replace({'A-G': 'ABE', 'C-T': 'CBE'})

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,8657,9148,8581,9986.0,16557.0
1,TGTAGGAATCCTGAGAAGGG,KRAS,ABE,8189,6595,4856,NaN,NaN
2,TGTAGGAATCCTGAGAAGGG,KRAS,CBE,8189,6356,6687,7986.0,12115.0
3,GATGTACCTATGGTCCTAGT,KRAS,CBE,6649,6762,6013,8186.0,13191.0
4,ACACAAAGAAAGCCCTCCCC,KRAS,CBE,4676,6117,5804,6323.0,9556.0
...,...,...,...,...,...,...,...,...
11361,TTTGTGGAAGACTGGGACTT,NaN,CBE,8113,10802,8152,9347.0,14213.0
11362,TTTGTGGTGTCACCTGAACC,NaN,ABE,7232,9799,9639,NaN,NaN
11363,TTTGTGGTGTCACCTGAACC,NaN,CBE,7232,9055,6288,7598.0,11234.0
11364,TTTGTTACCTTATCGGCCAC,NaN,ABE,5534,5668,7111,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,NaN,CBE,5534,4216,5046,6084.0,8681.0

In [9]:
df_lfc, df_zscores=RH_LFC_Z(df,"GR_A549_ABE_CBE_MELJUSO_CBE_Pro")

In [10]:
df_zscores

,Guide,Gene,Editor,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,-0.600886,-0.470379,-0.107572,0.370862
1,TGTAGGAATCCTGAGAAGGG,KRAS,ABE,-1.906669,-2.699755,NaN,NaN
2,TGTAGGAATCCTGAGAAGGG,KRAS,CBE,-2.084100,-1.311402,-0.914996,-0.850446
3,GATGTACCTATGGTCCTAGT,KRAS,CBE,-0.785068,-0.868404,0.205637,0.544985
4,ACACAAAGAAAGCCCTCCCC,KRAS,CBE,0.425128,0.505607,0.656548,0.685884
...,...,...,...,...,...,...,...
11361,TTTGTGGAAGACTGGGACTT,NaN,CBE,0.510003,-0.411304,-0.113483,-0.046506
11362,TTTGTGGTGTCACCTGAACC,NaN,ABE,0.594114,0.814638,NaN,NaN
11363,TTTGTGGTGTCACCTGAACC,NaN,CBE,0.214535,-1.039077,-0.556912,-0.618492
11364,TTTGTTACCTTATCGGCCAC,NaN,ABE,-0.751072,0.655899,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,NaN,CBE,-2.173569,-0.832689,-0.338718,-0.571973

In [15]:
df_zscores

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,NaN,-0.600912,-0.470400,-0.107582,0.370895
1,TGTAGGAATCCTGAGAAGGG,KRAS,ABE,NaN,-1.906752,-2.699874,NaN,NaN
2,TGTAGGAATCCTGAGAAGGG,KRAS,CBE,NaN,-2.084191,-1.311460,-0.915076,-0.850521
3,GATGTACCTATGGTCCTAGT,KRAS,CBE,NaN,-0.785102,-0.868443,0.205655,0.545033
4,ACACAAAGAAAGCCCTCCCC,KRAS,CBE,NaN,0.425147,0.505630,0.656606,0.685945
...,...,...,...,...,...,...,...,...
11361,TTTGTGGAAGACTGGGACTT,NaN,CBE,NaN,0.510026,-0.411322,-0.113493,-0.046510
11362,TTTGTGGTGTCACCTGAACC,NaN,ABE,NaN,0.594140,0.814674,NaN,NaN
11363,TTTGTGGTGTCACCTGAACC,NaN,CBE,NaN,0.214545,-1.039122,-0.556961,-0.618546
11364,TTTGTTACCTTATCGGCCAC,NaN,ABE,NaN,-0.751105,0.655928,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,NaN,CBE,NaN,-2.173665,-0.832726,-0.338747,-0.572023

In [15]:
df_lfc.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Zscores.csv", index=False)