In [1]:
import pandas as pd
from Process import *

# MC

In [3]:
df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/MC/~$MC_readcouns.csv")
df.sort_values(by='guide')

/var/folders/_b/vg6mlp993fs42rqbm_7nm25h0000gn/T/ipykernel_2503/3955121970.py:1: DtypeWarning: Columns (76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/MC/~$MC_readcouns.csv")

,guide,Gene,plasmid_reads,H23_CBE_T0_exp1_reads,H23_ABE_T0_exp1_reads,H23_CBE_Sotor_exp1_reads,H23_ABE_Sotor_exp1_reads,H23_CBE_Control_exp1_reads,H23_ABE_Control_exp1_reads,H23_CBE_Adag_exp1_reads,...,Gene_ID,Transcript_ID,Exon_ID,G_guide,sgRNA_type,polyT,off_target_summary,strand,Twist_oligo,Twist_oligo_length
1,AAAAAAAAAAACTAAGAGTT,KRAS,468,756,364,380,311,416,244,226,...,ENSG00000133703,ENST00000311936,ENSE00002456976,GAAAAAAAAAACTAAGAGTT,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGAAAAAAAAAACTAAGAGTTgt...,69
5,AAAAAAAAAAGTAAGCTTCA,KRAS,720,794,656,887,482,756,859,654,...,ENSG00000133703,ENST00000311936,ENSE00002456976,GAAAAAAAAAGTAAGCTTCA,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGAAAAAAAAAGTAAGCTTCAgt...,69
7,AAAAAAAAAATCAATGGTGG,BCL2,965,1333,774,871,557,1116,1760,1225,...,ENSG00000171791,ENST00000333681,ENSE00001316245,GAAAAAAAAATCAATGGTGG,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGAAAAAAAAATCAATGGTGGgt...,69
8,AAAAAAAAAATTAATGTCTT,KRAS,654,610,387,696,832,896,531,570,...,ENSG00000133703,ENST00000311936,ENSE00002456976,GAAAAAAAAATTAATGTCTT,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGAAAAAAAAATTAATGTCTTgt...,69
9,AAAAAAAAACTAAGAGTTTG,KRAS,743,1128,513,919,796,789,315,536,...,ENSG00000133703,ENST00000311936,ENSE00002456976,GAAAAAAAACTAAGAGTTTG,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGAAAAAAAACTAAGAGTTTGgt...,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22168,TTTTGTCCTAATATATACAT,KRAS,661,852,625,524,648,844,679,632,...,ENSG00000133703,ENST00000311936,ENSE00002456976,GTTTGTCCTAATATATACAT,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGTTTGTCCTAATATATACATgt...,69
22171,TTTTGTGCAAGGAGGCTCAC,PIK3CA,1461,1870,1971,1542,1881,2236,2394,1677,...,ENSG00000121879,ENST00000263967,ENSE00001139987,GTTTGTGCAAGGAGGCTCAC,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGTTTGTGCAAGGAGGCTCACgt...,69
22173,TTTTGTGCCCTGGACAAAGT,BRAF,1263,1578,857,1598,2136,1758,2024,1238,...,ENSG00000157764,ENST00000644969,ENSE00003819130,GTTTGTGCCCTGGACAAAGT,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGTTTGTGCCCTGGACAAAGTgt...,69
22178,TTTTGTGTGACAAAGCGTAA,EGFR,1175,1223,813,1009,1718,1260,582,718,...,ENSG00000146648,ENST00000275493,ENSE00001245887,GTTTGTGTGACAAAGCGTAA,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGTTTGTGTGACAAAGCGTAAgt...,69
22187,TTTTGTTTCCTTGCTCACTG,BRAF,1434,1313,1286,1516,1479,1428,1906,1673,...,ENSG00000157764,ENST00000644969,ENSE00003819130,GTTTGTTTCCTTGCTCACTG,exonic,False,NaN,NaN,atcttgtggaaaggacgaaacaccGTTTGTTTCCTTGCTCACTGgt...,69

In [4]:
df,lfc_data,zscores=process_all(df,"MC")
df

/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:183: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_pivot = df_pivot.fillna("Na")

,Guide,Gene,Editor,pDNA,H23__Adag_exp1,H23__Adag_exp2,H23__Control_exp1,H23__Control_exp2,H23__Sotor_exp1,H23__Sotor_exp2,...,H_T29__Tram_exp2,P_C9__Control_exp1,P_C9__Control_exp2,P_C9__Gefit_exp1,P_C9__Gefit_exp2,P_C9__Gefit_exp3,P_C9__Osim_exp1,P_C9__Osim_exp2,P_C9__T0_exp1,P_C9__T0_exp2
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,468,627,345,244,337,311,338,...,369,458,469,323,736,Na,401,611,663,593
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,468,226,372,416,330,380,339,...,470,446,363,418,622,139,425,354,653,376
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,720,522,569,859,560,482,579,...,516,1006,923,733,912,Na,826,758,1190,840
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,720,654,584,756,536,887,453,...,433,601,777,364,476,161,701,933,1164,822
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,965,1090,551,1760,585,557,738,...,736,1519,1083,965,928,Na,1021,860,1887,1239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45177,TTTTGTGCCCTGGACAAAGT,BRAF,CBE,1263,1238,1250,1758,1346,1598,1236,...,1041,1930,1790,1435,1813,424,1373,1258,1962,1637
45178,TTTTGTGTGACAAAGCGTAA,EGFR,ABE,1175,1056,1080,582,1073,1718,1163,...,795,1244,1441,1162,1121,Na,1359,1081,1739,1655
45179,TTTTGTGTGACAAAGCGTAA,EGFR,CBE,1175,718,1229,1260,1195,1009,903,...,858,1521,1372,1098,1181,586,1431,1082,1450,1284
45180,TTTTGTTTCCTTGCTCACTG,BRAF,ABE,1434,1948,1095,1906,1243,1479,1529,...,1003,2159,1899,1435,2606,Na,1997,1847,2434,1680
45181,TTTTGTTTCCTTGCTCACTG,BRAF,CBE,1434,1673,1600,1428,1539,1516,1268,...,1092,1820,1974,1517,1179,1182,1652,1661,2305,1808

In [4]:
(lfc_data,df_zscores)=MC_LFC_Z(df)

In [5]:
lfc_data

,Guide,Gene,Editor,H23__Adag_repA,H23__Adag_repB,H23__Sotor_repA,H23__Sotor_repB,H23__T0_repA,H23__T0_repB,H_T29__Deb_Cet_repA,...,H_T29__T0_repA,H_T29__T0_repB,H_T29__Tram_repA,H_T29__Tram_repB,P_C9__Gefit_repA,P_C9__Gefit_repB,P_C9__Osim_repA,P_C9__Osim_repB,P_C9__T0_repA,P_C9__T0_repB
0,AAAAAAAAAAACTAAGAGTT,KRAS,ABE,1.357983,0.033749,0.348764,0.004262,0.575115,-0.021501,0.506306,...,0.924449,0.184083,0.543142,0.130502,0.403212,1.124641,0.714414,0.856508,1.438401,0.813440
1,AAAAAAAAAAACTAAGAGTT,KRAS,CBE,-0.877355,0.172344,-0.130256,0.038704,0.860246,0.152875,-0.052852,...,-0.192151,0.505830,-0.056445,0.508896,0.006903,0.912401,0.030806,0.100988,0.649243,0.187733
2,AAAAAAAAAAGTAAGCTTCA,KRAS,ABE,-0.717526,0.022961,-0.832313,0.048052,-0.388443,-0.477221,-0.874749,...,-0.330340,0.205765,-0.541179,-0.117836,-0.228557,0.702614,-0.056449,0.436099,0.469765,0.584105
3,AAAAAAAAAAGTAAGCTTCA,KRAS,CBE,-0.208798,0.123515,0.230266,-0.242230,0.070662,0.060505,-0.211003,...,-0.429723,0.308432,-0.440028,-0.307227,-1.052397,-0.170933,-0.108822,0.798500,0.621965,0.615970
4,AAAAAAAAAATCAATGGTGG,BCL2,ABE,-0.690744,-0.086232,-1.658058,0.334674,-1.184127,0.193260,-1.199096,...,-0.950872,0.704600,-0.839665,0.330764,-0.866300,0.664778,-0.785000,0.555113,0.100464,1.081368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45177,TTTTGTGCCCTGGACAAAGT,BRAF,CBE,-0.505579,-0.106668,-0.137586,-0.122904,-0.155744,-0.257262,-0.848325,...,-0.762340,0.056707,-0.537366,-0.370395,-0.292700,0.429425,-0.356373,-0.097472,0.158305,0.282186
45178,TTTTGTGTGACAAAGCGTAA,EGFR,ABE,0.858408,0.009373,1.560002,0.116097,0.481533,-0.138041,0.543967,...,0.851567,-0.056154,0.798490,-0.432154,0.996283,0.063079,1.222039,0.010707,1.577520,0.624709
45179,TTTTGTGTGACAAAGCGTAA,EGFR,CBE,-0.810505,0.040441,-0.320213,-0.403823,-0.042965,-0.101174,-0.557201,...,-0.681967,-0.059095,-0.610355,-0.477487,-0.198377,-0.016987,0.183463,-0.143184,0.202479,0.103551
45180,TTTTGTTTCCTTGCTCACTG,BRAF,ABE,0.031429,-0.182739,-0.365708,0.298545,-0.567293,0.054620,-0.867802,...,-0.435610,0.112620,-0.667069,-0.309227,-0.409249,1.067404,0.067252,0.570978,0.352617,0.434333
45181,TTTTGTTTCCTTGCTCACTG,BRAF,CBE,0.228294,0.056043,0.086215,-0.279238,-0.121041,-0.183573,-0.329774,...,-0.307113,-0.074001,-0.560437,-0.494637,0.087166,-0.384143,0.210081,0.109990,0.690387,0.232262

# RH

In [2]:
df=pd.read_excel("/Users/joanacorreia/Desktop/Tese/Original Counts files/RH/counts_PARP1.xlsx",header=None, sheet_name='BE3_HAP1')
#df has all unique guides

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Cell line,pDNA,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1,HAP1
1,Condition,pDNA,Dropout,Dropout,Niraparib,Niraparib,Olaparib,Olaparib,Rucaparib,Rucaparib,Talazoparib,Talazoparib,Veliparib,Veliparib
2,sgRNA sequence,pDNA,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB,RepA,RepB
3,AAAAAACAAAGAGGTTAAGT,637,248,295,453,201,271,301,434,205,653,471,556,419
4,AAAAAACCAAATCGCCACGT,1214,685,658,511,641,506,382,581,472,747,1096,854,842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11452,TTTGTCCCCCAGCTCCGGAG,1183,238,294,293,260,236,216,248,186,337,287,230,243
11453,TTTGTGAATAAATGGTAAGT,871,879,749,627,702,482,530,508,581,908,816,719,919
11454,TTTGTGGATGGTAAGAATTG,1094,993,1084,804,670,711,578,715,940,1135,1195,901,1197
11455,TTTGTTCTCCACTAGCACCA,1508,509,418,410,371,462,401,548,320,748,731,552,846
11456,TTTGTTGATGGCCTCTCGGA,1515,1254,1113,957,605,924,714,709,654,1545,888,1400,1153

In [4]:
df,lfc_data,zscores=process_all(df,"RH",subset='PARP1_set')

/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'sgRNA sequence': 'Guide'}, inplace=True)
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'GeneID': 'Gene'}, inplace=True)
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected['Editor'] = df2_selected['Editor'].replace({'A-G': 'ABE', 'C-T': 'CBE'})

In [19]:
lfc_data

,Guide,Gene,Editor,pDNA,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,AAAAAACAAAGAGGTTAAGT,NaN,NaN,0.0,-1.357411,-1.107959,-0.490864,-1.659201,-1.22995,-1.079008,-0.552541,-1.630912,0.035734,-0.43477,-0.195879,-0.603167
1,AAAAAACCAAATCGCCACGT,NaN,NaN,0.0,-0.824676,-0.882606,-1.246741,-0.920311,-1.260899,-1.66554,-1.061865,-1.361044,-0.699846,-0.147393,-0.50696,-0.527352
2,AAAAAACTGTTTGGGACCTC,NaN,NaN,0.0,-0.198761,-0.499628,-0.343449,-0.312511,-0.895434,-1.019854,-0.648794,-0.39006,0.202062,0.194903,-0.335134,0.383055
3,AAAAAAGAGATCCACAAAGA,NaN,NaN,0.0,-1.474343,-1.428701,-1.355699,-2.516164,-1.581259,-2.684763,-2.049037,-1.684763,-0.789845,-0.988917,-0.967002,-1.295287
4,AAAAACACCCATCCAGGCAG,NaN,NaN,0.0,-0.46828,-0.726549,-0.673063,-0.923649,-0.705939,-1.406698,-0.859648,-1.201634,-0.381966,-0.534877,-0.581047,-0.406698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449,TTTGTCCCCCAGCTCCGGAG,NaN,NaN,0.0,-2.308587,-2.004882,-2.009781,-2.181547,-2.32071,-2.447902,-2.249451,-2.662559,-1.808574,-2.039528,-2.357704,-2.278716
11450,TTTGTGAATAAATGGTAAGT,NaN,NaN,0.0,0.013175,-0.217438,-0.473564,-0.310803,-0.852305,-0.715616,-0.776662,-0.583309,0.059952,-0.093992,-0.276331,0.077306
11451,TTTGTGGATGGTAAGAATTG,NaN,NaN,0.0,-0.139613,-0.013236,-0.44387,-0.706546,-0.620982,-0.919296,-0.612899,-0.218664,0.053032,0.127287,-0.279732,0.129697
11452,TTTGTTCTCCACTAGCACCA,NaN,NaN,0.0,-1.565024,-1.848571,-1.876383,-2.020218,-1.704509,-1.908325,-1.458715,-2.232948,-1.010555,-1.043677,-1.448241,-0.833159
11453,TTTGTTGATGGCCTCTCGGA,NaN,NaN,0.0,-0.272582,-0.444521,-0.662172,-1.32288,-0.712744,-1.084255,-1.094379,-1.210703,0.028271,-0.770014,-0.113813,-0.393627

In [ ]:
from Process import process_RH, RH_LFC_Z
df=process_RH(df,subset='PARP1_set') #only CBE editors and Nan, no ABE
df.sort_values(by="Gene")
#df.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_processed.csv", index=False)

,Guide,Gene,Editor,pDNA,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,1214,685,658,511,641,506,382,581,472,747,1096,854,842
329,CGGCGTACAGCCTATCCGCG,Intergenic control,NaN,783,465,408,390,340,249,209,362,327,559,470,640,687
328,GGGCTCAGGAATATCACGTC,Intergenic control,NaN,1200,979,1193,851,853,603,731,671,813,986,1286,757,1362
327,GGGGAGTTTCAGCCCAACGA,Intergenic control,NaN,1068,627,667,600,458,413,405,506,507,778,917,675,684
326,CTCCGAGTGGGAACTAACAC,Intergenic control,NaN,935,744,857,679,704,841,694,678,688,803,934,848,1126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449,TTTGTCCCCCAGCTCCGGAG,NaN,NaN,1183,238,294,293,260,236,216,248,186,337,287,230,243
11450,TTTGTGAATAAATGGTAAGT,NaN,NaN,871,879,749,627,702,482,530,508,581,908,816,719,919
11451,TTTGTGGATGGTAAGAATTG,NaN,NaN,1094,993,1084,804,670,711,578,715,940,1135,1195,901,1197
11452,TTTGTTCTCCACTAGCACCA,NaN,NaN,1508,509,418,410,371,462,401,548,320,748,731,552,846
11453,TTTGTTGATGGCCTCTCGGA,NaN,NaN,1515,1254,1113,957,605,924,714,709,654,1545,888,1400,1153

In [10]:
df_lfc, df_zscores=RH_LFC_Z(df)

In [11]:
df_lfc

,Guide,Gene,Editor,pDNA,HAP1_Dropout_RepA,HAP1_Dropout_RepB,HAP1_Niraparib_RepA,HAP1_Niraparib_RepB,HAP1_Olaparib_RepA,HAP1_Olaparib_RepB,HAP1_Rucaparib_RepA,HAP1_Rucaparib_RepB,HAP1_Talazoparib_RepA,HAP1_Talazoparib_RepB,HAP1_Veliparib_RepA,HAP1_Veliparib_RepB
0,AAAAAACCAAATCGCCACGT,Intergenic control,NaN,0.0,-0.824676,-0.882606,-1.246741,-0.920311,-1.260899,-1.66554,-1.061865,-1.361044,-0.699846,-0.147393,-0.50696,-0.527352
1,TATATGACGTCCTCACGCCG,Intergenic control,NaN,0.0,0.159292,-0.318813,0.527702,-0.8861,-0.589425,-1.557599,-0.43568,-0.728673,0.31281,-0.317702,-0.047098,-0.216908
2,CAATGTAGGGAGCCTAGCGC,Intergenic control,NaN,0.0,0.131176,-0.887683,-0.215831,-1.163625,0.038931,-1.308573,-0.236138,-1.142563,0.247429,-0.028695,-0.061263,-0.413986
3,CAATTGGGATGACGCACCCC,Intergenic control,NaN,0.0,-0.097668,0.048113,-0.135912,-0.512299,-0.159862,-0.986411,-0.548451,-0.390967,0.39902,0.320107,0.156207,0.30821
4,CAATTTGCTTAGGCGACCTG,Intergenic control,NaN,0.0,-0.304742,-0.433728,-0.157135,-0.883784,-0.445452,-0.705612,-0.435026,-0.899824,0.346688,-0.317852,0.082142,-0.125356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11449,TTTGTCCCCCAGCTCCGGAG,NaN,NaN,0.0,-2.308587,-2.004882,-2.009781,-2.181547,-2.32071,-2.447902,-2.249451,-2.662559,-1.808574,-2.039528,-2.357704,-2.278716
11450,TTTGTGAATAAATGGTAAGT,NaN,NaN,0.0,0.013175,-0.217438,-0.473564,-0.310803,-0.852305,-0.715616,-0.776662,-0.583309,0.059952,-0.093992,-0.276331,0.077306
11451,TTTGTGGATGGTAAGAATTG,NaN,NaN,0.0,-0.139613,-0.013236,-0.44387,-0.706546,-0.620982,-0.919296,-0.612899,-0.218664,0.053032,0.127287,-0.279732,0.129697
11452,TTTGTTCTCCACTAGCACCA,NaN,NaN,0.0,-1.565024,-1.848571,-1.876383,-2.020218,-1.704509,-1.908325,-1.458715,-2.232948,-1.010555,-1.043677,-1.448241,-0.833159
11453,TTTGTTGATGGCCTCTCGGA,NaN,NaN,0.0,-0.272582,-0.444521,-0.662172,-1.32288,-0.712744,-1.084255,-1.094379,-1.210703,0.028271,-0.770014,-0.113813,-0.393627

In [51]:
df_lfc.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Tables/RH/RH_PARP1_Zscores.csv", index=False)

# GR

In [12]:
import pandas as pd
#/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-MELJUSO_ABE.txt
#"/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-A549_ABE_CBE_MELJUSO_CBE.txt
df=pd.read_csv("/Users/joanacorreia/Desktop/Tese/Original Counts files/GR/counts-A549_ABE_CBE_MELJUSO_CBE.txt")
df.sort_values(by="Construct Barcode") #all unique guides

,Construct Barcode,Construct IDs,A549_ABE_repA,A549_ABE_repB,A549_CBE_repA,A549_CBE_repB,Meljuso_CBE_repA,Meljuso_CBE_repB,pDNA_CP1965
2267,AAAAAACATACCTCAACCCT,ENSG00000149554,7196,7384,7115,5185,7695,11196,6186
2732,AAAAAACTCAACAGCAGTGA,ENSG00000213281,12030,11611,10438,11090,10779,18113,8010
2268,AAAAACATACCTCAACCCTT,ENSG00000149554,6941,9996,8747,7866,8759,11528,7427
4690,AAAAAGAAGAACCAGTGGTT,ENSG00000166851,7849,8036,5563,7116,7171,11166,5380
4059,AAAAAGCATCCTCCACTCTC,ENSG00000133703,9682,9476,7024,6181,8963,13702,7379
...,...,...,...,...,...,...,...,...,...
2783,TTTGTATCAACTGTCCTTGT,ENSG00000213281,9864,8046,7473,6704,8376,12561,6030
2006,TTTGTGGAAGACTGGGACTT,ENSG00000149554,10202,9902,10802,8152,9347,14213,8113
3446,TTTGTGGTGTCACCTGAACC,ENSG00000170836,9799,9639,9055,6288,7598,11234,7232
3894,TTTGTGTCTACTGTTCTAGA,ENSG00000133703,8636,9770,9148,8581,9986,16557,8657
5636,TTTGTTACCTTATCGGCCAC,ENSG00000138160,5668,7111,4216,5046,6084,8681,5534

In [13]:
from Process import process_GR,GR_LFC_Z
df=process_GR(df)
df
#df.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Processed.csv", index=False)

Warning: Some reordered columns not found in DataFrame.

/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:127: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected.rename(columns={'sgRNA sequence': 'Guide'}, inplace=True)
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:128: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_selected['Editor'] = df2_selected['Editor'].replace({'A-G': 'ABE', 'C-T': 'CBE'})

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,8657,9148,8581,9986.0,16557.0
1,TGTAGGAATCCTGAGAAGGG,KRAS,ABE,8189,6595,4856,NaN,NaN
2,TGTAGGAATCCTGAGAAGGG,KRAS,CBE,8189,6356,6687,7986.0,12115.0
3,GATGTACCTATGGTCCTAGT,KRAS,CBE,6649,6762,6013,8186.0,13191.0
4,ACACAAAGAAAGCCCTCCCC,KRAS,CBE,4676,6117,5804,6323.0,9556.0
...,...,...,...,...,...,...,...,...
11361,TTTGTGGAAGACTGGGACTT,NaN,CBE,8113,10802,8152,9347.0,14213.0
11362,TTTGTGGTGTCACCTGAACC,NaN,ABE,7232,9799,9639,NaN,NaN
11363,TTTGTGGTGTCACCTGAACC,NaN,CBE,7232,9055,6288,7598.0,11234.0
11364,TTTGTTACCTTATCGGCCAC,NaN,ABE,5534,5668,7111,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,NaN,CBE,5534,4216,5046,6084.0,8681.0

In [14]:
df_lfc, df_zscores=GR_LFC_Z(df)

/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:152: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0        0.079580
1       -0.312272
2       -0.365517
3        0.024309
4        0.387477
           ...
11361    0.412947
11362    0.438188
11363    0.324280
11364    0.034511
11365   -0.392366
Length: 11366, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_lfc.iloc[:, i]= np.log2(pd.to_numeric((table1.iloc[:, i] + 1) / (table1[reference_col][:] + 1)))
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0       -0.600912
1       -1.906752
2       -2.084191
3       -0.785102
4        0.425147
           ...
11361    0.510026
11362    0.594140
11363    0.214545
11364   -0.751105
11365   -2.173665
Name: A549_repA, Length: 11366, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_zscores.iloc[:, i]= (df_lfc.iloc[:, i] - np.mean(df_lfc.iloc[:, i])) / np.std(df_lfc.iloc[:, i])
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:152: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0       -0.012720
1       -0.753798
2       -0.292289
3       -0.145029
4        0.311713
           ...
11361    0.006918
11362    0.414439
11363   -0.201764
11364    0.361672
11365   -0.133157
Length: 11366, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_lfc.iloc[:, i]= np.log2(pd.to_numeric((table1.iloc[:, i] + 1) / (table1[reference_col][:] + 1)))
/Users/joanacorreia/Desktop/Tese/Processamento/Process.py:154: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0       -0.470400
1       -2.699874
2       -1.311460
3       -0.868443
4        0.505630
           ...
11361   -0.411322
11362    0.814674
11363   -1.039122
11364    0.655928
11365   -0.832726
Name: A549_repB, Length: 11366, dtype: float64' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_zscores.iloc[:, i]= (df_lfc.iloc[:, i] - np.mean(df_lfc.iloc[:, i])) / np.std(df_lfc.iloc[:, i])

In [15]:
df_zscores

,Guide,Gene,Editor,pDNA,A549_repA,A549_repB,Meljuso_repA,Meljuso_repB
0,TTTGTGTCTACTGTTCTAGA,KRAS,CBE,NaN,-0.600912,-0.470400,-0.107582,0.370895
1,TGTAGGAATCCTGAGAAGGG,KRAS,ABE,NaN,-1.906752,-2.699874,NaN,NaN
2,TGTAGGAATCCTGAGAAGGG,KRAS,CBE,NaN,-2.084191,-1.311460,-0.915076,-0.850521
3,GATGTACCTATGGTCCTAGT,KRAS,CBE,NaN,-0.785102,-0.868443,0.205655,0.545033
4,ACACAAAGAAAGCCCTCCCC,KRAS,CBE,NaN,0.425147,0.505630,0.656606,0.685945
...,...,...,...,...,...,...,...,...
11361,TTTGTGGAAGACTGGGACTT,NaN,CBE,NaN,0.510026,-0.411322,-0.113493,-0.046510
11362,TTTGTGGTGTCACCTGAACC,NaN,ABE,NaN,0.594140,0.814674,NaN,NaN
11363,TTTGTGGTGTCACCTGAACC,NaN,CBE,NaN,0.214545,-1.039122,-0.556961,-0.618546
11364,TTTGTTACCTTATCGGCCAC,NaN,ABE,NaN,-0.751105,0.655928,NaN,NaN
11365,TTTGTTACCTTATCGGCCAC,NaN,CBE,NaN,-2.173665,-0.832726,-0.338747,-0.572023

In [15]:
df_lfc.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_LFC.csv", index=False)
df_zscores.to_csv("/Users/joanacorreia/Desktop/Tese/Processed Tables/GR/GR_A549_ABE_CBE_MELJUSO_CBE_Zscores.csv", index=False)